"""Cross-text units, batch 3 (format in passage_data1.py). Original texts; studies are illustrative."""

UNITS = """
P: Some writers claim that people learn best when information matches their preferred "learning style," such as visual or auditory.
P2: Studies that tested students' preferred styles and then taught them in matching or mismatching ways found little difference in learning. Students may prefer certain formats, but most people learn more from combining words, images, and active practice than from a single mode. Researchers suggest that the content being taught, not an individual's supposed style, should guide instruction.
CT:: || By arguing that matching instruction to preferred styles does not improve learning and that mixed approaches are generally more effective || By agreeing that teaching to learning styles greatly improves learning || By claiming that students have no preferences for formats || By arguing that images should never be used in teaching >> Studies found little difference; combining modes helps more.
CT: The author of Text 2 would most likely agree with Text 1 that || students may prefer certain formats of information. || learning styles determine how much students learn. || auditory learners cannot learn from images. || instruction should use only one mode. >> "Students may prefer certain formats."
CT: Based on Text 2, researchers recommend that instruction be guided mainly by || the nature of the content being taught. || each student's preferred learning style. || the number of students in the class. || the teacher's favorite format. >> "The content being taught ... should guide instruction."

P: Some city officials argue that increasing police patrols is the most effective way to reduce crime in neighborhoods.
P2: Research in several cities has found that improving street lighting and cleaning up vacant lots were associated with reductions in certain crimes, sometimes at lower cost than additional patrols. Researchers suggest that changes to the physical environment can complement other public safety strategies.
CT:: || By presenting evidence that environmental improvements can also reduce crime and may complement other strategies || By agreeing that patrols are the only effective approach || By claiming that street lighting increases crime || By arguing that vacant lots should be left untouched >> Lighting and lot cleanup reduced some crimes.
CT: Based on Text 2, one advantage of improving street lighting is that it || can reduce certain crimes at relatively low cost. || eliminates all crime. || replaces the need for police. || increases the number of vacant lots. >> "Sometimes at lower cost than additional patrols."
CT: Which choice best describes how Text 2 relates to Text 1? || It suggests additional approaches beyond the one proposed in Text 1. || It provides evidence that patrols increase crime. || It agrees that patrols are the most effective approach. || It discusses crime in a different century. >> Environmental changes "complement other public safety strategies."

P: Some biologists have argued that animals that live in groups always benefit from doing so, because groups offer protection from predators.
P2: Group living can reduce predation, but it also has costs. Animals in large groups must compete for food, and diseases spread more easily among closely packed individuals. Whether group living is beneficial overall depends on factors such as food availability and predation pressure.
CT:: || By acknowledging the protective benefit of groups while arguing that group living also has costs that vary with conditions || By agreeing that group living is always beneficial || By claiming that groups offer no protection from predators || By arguing that animals should always live alone >> Protection plus competition and disease.
CT: Based on Text 2, one cost of living in a large group is that || diseases can spread more easily. || predators become more common. || animals find food more easily. || animals cannot communicate. >> "Diseases spread more easily among closely packed individuals."
CT: The author of Text 2 would most likely object to the word "always" in Text 1 because || the benefits of group living depend on circumstances. || group living never protects animals. || all animals live in groups. || predators avoid groups. >> Benefit "depends on factors such as food availability."

P: Some critics argue that audiences prefer films based on original stories rather than sequels and remakes.
P2: Box office data from recent decades show that sequels and remakes have frequently been among the highest-earning films each year. Surveys, however, suggest that many viewers say they want more original films, even as they buy tickets to familiar franchises. What audiences say and what they choose may differ.
CT:: || By noting that ticket sales favor sequels and remakes even though many viewers say they want originality || By agreeing that original films always earn more than sequels || By claiming that audiences never watch sequels || By suggesting that surveys accurately predict ticket sales >> Stated preferences differ from purchasing behavior.
CT: Based on Text 2, the surveys and box office data together suggest that || viewers' stated preferences may not match their choices. || audiences dislike all films. || original films earn the most money. || viewers never answer surveys honestly. >> "What audiences say and what they choose may differ."
CT: The author of Text 2 would most likely say that the critics' claim in Text 1 || reflects what many viewers say but not what box office data show. || is fully supported by box office data. || ignores surveys of viewers. || applies only to animated films. >> Surveys support it; ticket sales do not.

P: Some ecologists claim that cats kept indoors live healthier lives than cats allowed outdoors.
P2: Surveys of veterinarians and pet insurance records suggest that indoor cats face lower risks of injury from traffic, fights, and certain infectious diseases, and often live longer. However, some indoor cats become overweight or bored without enough activity, so veterinarians recommend providing play and climbing spaces.
CT:: || By supporting the claim while noting that indoor cats need enrichment to avoid problems such as weight gain and boredom || By claiming that outdoor cats always live longer || By arguing that indoor cats face more injuries from traffic || By suggesting that cats should never be kept as pets >> Lower risks indoors, with a caveat about activity.
CT: Based on Text 2, veterinarians recommend play and climbing spaces for indoor cats in order to || prevent weight gain and boredom. || reduce traffic injuries. || cure infectious diseases. || help cats find food outdoors. >> Some indoor cats become "overweight or bored."
CT: Which choice best describes the relationship between the texts? || Text 2 supports Text 1's claim but adds a qualification. || Text 2 rejects Text 1's claim entirely. || Text 2 discusses dogs rather than cats. || Text 2 restates Text 1 without evidence. >> Supportive evidence plus the need for enrichment.

P: Some historians describe a famous explorer as the first person to reach a particular region of North America.
P2: Indigenous peoples had lived in the region for thousands of years before the explorer arrived, and oral histories and archaeological sites document their long presence. The explorer's journey was significant for European knowledge of the area, but describing him as the first to reach it overlooks the people who already lived there.
CT:: || By pointing out that Indigenous peoples had lived in the region long before the explorer arrived || By agreeing that the explorer was the first person in the region || By claiming that the explorer never traveled to the region || By arguing that archaeological sites are unreliable >> Indigenous presence predates the explorer.
CT: The author of Text 2 acknowledges that the explorer's journey || was significant for European knowledge of the region. || was the first human arrival in the region. || had no historical importance. || was invented by historians. >> "Significant for European knowledge of the area."
CT: Based on Text 2, evidence of Indigenous presence in the region comes from || oral histories and archaeological sites. || the explorer's diary alone. || modern maps only. || European census records. >> "Oral histories and archaeological sites document their long presence."

P: Some scientists argue that planting trees is one of the most effective ways to fight climate change.
P2: Trees absorb carbon dioxide as they grow, and restoring forests can store significant amounts of carbon. However, new forests take decades to mature, planting in the wrong places can harm grasslands or water supplies, and trees can release stored carbon if they burn. Many researchers see tree planting as helpful but not a substitute for reducing emissions.
CT:: || By agreeing that trees store carbon while cautioning about limitations and arguing that planting cannot replace emission reductions || By claiming that trees do not absorb carbon dioxide || By arguing that forests should be cut down || By agreeing that tree planting alone will solve climate change >> Benefits plus limits; not a substitute.
CT: Based on Text 2, one risk of planting trees in the wrong places is that it can || harm grasslands or water supplies. || make trees grow faster. || prevent all forest fires. || reduce emissions from cars. >> Planting in the wrong places "can harm grasslands or water supplies."
CT: The author of Text 2 would most likely agree with the scientists in Text 1 that || restoring forests can store significant amounts of carbon. || tree planting is a complete solution. || forests never burn. || emissions do not need to be reduced. >> "Restoring forests can store significant amounts of carbon."

P: Many people believe that humans use only ten percent of their brains.
P2: Brain imaging shows activity throughout the brain, though not all regions are equally active at the same moment. Damage to almost any area of the brain can affect abilities, which would be unlikely if most of the brain went unused. Neuroscientists regard the ten-percent idea as a myth.
CT:: || By citing brain imaging and effects of brain damage as evidence that people use far more than ten percent of their brains || By agreeing that most of the brain is unused || By claiming that brain imaging shows no activity || By arguing that brain damage has no effects >> Activity throughout the brain and effects of damage.
CT: The author of Text 2 mentions brain damage mainly to || show that nearly every area of the brain serves a function. || explain how imaging devices work. || argue that people should avoid injuries. || suggest that most brain regions are unnecessary. >> Damage anywhere affects abilities.
CT: Based on Text 2, which statement is accurate? || Not all brain regions are equally active at every moment. || Only ten percent of the brain is ever active. || Brain imaging cannot detect activity. || Neuroscientists support the ten-percent idea. >> "Not all regions are equally active at the same moment."

P: Some urban planners argue that tall residential towers are the best way to house growing city populations.
P2: Towers can house many people on small plots of land, but mid-rise buildings of four to eight stories can achieve similar densities across a neighborhood while keeping residents closer to street life. Some studies suggest that residents of mid-rise neighborhoods report stronger connections with neighbors than residents of isolated high-rise towers.
CT:: || By suggesting that mid-rise buildings can provide similar density with social advantages || By agreeing that towers are the only way to increase density || By claiming that mid-rise buildings house fewer people than single-family homes || By arguing that cities should stop growing >> Mid-rises achieve density while supporting connections.
CT: The author of Text 2 would most likely agree with Text 1 that towers || can house many people on small plots of land. || strengthen connections among neighbors. || are always better than mid-rise buildings. || cannot be built in cities. >> "Towers can house many people on small plots."
CT: Based on Text 2, an advantage of mid-rise neighborhoods is that residents || may feel more connected to their neighbors. || live farther from street life. || require more land per person than towers in every case. || have fewer neighbors. >> Residents "report stronger connections."

P: Some educators argue that grades motivate students to work hard.
P2: Grades can encourage effort, especially for students focused on college admissions. But research suggests that when grades become the main goal, some students choose easier tasks to protect their scores and lose interest in learning for its own sake. Feedback that explains how to improve may sustain motivation more effectively for many students.
CT:: || By acknowledging that grades can encourage effort while arguing that they can also undermine interest and challenge-seeking || By agreeing that grades are the best motivation for all students || By claiming that grades never motivate anyone || By arguing that feedback reduces motivation >> Grades help some but can have drawbacks.
CT: Based on Text 2, when grades become students' main goal, some students || choose easier tasks to protect their scores. || seek out the hardest tasks. || stop attending school. || ignore their grades. >> "Some students choose easier tasks to protect their scores."
CT: The author of Text 2 suggests that an alternative way to sustain motivation is || feedback that explains how to improve. || eliminating all assignments. || giving every student the same grade. || assigning more tests. >> Explanatory feedback "may sustain motivation more effectively."

P: Some historians claim that medieval people believed the Earth was flat.
P2: Educated writers throughout the Middle Ages generally accepted that the Earth was round, a view inherited from ancient Greek scholars. Textbooks used in medieval universities described a spherical Earth. The idea that medieval people commonly believed in a flat Earth became popular much later, partly through nineteenth-century writers.
CT:: || By arguing that educated medieval people generally knew the Earth was round and that the flat-Earth belief is a later myth || By agreeing that medieval people believed the Earth was flat || By claiming that ancient Greeks believed the Earth was flat || By arguing that universities did not exist in the Middle Ages >> Medieval textbooks described a spherical Earth.
CT: Based on Text 2, the idea that medieval people believed in a flat Earth || became popular much later, partly through nineteenth-century writers. || came from medieval university textbooks. || was proven by ancient Greeks. || was accepted by all medieval scholars. >> It "became popular much later."
CT: The author of Text 2 mentions university textbooks mainly to || provide evidence of what educated medieval people believed. || argue that universities were expensive. || describe how books were printed. || show that textbooks contained errors. >> Textbooks described a spherical Earth.

P: Some people argue that working longer hours always leads to greater productivity.
P2: Studies of factory and office workers have found that output per hour tends to decline when work weeks become very long. Beyond a certain point, fatigue leads to more errors and accidents, so additional hours add little or even reduce total output. Many companies have found that moderate schedules with adequate rest sustain productivity better.
CT:: || By presenting evidence that very long hours can reduce productivity because of fatigue || By agreeing that longer hours always increase productivity || By claiming that workers never make errors || By arguing that rest reduces productivity >> Output per hour falls, and errors rise.
CT: Based on Text 2, very long work weeks can reduce output mainly because || fatigue causes more errors and accidents. || workers have too much rest. || companies pay workers less. || factories close earlier. >> "Fatigue leads to more errors and accidents."
CT: The author of Text 2 would most likely object to the word "always" in Text 1 because || additional hours eventually stop increasing productivity. || workers never work long hours. || productivity cannot be measured. || rest always reduces output. >> Beyond a point, extra hours add little.

P: Some critics argue that video calls can fully replace in-person meetings for business teams.
P2: Video calls save travel time and allow teams in different cities to meet easily. However, surveys of workers report that brainstorming and building trust with new colleagues often feel more difficult over video, and informal conversations before and after meetings are less common. Many teams now mix video calls with occasional in-person gatherings.
CT:: || By acknowledging the benefits of video calls while arguing that some kinds of collaboration work better in person || By agreeing that video calls fully replace in-person meetings || By claiming that video calls waste time || By arguing that teams should never meet in person >> Brainstorming and trust-building can suffer over video.
CT: Based on Text 2, one thing that tends to happen less during video calls is || informal conversation before and after meetings. || saving travel time. || meetings between people in different cities. || scheduled discussion. >> "Informal conversations ... are less common."
CT: The author of Text 2 would most likely agree with the critics in Text 1 that video calls || make it easier for teams in different cities to meet. || are best for building trust with new colleagues. || eliminate the need for travel entirely. || improve brainstorming. >> They "allow teams in different cities to meet easily."

P: Some nutrition writers argue that fresh vegetables are always more nutritious than frozen ones.
P2: Vegetables are often frozen within hours of harvest, preserving many vitamins, while fresh vegetables may spend days in transport and storage, losing nutrients along the way. Studies comparing the two have found that frozen vegetables are often similar in nutrients to fresh ones and sometimes contain more of certain vitamins.
CT:: || By presenting evidence that frozen vegetables can be as nutritious as fresh ones, and sometimes more so || By agreeing that fresh vegetables are always more nutritious || By claiming that frozen vegetables contain no vitamins || By arguing that vegetables should not be eaten >> Quick freezing preserves nutrients.
CT: Based on Text 2, fresh vegetables may lose nutrients because they || spend days in transport and storage. || are frozen too quickly. || are grown in greenhouses. || contain added preservatives. >> Transport and storage cause losses.
CT: The author of Text 2 would most likely object to the word "always" in Text 1 because || frozen vegetables sometimes contain more of certain vitamins. || fresh vegetables are never nutritious. || all vegetables are frozen before sale. || nutrients cannot be measured. >> Frozen can sometimes be better.

P: Some writers say that the Industrial Revolution made life worse for ordinary workers.
P2: Early factory work was often dangerous, hours were long, and crowded cities bred disease. Over time, however, rising productivity contributed to higher wages, cheaper goods, and eventually to reforms such as limits on child labor and working hours. The period's effects on workers changed considerably over the course of the century.
CT:: || By acknowledging early hardships while arguing that conditions for workers improved over time || By claiming that factory work was always safe || By agreeing that life only worsened throughout the period || By arguing that cities had no disease >> Early hardship, later improvements and reforms.
CT: The author of Text 2 would most likely agree with the writers in Text 1 that || early factory work was often dangerous. || workers' lives never improved. || reforms made conditions worse. || cities were free of disease. >> "Early factory work was often dangerous."
CT: Based on Text 2, one later development that helped workers was || reforms limiting child labor and working hours. || longer hours in factories. || more crowded cities. || higher prices for goods. >> Reforms "such as limits on child labor and working hours."

P: Some scientists have claimed that birds' feathers first evolved to help them fly.
P2: Fossils show that several dinosaurs that could not fly already had feathers. Some of these feathers were simple filaments that likely provided insulation, and others may have been used in displays to attract mates. Feathers may have been adapted for flight only later in the history of birds' ancestors.
CT:: || By presenting fossil evidence that feathers existed in non-flying dinosaurs and likely served other purposes first || By agreeing that feathers evolved only for flight || By claiming that dinosaurs never had feathers || By arguing that birds cannot fly >> Flightless dinosaurs had feathers used for insulation or display.
CT: Based on Text 2, simple filament feathers in some dinosaurs likely helped with || insulation. || gliding long distances. || swimming. || digging burrows. >> They "likely provided insulation."
CT: Which choice best describes the relationship between the texts? || Text 2 offers evidence suggesting a different origin for feathers than the one proposed in Text 1. || Text 2 confirms that feathers evolved for flight. || Text 2 discusses the flight of insects. || Text 2 agrees that dinosaurs could fly. >> Feathers predate flight.

P: Some parents worry that children who have imaginary friends are lonely or have trouble making real friends.
P2: Studies of preschool children have found that those with imaginary companions are generally as socially skilled as other children, and some show especially strong abilities to understand other people's perspectives. Imaginary friends appear to be a common and healthy part of development for many children.
CT:: || By presenting evidence that children with imaginary friends are typically socially skilled || By agreeing that imaginary friends indicate loneliness || By claiming that imaginary friends harm development || By arguing that preschool children cannot make friends >> Studies show normal or strong social skills.
CT: Based on Text 2, some children with imaginary companions show particular strength in || understanding other people's perspectives. || memorizing numbers. || physical coordination. || spelling. >> "Especially strong abilities to understand other people's perspectives."
CT: The author of Text 2 would most likely describe imaginary friends as || common and healthy for many children. || a sign of serious problems. || rare among preschool children. || harmful to friendships. >> "A common and healthy part of development."

P: Some energy experts argue that nuclear power is too dangerous to be part of efforts to reduce carbon emissions.
P2: Nuclear accidents have caused serious harm, and long-term storage of radioactive waste remains a challenge. Yet measured by deaths per unit of electricity produced, nuclear power has a safety record comparable to wind and solar and far better than coal. Some researchers argue that its risks should be weighed against the harms of fossil fuels.
CT:: || By acknowledging nuclear power's risks while arguing that its safety record compares favorably with fossil fuels || By agreeing that nuclear power should be excluded from all energy plans || By claiming that nuclear waste poses no challenges || By arguing that coal is safer than nuclear power >> Risks exist, but safety record is comparable to renewables.
CT: The author of Text 2 would most likely agree with the experts in Text 1 that || nuclear accidents have caused serious harm. || nuclear power is more dangerous than coal. || waste storage is easy. || wind power is unsafe. >> "Nuclear accidents have caused serious harm."
CT: Based on Text 2, nuclear power's safety record, measured by deaths per unit of electricity, is || comparable to wind and solar and better than coal. || worse than coal. || the worst of all energy sources. || impossible to measure. >> "Comparable to wind and solar and far better than coal."

P: Some writers argue that handwriting is no longer an important skill in the digital age.
P2: Adults increasingly type rather than write by hand, but studies of young children suggest that learning to form letters by hand helps them recognize letters and learn to read. Handwritten notes may also help some students remember information better than typed notes. The value of handwriting may lie partly in its effects on learning, not only in its everyday use.
CT:: || By arguing that handwriting may benefit learning even if adults rarely use it || By agreeing that handwriting has no value || By claiming that adults write more by hand than they type || By arguing that children should never type >> Handwriting helps letter recognition and memory.
CT: The author of Text 2 would most likely agree with the writers in Text 1 that || adults increasingly type instead of writing by hand. || handwriting is essential for all adult jobs. || typing harms children's reading. || notes should never be typed. >> "Adults increasingly type rather than write by hand."
CT: Based on Text 2, learning to form letters by hand may help young children || recognize letters and learn to read. || type faster. || avoid using computers. || draw pictures more accurately. >> It "helps them recognize letters and learn to read."

P: Some sports commentators claim that home teams win more often mainly because of cheering crowds.
P2: When sports leagues played games without fans during a period of restrictions, the home advantage shrank in some sports but did not disappear. Researchers suggest that familiarity with the venue, reduced travel fatigue, and referees' decisions all contribute, with crowds being one factor among several.
CT:: || By presenting evidence that crowds are only one of several factors behind home advantage || By agreeing that crowds are the only reason home teams win || By claiming that home teams never have an advantage || By arguing that referees always favor visiting teams >> Home advantage persisted without fans.
CT: Based on Text 2, when games were played without fans, the home advantage || shrank in some sports but did not disappear. || vanished completely. || grew much larger. || could not be measured. >> It "shrank in some sports but did not disappear."
CT: The author of Text 2 would most likely agree with Text 1 that crowds || may contribute to home advantage. || have no effect on games. || are the sole cause of home advantage. || cause visiting teams to win. >> Crowds are "one factor among several."
"""
