"""Cross-text units, batch 1. Each unit: P (Text 1), P2 (Text 2), then CT questions (format in passage_data1.py).
Original texts; people and studies are illustrative."""

UNITS = """
P: Many city leaders argue that free public transit would dramatically reduce car traffic. If riders no longer had to pay, they reason, far more commuters would leave their cars at home.
P2: When one mid-sized city eliminated bus fares, ridership rose by about a third. Traffic surveys, however, showed little change in car trips. Most new riders had previously walked or biked; few had switched from driving. Researchers concluded that for many drivers, travel time and convenience mattered more than cost.
CT:: || By arguing that making transit free may not convince many drivers to switch, because cost is not their main consideration || By agreeing that free transit greatly reduces car traffic || By claiming that free transit decreases bus ridership || By suggesting that cities should raise transit fares >> Text 2 found ridership rose but car trips barely changed, since drivers cared more about time and convenience.
CT: Based on Text 2, most of the new bus riders were people who || had previously walked or biked. || had previously driven cars. || had never traveled in the city. || stopped using transit after a year. >> "Most new riders had previously walked or biked."
CT: Which choice best describes the relationship between the two texts? || Text 2 presents evidence that complicates the prediction made in Text 1. || Text 2 provides evidence that fully confirms Text 1. || Text 2 describes an unrelated transportation policy. || Text 2 restates Text 1's argument without adding evidence. >> The prediction of reduced traffic was not borne out.

P: Some nutritionists recommend that people eat many small meals throughout the day instead of three larger ones, arguing that frequent eating keeps metabolism running faster and helps with weight control.
P2: Metabolism does rise slightly after every meal as the body digests food, but the total increase depends on how much is eaten, not how many times. In controlled studies where participants ate the same total calories in either three meals or six smaller ones, their total energy use and weight change were essentially the same.
CT:: || By arguing that meal frequency does not change total energy use when total calories are the same || By agreeing that six small meals speed up metabolism more than three meals || By claiming that eating fewer meals causes weight gain || By suggesting that digestion does not affect metabolism >> Text 2 says energy use depends on total food, and studies found no difference.
CT: The author of Text 2 would most likely agree with Text 1's claim that || metabolism increases after eating. || small frequent meals lead to greater weight loss. || three meals a day slow metabolism permanently. || meal timing matters more than total calories. >> Text 2 acknowledges "metabolism does rise slightly after every meal."
CT: Which choice best describes how the author of Text 2 responds to the reasoning in Text 1? || The author accepts part of the reasoning but rejects the conclusion drawn from it. || The author rejects every part of the reasoning. || The author accepts the conclusion but offers a different reason. || The author ignores the reasoning and discusses a different topic. >> Text 2 grants the metabolic rise but denies that meal frequency changes the total.

P: Historians have often portrayed a certain nineteenth-century inventor as a lone genius who developed the electric light bulb through sheer persistence, testing thousands of materials by himself.
P2: Laboratory records show that the inventor worked with a large team of machinists, chemists, and assistants who carried out many of the experiments. Moreover, several earlier inventors had already produced working bulbs, though none lasted long. The inventor's achievement, some historians now argue, was organizing collaborative research and improving existing designs, not working alone.
CT:: || By arguing that the inventor relied heavily on a team and built on earlier inventors' work rather than working alone || By agreeing that the inventor tested every material by himself || By claiming that the inventor had no role in developing the light bulb || By suggesting that earlier bulbs lasted longer than the inventor's >> Text 2 cites laboratory records of a team and earlier working bulbs.
CT: Based on the texts, both authors would most likely agree that the inventor || played a role in the development of a practical light bulb. || invented the first light bulb ever made. || worked without any assistants. || failed to improve on earlier designs. >> Text 1 credits him; Text 2 credits his improvements and organization.
CT: The author of Text 2 mentions "several earlier inventors" mainly to || show that the basic idea of the bulb did not originate with this inventor alone. || prove that the inventor stole their designs. || argue that earlier bulbs were superior. || explain why the inventor hired assistants. >> Earlier working bulbs challenge the lone-genius story.

P: Supporters of homework-free policies in elementary schools argue that homework adds stress without improving learning, and that children benefit more from play and family time after school.
P2: Research on elementary homework shows mixed results. Short, well-designed assignments, such as reading with a parent for fifteen minutes, have been linked to gains in reading. Long worksheets that repeat class material show little benefit and can cause frustration. The question, according to many researchers, is not whether to assign homework but what kind to assign.
CT:: || By suggesting that the value of homework depends on the type of assignment rather than rejecting all homework || By agreeing that all homework should be eliminated || By claiming that long worksheets are the most effective homework || By arguing that play has no benefit for children >> Text 2 says short reading assignments help, while repetitive worksheets do not.
CT: Based on Text 2, which kind of homework is most likely to benefit elementary students? || Brief reading time with a parent || Long worksheets repeating class material || No assignments of any kind || Homework assigned only on weekends >> Reading with a parent "has been linked to gains in reading."
CT: The author of Text 2 would most likely agree with the supporters in Text 1 that || some homework can cause frustration without improving learning. || all homework should be banned. || play is harmful to children. || family time should be replaced by homework. >> Text 2 says long worksheets "can cause frustration."

P: Wildlife managers in some regions have argued that removing predators such as wolves will increase deer populations and therefore improve hunting opportunities.
P2: In one region where wolves were removed, deer numbers did rise, but within a decade the deer had overgrazed young trees and shrubs. As food became scarce, deer grew thinner, disease spread, and populations crashed. Ecologists concluded that predators can help keep prey populations within limits that their habitat can support.
CT:: || By arguing that removing predators may increase deer at first but can lead to overgrazing and population crashes || By agreeing that removing predators permanently improves deer populations || By claiming that wolves cause deer to overgraze || By suggesting that deer populations never change >> Text 2 describes an initial rise followed by overgrazing and collapse.
CT: Based on Text 2, the deer population crashed mainly because || deer ate so much vegetation that food became scarce. || wolves returned to the region. || hunters removed too many deer. || the climate became warmer. >> Overgrazing led to scarce food, thinner deer, and disease.
CT: Which choice best describes the relationship between the two texts? || Text 2 describes long-term consequences that challenge the reasoning in Text 1. || Text 2 supports the reasoning in Text 1 with additional evidence. || Text 2 discusses predators in an unrelated habitat. || Text 2 summarizes Text 1. >> Text 1 expects benefits; Text 2 shows eventual harm.

P: Some critics argue that audiobooks are a lesser form of reading, claiming that listeners absorb less of a book's meaning than people who read print.
P2: In one study, participants who listened to a short story and participants who read it scored similarly on questions about plot and character. Listeners actually recalled more details about characters' emotions, which the researchers attributed to narrators' vocal expression. The researchers noted, however, that readers found it easier to reread difficult passages.
CT:: || By arguing that evidence shows listeners understand stories about as well as readers do, though each format has some advantages || By agreeing that listeners understand far less than readers || By claiming that audiobooks should replace printed books || By suggesting that narrators make stories harder to follow >> Text 2 reports similar comprehension, with advantages for each format.
CT: Based on Text 2, listeners recalled characters' emotions better most likely because || narrators conveyed emotion through their voices. || listeners reread difficult passages. || the story was shorter for listeners. || listeners took notes while listening. >> The researchers "attributed" it to "narrators' vocal expression."
CT: The author of Text 2 mentions that readers found it easier to reread difficult passages mainly to || acknowledge an advantage of print reading. || show that audiobooks are superior in every way. || criticize the study's design. || explain why the story was chosen. >> It presents a balancing point in favor of print.

P: Many parents believe that playing classical music for infants makes them smarter, an idea popularized decades ago by reports of a so-called music effect.
P2: The original study behind the claim tested college students, not infants, and found only a small, temporary improvement on one spatial reasoning task after listening to a sonata. Later attempts to repeat the result often failed. No research has shown that simply playing classical music for babies raises their intelligence.
CT:: || By pointing out that the evidence behind the belief is weak and does not concern infants || By agreeing that classical music raises infants' intelligence || By claiming that music harms infants' development || By arguing that college students are smarter than infants >> Text 2 notes the study involved adults, showed a small temporary effect, and often failed to replicate.
CT: Based on Text 2, which statement about the original study is accurate? || It found a small, temporary effect on one task in college students. || It tested hundreds of infants over several years. || It proved a permanent increase in intelligence. || It found that sonatas lower test scores. >> Text 2 describes a "small, temporary improvement on one spatial reasoning task."
CT: The author of Text 2 mentions that later attempts often failed mainly to || further undermine confidence in the original result. || show that the original study was fraudulent. || suggest that infants dislike classical music. || argue that more sonatas should be played. >> Failed replications weaken the claim.

P: Advocates of standing desks claim that working while standing burns far more calories than sitting and can help office workers lose weight.
P2: Standing does burn slightly more energy than sitting, but measurements suggest the difference is modest, roughly the equivalent of a small snack over an entire workday. Standing desks may reduce back discomfort for some workers, but they are unlikely on their own to produce significant weight loss.
CT:: || By acknowledging that standing burns somewhat more calories while arguing that the difference is too small to cause much weight loss || By agreeing that standing desks lead to major weight loss || By claiming that sitting burns more calories than standing || By arguing that standing desks always cause back pain >> Text 2 grants a small increase but disputes significant weight loss.
CT: Based on Text 2, a possible benefit of standing desks is that they || may reduce back discomfort for some workers. || cause substantial weight loss. || replace the need for exercise. || make workers more productive in every case. >> "May reduce back discomfort for some workers."
CT: Which choice best describes a difference in how the two texts view standing desks? || Text 1 emphasizes calorie burning, while Text 2 suggests that effect is modest. || Text 1 focuses on back pain, while Text 2 focuses on productivity. || Text 1 opposes standing desks, while Text 2 supports them. || Text 1 relies on measurements, while Text 2 relies on opinions. >> The texts disagree about the size of the calorie effect.

P: Some economists argue that raising taxes on sugary drinks will reduce consumption, because higher prices discourage buyers.
P2: After one city added a tax on sugary drinks, sales within the city fell sharply. However, sales at stores just outside the city limits rose, as some shoppers crossed the border to buy cheaper drinks. Overall consumption among residents dropped, but by less than the in-city sales figures alone suggested.
CT:: || By agreeing that the tax reduced consumption while noting that the effect was smaller than in-city sales suggested || By claiming that the tax increased consumption among residents || By arguing that prices have no effect on buyers || By suggesting that the city should remove the tax immediately >> Text 2 shows reduced consumption, partly offset by cross-border shopping.
CT: Based on Text 2, in-city sales figures alone would most likely have || exaggerated how much residents' consumption fell. || underestimated how much residents' consumption fell. || shown that sales rose. || matched overall consumption exactly. >> Some purchases shifted outside the city.
CT: The author of Text 2 mentions stores "just outside the city limits" mainly to || explain why the drop in in-city sales overstated the tax's effect. || show that the tax applied to the entire region. || argue that stores outside the city should be closed. || describe where the city's sugary drinks are made. >> Cross-border purchases partly offset the decline.

P: Many people assume that the Middle Ages were a period in which scientific thinking came to a halt in Europe.
P2: Historians of science point out that medieval scholars developed new theories of motion, studied optics, and built mechanical clocks. Universities founded during the period became centers for debating natural philosophy. While some ancient texts were lost in Europe, others were preserved, translated, and expanded upon, often through contact with scholars in the Islamic world.
CT:: || By presenting examples of scientific and scholarly activity during the period to challenge that assumption || By agreeing that scientific thinking stopped entirely || By claiming that universities were closed during the Middle Ages || By arguing that no ancient texts survived >> Text 2 lists theories of motion, optics, clocks, and universities.
CT: Based on Text 2, contact with scholars in the Islamic world contributed to || the preservation and expansion of ancient texts. || the loss of all ancient knowledge. || the closing of European universities. || the invention of the printing press. >> Texts were "preserved, translated, and expanded upon" through that contact.
CT: The author of Text 2 acknowledges that || some ancient texts were lost in Europe during the period. || no scientific progress occurred. || medieval clocks did not work. || universities discouraged debate. >> "While some ancient texts were lost in Europe..."

P: Proponents of year-round schooling argue that the long summer break causes students to forget much of what they learned, forcing teachers to spend weeks reviewing each fall.
P2: Studies of year-round calendars, which spread the same number of school days across shorter breaks, have found only small differences in overall achievement compared with traditional calendars. Some evidence suggests that summer learning loss is largest among students from low-income families, who may have fewer educational opportunities during the break.
CT:: || By suggesting that year-round calendars show only small overall benefits, though summer loss may affect some students more than others || By agreeing that year-round schooling greatly improves achievement for all students || By claiming that students forget nothing over the summer || By arguing that schools should add more days to the calendar >> Text 2 finds small differences but notes uneven summer loss.
CT: Based on Text 2, a year-round calendar differs from a traditional calendar mainly in || how school days are distributed across the year. || the total number of school days. || the subjects that are taught. || the age at which students begin school. >> It "spread[s] the same number of school days across shorter breaks."
CT: The author of Text 2 would most likely suggest that efforts to reduce summer learning loss || could focus especially on students with fewer opportunities during the break. || are unnecessary for all students. || should begin in high school. || should eliminate summer entirely. >> Loss is "largest among students from low-income families."

P: Some gardeners insist that talking to plants helps them grow, pointing to their own flourishing gardens as proof.
P2: A few experiments have reported that plants exposed to recorded speech grew slightly faster, but these studies were small and often poorly controlled. Gardeners who talk to their plants may also water, prune, and check them more often, and that extra attention could explain healthier growth.
CT:: || By suggesting that other forms of care provided by these gardeners might explain their plants' growth || By agreeing that speech is the main reason plants grow || By claiming that talking to plants harms them || By arguing that gardeners should stop watering their plants >> Text 2 points to extra watering and pruning as an alternative explanation.
CT: Based on Text 2, the experiments reporting faster growth are weak evidence because they || were small and often poorly controlled. || used real plants instead of models. || lasted too long. || were conducted by gardeners. >> "These studies were small and often poorly controlled."
CT: Which choice best describes the relationship between the texts? || Text 2 offers an alternative explanation for the evidence cited in Text 1. || Text 2 provides new evidence supporting Text 1. || Text 2 describes an unrelated gardening method. || Text 2 agrees completely with Text 1. >> Healthy gardens may result from extra care, not talking.

P: Museum curators have traditionally argued that fragile artifacts should never be handled by visitors, since even careful touching can cause gradual damage.
P2: Some museums now use high-quality replicas, created from detailed scans, that visitors are encouraged to touch. Surveys suggest that handling replicas helps visitors understand an object's weight and texture, and the originals remain safely behind glass. Curators who once opposed hands-on displays have found that replicas address their main concern.
CT:: || By agreeing that originals should be protected while describing a way to let visitors handle objects without risking damage || By arguing that visitors should handle all original artifacts || By claiming that touching artifacts never causes damage || By suggesting that museums should remove all displays >> Replicas let people touch while originals stay protected.
CT: Based on Text 2, handling replicas benefits visitors by helping them || understand objects' weight and texture. || identify which objects are fake. || repair damaged artifacts. || avoid visiting museums. >> Surveys suggest replicas help with "weight and texture."
CT: The curators described in Text 2 would most likely say that replicas || address the concern expressed in Text 1. || cause more damage than originals. || should never be touched. || are less accurate than photographs. >> Replicas "address their main concern."

P: Some urban planners argue that building more highway lanes is the best way to relieve traffic congestion.
P2: Studies of many cities have found that adding highway capacity often leads to more driving. When roads become less crowded, people take trips they previously avoided, choose to live farther away, or shift from transit to cars. Within a few years, traffic frequently returns to its previous levels, a pattern known as induced demand.
CT:: || By arguing that added lanes often encourage more driving, so congestion tends to return || By agreeing that new lanes permanently solve congestion || By claiming that fewer people drive when highways expand || By suggesting that cities should build no roads at all >> Text 2 describes induced demand.
CT: Based on Text 2, which situation is an example of induced demand? || After a highway is widened, more people decide to commute by car from distant suburbs. || After a highway is widened, fewer people drive. || After a bus line is added, traffic decreases. || After a highway closes, people stop traveling. >> Less crowded roads encourage new driving trips.
CT: Which choice best describes how Text 2 responds to Text 1? || It presents evidence suggesting that the proposed solution may not work in the long run. || It supports the proposed solution with new data. || It proposes adding even more lanes than Text 1 suggests. || It agrees but adds that roads should be tolled. >> Traffic "returns to its previous levels."

P: Many writers claim that people have become worse at paying attention because of smartphones, citing a widely repeated claim that human attention spans are now shorter than a goldfish's.
P2: Researchers who have searched for the source of the goldfish comparison have been unable to find any study supporting it. Attention also varies greatly by task; people who struggle to focus on a dull lecture may concentrate for hours on a game or a novel. Whether smartphones affect attention is a legitimate question, but the goldfish claim is not evidence.
CT:: || By arguing that the goldfish comparison is unsupported, even though the question about smartphones deserves study || By agreeing that attention spans are shorter than a goldfish's || By claiming that smartphones improve attention || By suggesting that people cannot concentrate on novels >> Text 2 rejects the statistic but keeps the question open.
CT: Based on Text 2, the example of people concentrating for hours on a game suggests that || attention depends on the task, not a single fixed span. || games damage attention. || lectures are more engaging than games. || people cannot focus for long periods. >> "Attention also varies greatly by task."
CT: The author of Text 2 would most likely agree with Text 1 that || the effect of smartphones on attention is worth investigating. || attention spans are shorter than a goldfish's. || the goldfish statistic comes from a reliable study. || people can no longer read novels. >> "Whether smartphones affect attention is a legitimate question."

P: Some architects argue that tall glass skyscrapers are energy-efficient because they let in abundant daylight, reducing the need for electric lighting.
P2: Glass walls do admit daylight, but they also let heat escape in winter and absorb heat in summer, often requiring powerful heating and cooling systems. Studies of office towers have found that fully glazed buildings frequently use more total energy than buildings with a mix of windows and insulated walls, even after lighting savings are counted.
CT:: || By arguing that lighting savings are often outweighed by increased heating and cooling needs || By agreeing that glass skyscrapers use less total energy than other buildings || By claiming that glass blocks daylight || By suggesting that buildings should have no windows >> Heat loss and gain can exceed lighting savings.
CT: Based on Text 2, buildings with a mix of windows and insulated walls tend to || use less total energy than fully glazed buildings. || require no heating or cooling. || receive no daylight. || use more lighting energy than glass buildings and more total energy. >> Fully glazed buildings "frequently use more total energy."
CT: The author of Text 2 would most likely agree with the architects in Text 1 that glass walls || let in daylight. || prevent heat from escaping. || keep buildings cool in summer. || reduce total energy use. >> "Glass walls do admit daylight."

P: Many coaches have long believed that athletes should stretch before exercise to prevent injuries.
P2: Several large studies of runners and military recruits found that stretching before exercise did little to reduce injury rates. Some research suggests that a dynamic warm-up, such as light jogging and movement drills, prepares muscles more effectively than holding static stretches. Stretching may still improve flexibility over time when done regularly.
CT:: || By presenting evidence that pre-exercise stretching does little to prevent injuries and suggesting a different warm-up || By agreeing that static stretching prevents most injuries || By claiming that warming up increases injuries || By arguing that flexibility has no value >> Studies found little reduction in injuries; dynamic warm-ups may work better.
CT: Based on Text 2, which statement about stretching is most accurate? || It may improve flexibility over time, even if it does little to prevent injuries before exercise. || It has no effects of any kind. || It is more effective than any warm-up for preventing injuries. || It should be done only after injuries occur. >> Text 2 grants a flexibility benefit.
CT: Which choice best describes the relationship between the texts? || Text 2 challenges a long-held belief described in Text 1. || Text 2 confirms the belief described in Text 1. || Text 2 describes the history of coaching. || Text 2 and Text 1 discuss unrelated sports. >> Evidence contradicts the traditional practice.

P: Some historians have argued that a small ancient kingdom collapsed suddenly because of a single devastating invasion.
P2: Excavations at the kingdom's cities reveal a more gradual process. Layers of soil show declining harvests over several decades, and records mention repeated droughts and rising grain prices. The invasion occurred, but it struck a kingdom already weakened by years of hardship.
CT:: || By arguing that the kingdom was already weakened by long-term problems before the invasion occurred || By claiming that no invasion ever took place || By agreeing that the invasion alone caused the collapse || By suggesting that the kingdom grew stronger before the invasion >> Text 2 describes gradual decline plus the invasion.
CT: Based on Text 2, which evidence suggests a gradual decline? || Soil layers showing declining harvests over decades || A single record of the invasion || Weapons found in one city || A description of the kingdom's founding >> "Declining harvests over several decades."
CT: The author of Text 2 would most likely agree with the historians in Text 1 that || an invasion occurred. || the collapse happened in a single day. || droughts were unimportant. || grain prices fell. >> "The invasion occurred."

P: Some linguists predict that the spread of global languages such as English will cause many local languages to disappear within the next century.
P2: Language loss is a serious concern, and many small languages are indeed threatened. Yet some communities have revived languages that had few remaining speakers by creating immersion schools, recording elders, and using the languages in media and apps. These efforts show that decline is not inevitable when communities commit resources to preservation.
CT:: || By agreeing that many languages are threatened while arguing that community efforts can reverse decline || By claiming that no languages are threatened || By arguing that English will soon disappear || By suggesting that recording elders speeds language loss >> Text 2 accepts the threat but describes successful revivals.
CT: Based on Text 2, which approach has helped revive threatened languages? || Creating immersion schools || Banning the use of global languages || Avoiding the use of apps || Teaching only written grammar >> Immersion schools are one listed method.
CT: Which choice best describes a difference between the texts? || Text 1 presents language loss as likely, while Text 2 emphasizes that loss can sometimes be prevented. || Text 1 focuses on English, while Text 2 focuses on mathematics. || Text 1 argues languages are growing, while Text 2 argues they are shrinking. || Text 1 relies on community examples, while Text 2 relies on predictions. >> Prediction versus evidence of revival.

P: Many people believe that lightning never strikes the same place twice.
P2: Tall structures and high points in a landscape are struck repeatedly. Some skyscrapers are hit dozens of times each year, and lightning rods are designed precisely because tall objects attract strikes again and again. The saying may be meant as encouragement, but it is not accurate.
CT:: || By pointing out that lightning frequently strikes the same tall objects repeatedly || By agreeing that lightning never strikes one place twice || By claiming that skyscrapers are never struck by lightning || By arguing that lightning rods attract only one strike >> Skyscrapers are hit many times.
CT: The author of Text 2 mentions skyscrapers primarily to || give an example that contradicts the belief in Text 1. || explain how lightning forms. || describe the history of lightning rods. || argue that skyscrapers are unsafe. >> Skyscrapers are struck "dozens of times each year."
CT: Based on Text 2, the saying about lightning is best described as || inaccurate, though possibly meant as encouragement. || scientifically proven. || a description of skyscrapers. || a rule for designing lightning rods. >> "May be meant as encouragement, but it is not accurate."

P: Advocates of organic farming argue that it is better for the environment in every respect than conventional farming.
P2: Organic farms often support greater biodiversity and use fewer synthetic pesticides. However, they typically produce smaller harvests per acre, which means more land may be needed to grow the same amount of food. Whether organic farming is better overall can depend on how much land is available and which environmental impacts are measured.
CT:: || By acknowledging environmental benefits of organic farming while noting drawbacks that make its overall impact more complicated || By agreeing that organic farming is better in every respect || By claiming that organic farms use more synthetic pesticides || By arguing that biodiversity does not matter >> Text 2 cites benefits and lower yields.
CT: Based on Text 2, a drawback of organic farming is that it || may require more land to produce the same amount of food. || reduces biodiversity. || uses more synthetic pesticides. || cannot grow vegetables. >> Smaller harvests per acre mean more land may be needed.
CT: The author of Text 2 would most likely object to the word "every" in Text 1 because || organic farming has some environmental disadvantages as well as advantages. || organic farming has no environmental benefits. || conventional farming is always better. || the author did not study organic farming. >> Lower yields show it is not better in every respect.

P: Some teachers believe that students should memorize multiplication tables, arguing that quick recall frees attention for more complex math.
P2: Other educators worry that memorization without understanding leaves students unable to apply facts flexibly. They favor teaching strategies such as breaking problems into parts, so that students understand why facts are true. Many researchers conclude that the approaches work best together: understanding makes facts meaningful, and fluent recall makes complex work easier.
CT:: || By suggesting that memorization is most useful when combined with understanding || By claiming that memorization harms all students || By agreeing that understanding is unnecessary || By arguing that multiplication should not be taught >> Text 2 concludes the two approaches work best together.
CT: Based on Text 2, the educators who worry about memorization are concerned that students || may not be able to use facts flexibly without understanding them. || will memorize too quickly. || will refuse to learn multiplication. || cannot break problems into parts. >> Memorization without understanding limits application.
CT: The researchers described in Text 2 would most likely agree with the teachers in Text 1 that || fluent recall of facts can make complex work easier. || understanding facts is unimportant. || strategies should replace memorization. || multiplication tables are too difficult. >> "Fluent recall makes complex work easier."

P: A popular idea holds that people are either "left-brained," meaning logical and analytical, or "right-brained," meaning creative and intuitive.
P2: Brain imaging studies show that both hemispheres are active during nearly all complex tasks, including math and art. Some functions, such as aspects of language, rely more on one side, but researchers have found no evidence that individuals consistently use one hemisphere more than the other.
CT:: || By presenting evidence that people do not rely predominantly on one side of the brain || By agreeing that people are either left-brained or right-brained || By claiming that the brain has only one hemisphere || By arguing that art uses no brain activity >> Imaging shows both hemispheres active; no evidence of dominance.
CT: The author of Text 2 acknowledges that || some functions rely more heavily on one hemisphere. || individuals consistently use one hemisphere more. || art activates only the right hemisphere. || math activates only the left hemisphere. >> "Aspects of language rely more on one side."
CT: Which choice best describes the relationship between the texts? || Text 2 uses research to reject the popular idea in Text 1. || Text 2 expands on the popular idea in Text 1. || Text 2 describes a different theory of creativity. || Text 2 argues that the idea in Text 1 is proven. >> Text 2 finds no evidence for hemispheric types.

P: Some critics argue that video games are a waste of time with no educational value.
P2: Research on certain action games has found that players can improve in tracking multiple moving objects and switching attention quickly. Puzzle and strategy games may encourage planning and problem solving. The benefits depend heavily on the type of game, and researchers caution that many popular games have not been shown to teach specific skills.
CT:: || By noting that some types of games may develop certain skills, while cautioning that benefits vary by game || By agreeing that all video games are a waste of time || By claiming that every video game teaches valuable skills || By arguing that attention skills cannot be improved >> Text 2 finds benefits for some games but not all.
CT: Based on Text 2, action games have been linked to improvements in || tracking multiple moving objects. || memorizing historical dates. || learning foreign languages. || spelling. >> Players "improve in tracking multiple moving objects."
CT: The author of Text 2 would most likely say that the critics' claim is || too broad, because some games may have educational value. || fully supported by research. || correct about puzzle games only. || irrelevant to research on games. >> Some games show benefits.

P: Some city officials argue that planting trees along streets is mainly a way to make neighborhoods more attractive.
P2: Street trees provide measurable benefits beyond appearance. Studies have linked tree-lined streets to cooler summer temperatures, reduced stormwater runoff, and in some neighborhoods, lower energy costs for nearby homes. Researchers suggest that trees should be treated as public infrastructure, like sidewalks and drainage systems.
CT:: || By arguing that street trees offer practical benefits beyond making neighborhoods attractive || By agreeing that trees serve only a decorative purpose || By claiming that trees increase energy costs || By suggesting that sidewalks are unnecessary >> Cooler streets, less runoff, lower energy costs.
CT: The researchers in Text 2 compare trees to sidewalks and drainage systems mainly to || suggest that trees provide essential public services. || argue that trees should be removed. || describe how trees are planted. || explain why sidewalks crack. >> Treating trees "as public infrastructure."
CT: Based on the texts, both authors would most likely agree that street trees || can make neighborhoods more attractive. || increase stormwater runoff. || raise summer temperatures. || have no measurable effects. >> Text 2 says benefits go "beyond appearance," implying appearance is one benefit.

P: Many people believe that bats are blind.
P2: All bat species can see, and some large fruit bats have excellent vision suited to finding food at dusk. Many smaller bats rely heavily on echolocation, emitting sounds and listening to echoes to navigate and hunt in darkness, which may be why people assume bats cannot see.
CT:: || By stating that bats can see and suggesting that reliance on echolocation may explain the mistaken belief || By agreeing that most bats are blind || By claiming that no bats use echolocation || By arguing that bats hunt only during the day >> Text 2 says all bats can see and explains the misconception.
CT: Based on Text 2, large fruit bats are notable because they || have excellent vision. || rely entirely on echolocation. || cannot see at all. || hunt insects underwater. >> "Some large fruit bats have excellent vision."
CT: Which choice best describes how Text 2 responds to the belief in Text 1? || It corrects the belief and offers a possible reason people hold it. || It supports the belief with new evidence. || It ignores the belief. || It agrees but adds that bats cannot hear. >> Correction plus explanation via echolocation.

P: Some business leaders argue that open-plan offices, without walls or private offices, encourage collaboration by making it easy for employees to talk.
P2: A study that tracked employees before and after two companies switched to open-plan offices found that face-to-face interaction actually decreased by about seventy percent, while email and messaging increased. Researchers suggest that employees, lacking privacy, may have used headphones and digital messages to avoid being overheard or interrupted.
CT:: || By presenting evidence that open-plan offices may reduce face-to-face interaction rather than increase it || By agreeing that open offices greatly increase conversation || By claiming that email decreased in open offices || By arguing that private offices prevent all collaboration >> Face-to-face interaction dropped sharply.
CT: Based on Text 2, employees in open-plan offices most likely increased their use of email and messaging because they || wanted to avoid being overheard or interrupted. || were required to stop talking. || had more private offices. || could not use headphones. >> Lack of privacy led to digital communication.
CT: Which choice best describes the relationship between the texts? || Text 2 reports a result contrary to the expectation in Text 1. || Text 2 confirms the expectation in Text 1. || Text 2 describes the architecture of office buildings. || Text 2 summarizes Text 1 without adding evidence. >> Collaboration was expected to rise but face-to-face contact fell.
"""
