"""Cross-text units, batch 2 (format in passage_data1.py). Original texts; studies are illustrative."""

UNITS = """
P: Some conservation groups argue that zoos mainly serve entertainment and do little for wild animal populations.
P2: Many accredited zoos run breeding programs for endangered species, and several species that had vanished from the wild have been reintroduced from zoo-bred populations. Zoos also fund field research and habitat protection. Critics are right that not all zoos meet high standards, but well-run zoos can make meaningful contributions to conservation.
CT:: || By arguing that well-run zoos contribute to conservation through breeding, research, and habitat protection, while conceding that some zoos fall short || By agreeing that zoos do nothing for wild populations || By claiming that all zoos meet high standards || By suggesting that endangered species should never be bred in captivity >> Text 2 cites breeding and funding while granting that not all zoos are good.
CT: Based on Text 2, which statement about some endangered species is accurate? || They have been reintroduced to the wild from zoo-bred populations. || They can survive only in zoos. || They were never found in the wild. || They are harmed by field research. >> Several species "have been reintroduced from zoo-bred populations."
CT: The author of Text 2 would most likely agree with the conservation groups in Text 1 that || some zoos do not meet high standards. || zoos serve only as entertainment. || breeding programs have failed. || habitat protection is unnecessary. >> "Critics are right that not all zoos meet high standards."

P: Some technology writers predict that printed books will soon disappear, replaced entirely by e-books.
P2: E-book sales grew rapidly for several years after e-readers were introduced, but they later leveled off, and print books continue to account for a large share of sales. Surveys suggest that many readers value the physical experience of print, while others prefer e-books for travel. The two formats appear likely to coexist.
CT:: || By arguing that sales trends and reader preferences suggest print and e-books will continue to coexist || By agreeing that print books will disappear soon || By claiming that e-book sales have never grown || By arguing that e-books are unpopular with travelers >> E-book growth leveled off, and print remains popular.
CT: Based on Text 2, some readers prefer e-books because they || are convenient for travel. || offer a physical reading experience. || cost more than print books. || cannot be read on e-readers. >> "Others prefer e-books for travel."
CT: Which choice best describes the relationship between the texts? || Text 2 presents evidence against the prediction in Text 1. || Text 2 supports the prediction in Text 1. || Text 2 discusses the history of printing. || Text 2 agrees that print sales have ended. >> Sales leveled off and print endures.

P: Many people believe that sugar makes children hyperactive, and parents often report that their children become wild after eating sweets.
P2: In controlled experiments, children were given either sugar or a sugar-free substitute without anyone knowing which. Researchers found no difference in behavior. In one study, parents who were told their child had eaten sugar rated the child as more hyperactive, even when the child had received the substitute, suggesting that expectations may shape what parents notice.
CT:: || By arguing that controlled studies found no effect and that parents' expectations may explain their observations || By agreeing that sugar causes hyperactivity || By claiming that sugar substitutes cause hyperactivity || By suggesting that parents cannot observe their children >> No behavioral difference; expectation influences ratings.
CT: Based on Text 2, parents who were told their child had eaten sugar || rated the child as more hyperactive even when no sugar had been eaten. || rated the child as calmer. || refused to rate their child's behavior. || gave their child more sugar. >> Expectation led to higher ratings.
CT: The author of Text 2 would most likely say that the parents' reports described in Text 1 || may reflect their expectations rather than an effect of sugar. || prove that sugar causes hyperactivity. || are based on controlled experiments. || show that sugar calms children. >> Expectations may shape what parents notice.

P: Some farmers argue that bees are the only pollinators that matter for crops.
P2: Honeybees and wild bees are important, but studies of crop fields around the world show that flies, beetles, moths, and butterflies also pollinate many crops. In some fields, these insects account for a substantial share of flower visits. Protecting a variety of pollinators may make crop production more resilient if bee populations decline.
CT:: || By acknowledging bees' importance while arguing that many other insects also contribute to pollination || By agreeing that only bees pollinate crops || By claiming that bees are unimportant for crops || By suggesting that beetles damage all crops >> Flies, beetles, moths, and butterflies also pollinate.
CT: Based on Text 2, protecting a variety of pollinators could be valuable because || crops would depend less on bees alone if bee numbers fell. || other insects produce honey. || bees would stop visiting flowers. || moths are easier to raise than bees. >> Diversity makes production "more resilient."
CT: The author of Text 2 would most likely agree with the farmers in Text 1 that || bees are important pollinators. || beetles are the most important pollinators. || only bees visit crop flowers. || pollination is unimportant for crops. >> "Honeybees and wild bees are important."

P: Some critics claim that remote learning is always less effective than in-person instruction.
P2: Results from remote courses vary widely. Studies suggest that well-designed online courses with frequent interaction, clear structure, and regular feedback can produce learning outcomes similar to in-person courses. Poorly designed courses, and students without reliable internet or quiet study spaces, often fare worse.
CT:: || By arguing that remote learning's effectiveness depends on course design and students' circumstances || By agreeing that remote learning is always less effective || By claiming that online courses are always more effective || By suggesting that feedback harms learning >> Outcomes vary by design and student conditions.
CT: Based on Text 2, which students are most likely to struggle in remote courses? || Students without reliable internet or quiet places to study || Students who receive regular feedback || Students in well-structured courses || Students who interact frequently with instructors >> Those lacking internet or quiet space "often fare worse."
CT: The author of Text 2 would most likely object to the word "always" in Text 1 because || some remote courses produce outcomes similar to in-person courses. || all remote courses are ineffective. || in-person courses never work. || studies of remote learning do not exist. >> Well-designed courses can match in-person results.

P: Some historians have credited a single general's brilliant strategy for an army's victory in a famous battle.
P2: Letters and supply records from the campaign reveal that the victorious army had far better access to food and ammunition than its opponent, whose supply lines had been disrupted by weeks of heavy rain. The general's decisions mattered, but historians who emphasize only strategy may overlook the practical conditions that made victory possible.
CT:: || By arguing that supply advantages and weather also contributed significantly to the victory || By claiming that the general made no decisions during the battle || By agreeing that strategy alone determined the outcome || By suggesting that the battle never took place >> Supplies and disrupted enemy lines mattered too.
CT: Based on Text 2, the opposing army's supply problems were caused mainly by || weeks of heavy rain that disrupted its supply lines. || the general's secret attack on its camp. || a shortage of soldiers. || a lack of ammunition factories. >> Supply lines "had been disrupted by weeks of heavy rain."
CT: The author of Text 2 would most likely agree with the historians in Text 1 that || the general's decisions influenced the battle. || supplies were irrelevant to the outcome. || rain helped the victorious army's opponent. || the general lost the battle. >> "The general's decisions mattered."

P: Some public health officials argue that warning labels on cigarette packages are an effective way to reduce smoking.
P2: Studies comparing countries suggest that large graphic warning images are associated with more attempts to quit than small text-only warnings. However, labels appear to work best as part of a broader strategy that includes taxes, smoking bans in public places, and support programs for people trying to quit.
CT:: || By agreeing that labels, especially graphic ones, can help, while suggesting they are most effective combined with other measures || By claiming that warning labels increase smoking || By arguing that text-only warnings work better than images || By suggesting that taxes discourage people from quitting >> Graphic warnings help most within a broader strategy.
CT: Based on Text 2, which type of warning label is associated with more attempts to quit? || Large graphic images || Small text-only warnings || Labels printed on the inside of packages || Labels without any images or text >> Graphic images are linked to more quit attempts.
CT: Which choice best describes how Text 2 relates to Text 1? || It supports the claim in Text 1 while adding an important qualification. || It rejects the claim in Text 1 entirely. || It discusses an unrelated health issue. || It restates the claim in Text 1 without evidence. >> Labels help, but best as part of broader efforts.

P: Many runners believe that expensive, highly cushioned running shoes prevent injuries.
P2: Studies of runners wearing different kinds of shoes have not consistently found that cushioning reduces injury rates. Some evidence suggests that choosing a shoe that feels comfortable to the individual runner may matter more than the amount of cushioning or the price.
CT:: || By arguing that evidence does not clearly show that cushioning prevents injuries and that comfort may matter more || By agreeing that expensive shoes always prevent injuries || By claiming that cushioning causes injuries || By suggesting that runners should run barefoot >> Studies are inconsistent; comfort may matter most.
CT: Based on Text 2, a runner trying to reduce injury risk would most likely be advised to || choose shoes that feel comfortable to them. || buy the most expensive shoes available. || select the most cushioned shoes. || avoid wearing shoes. >> Comfort "may matter more."
CT: The author of Text 2 mentions price mainly to || suggest that a shoe's cost is not a reliable guide to injury prevention. || argue that cheap shoes cause injuries. || explain why cushioned shoes are expensive. || recommend buying shoes on sale. >> Comfort may matter more "than ... the price."

P: Some urban designers argue that pedestrian-only shopping streets always attract more customers than streets open to cars.
P2: Many pedestrian streets have thrived, especially in dense city centers with heavy foot traffic. But in some smaller towns, closing main streets to cars reduced visits, as shoppers who arrived by car found parking too distant. Several of these towns later reopened their streets to traffic. Success appears to depend on local conditions.
CT:: || By arguing that pedestrian streets succeed in some places but not others, depending on local conditions || By agreeing that pedestrian streets always attract more customers || By claiming that no pedestrian street has ever succeeded || By suggesting that all towns should close streets to cars >> Dense centers thrive; some small towns struggled.
CT: Based on Text 2, some small towns reopened streets to traffic most likely because || closing them to cars had reduced shopper visits. || pedestrians demanded more parking lots. || foot traffic increased too much. || the streets were too narrow for walking. >> Visits declined when parking was distant.
CT: The author of Text 2 would most likely object to the word "always" in Text 1 because || pedestrian streets have not succeeded in every setting. || pedestrian streets never attract customers. || all towns have heavy foot traffic. || cars are banned in every city center. >> Some towns saw fewer visits.

P: Some scientists have argued that dinosaurs were wiped out slowly by gradual climate change over millions of years.
P2: A layer of rock found around the world marks the end of the age of dinosaurs. It contains unusually high levels of iridium, an element rare on Earth but common in asteroids, and a large impact crater of the right age has been identified. Many scientists conclude that an asteroid impact caused a rapid mass extinction, though some argue that volcanic eruptions had already stressed ecosystems.
CT:: || By presenting evidence pointing to a sudden asteroid impact, while noting that other factors may also have played a role || By agreeing that the extinction happened only through gradual climate change || By claiming that dinosaurs survived the asteroid impact || By arguing that iridium is common on Earth >> Iridium layer and crater support a rapid event.
CT: Based on Text 2, the iridium in the rock layer is significant because || iridium is common in asteroids but rare on Earth. || iridium causes volcanic eruptions. || iridium is found only in dinosaur bones. || iridium forms slowly over millions of years. >> It suggests an extraterrestrial source.
CT: The mention of volcanic eruptions in Text 2 suggests that || the extinction may have had more than one contributing cause. || the asteroid never struck Earth. || volcanoes produce iridium layers. || the author rejects the asteroid explanation. >> Volcanoes "had already stressed ecosystems."

P: Some people believe that reading on screens damages eyesight permanently.
P2: Long periods of screen use can cause temporary eye strain, dryness, and blurred vision, often because people blink less while staring at screens. Eye doctors recommend regular breaks, such as looking at something distant every twenty minutes. There is little evidence, however, that screen use by itself causes permanent damage to adult vision.
CT:: || By acknowledging that screens can cause temporary discomfort while arguing there is little evidence of permanent damage || By agreeing that screens permanently damage eyesight || By claiming that screens improve vision || By suggesting that people should stop blinking >> Temporary strain, but little evidence of lasting harm.
CT: Based on Text 2, screen use contributes to eye strain partly because people || blink less while looking at screens. || sit too far from screens. || read printed books too often. || take too many breaks. >> "People blink less while staring at screens."
CT: The author of Text 2 would most likely recommend that someone working at a computer all day || look at distant objects periodically. || avoid blinking. || use screens without breaks. || stop using computers entirely. >> Regular breaks looking at distant objects.

P: Some economists argue that automation will eliminate most jobs within a few decades.
P2: Past waves of automation, such as the mechanization of farming, eliminated many specific jobs but also created new types of work, from factory employment to services. Automation can cause serious hardship for workers whose skills become obsolete, but history suggests that total employment has tended to recover as economies adapt, though often slowly and unevenly.
CT:: || By arguing that automation historically created new work even as it eliminated some jobs, though transitions can be difficult || By agreeing that automation will eliminate most jobs || By claiming that automation never causes hardship || By suggesting that farming was never mechanized >> History shows job loss and creation.
CT: The author of Text 2 mentions the mechanization of farming mainly to || provide a historical example of automation's mixed effects on work. || argue that farming should not be mechanized. || explain how factories were built. || show that farmers opposed machines. >> It eliminated some jobs and was followed by new types of work.
CT: The author of Text 2 would most likely agree with Text 1 that automation || can eliminate specific jobs. || will end all employment. || creates no new work. || affects all workers equally. >> "Eliminated many specific jobs."

P: Some coaches argue that young athletes should specialize in a single sport early to develop elite skills.
P2: Studies of college and professional athletes found that many played several sports during childhood and specialized only in their teens. Early specialization has been linked to higher rates of overuse injuries and burnout, while playing multiple sports may develop a broader range of physical skills.
CT:: || By presenting evidence that many elite athletes played multiple sports early and that early specialization carries risks || By agreeing that all young athletes should specialize early || By claiming that professional athletes never played other sports || By arguing that playing multiple sports causes injuries >> Many elite athletes diversified; specialization is linked to injuries and burnout.
CT: Based on Text 2, early specialization has been linked to || more overuse injuries and burnout. || fewer injuries. || greater enjoyment of sports. || a broader range of skills. >> Linked to "higher rates of overuse injuries and burnout."
CT: Which choice best describes the relationship between the texts? || Text 2 challenges the recommendation in Text 1 with evidence about athletes' development. || Text 2 supports the recommendation in Text 1. || Text 2 discusses professional contracts. || Text 2 agrees but adds that coaches should train more. >> Evidence counters early specialization.

P: Some critics argue that translated poems are pale imitations that cannot capture the original work.
P2: Translation inevitably changes a poem, since sounds, rhythms, and wordplay rarely survive intact in another language. Yet many translators see their work as creating a new poem that conveys the spirit of the original. Some translated poems have been admired as works of art in their own right and have introduced readers to writers they could never otherwise read.
CT:: || By acknowledging that translation changes poems while arguing that translations can be valuable works of art in their own right || By agreeing that translations have no value || By claiming that translation preserves every sound and rhythm || By suggesting that readers should learn every language >> Changes are inevitable, but translations can be admired.
CT: The author of Text 2 would most likely agree with the critics in Text 1 that || translation cannot preserve every aspect of a poem. || translated poems are worthless. || wordplay translates perfectly. || poets should never be translated. >> "Sounds, rhythms, and wordplay rarely survive intact."
CT: Based on Text 2, one benefit of translated poems is that they || introduce readers to writers they could not otherwise read. || replace the original poems. || preserve every rhyme exactly. || make original languages unnecessary. >> They "introduced readers to writers they could never otherwise read."

P: Some residents oppose building apartment complexes in their neighborhoods, arguing that new housing will lower nearby property values.
P2: Studies of several cities found that new apartment buildings generally had little effect on nearby home values, and in some cases values rose slightly as new residents supported local shops and services. Effects varied, but the fear of widespread declines was not supported by most of the evidence.
CT:: || By citing studies showing that new apartments usually had little negative effect on nearby property values || By agreeing that new apartments always lower property values || By claiming that shops closed near new apartments || By arguing that no new housing should be built >> Little effect, sometimes slight increases.
CT: Based on Text 2, property values sometimes rose near new apartment buildings because || new residents supported local shops and services. || the apartments were demolished. || homeowners renovated their houses. || fewer people lived in the neighborhood. >> New residents "supported local shops and services."
CT: The author of Text 2 acknowledges that || effects of new apartment buildings varied. || property values fell everywhere. || no studies have been done. || all residents support new housing. >> "Effects varied."

P: Some writers claim that dogs feel guilty when they misbehave, pointing to the "guilty look" dogs show when owners discover a mess.
P2: In one experiment, owners left the room, and researchers either had the dog eat a forbidden treat or removed it themselves. Owners were then told, sometimes falsely, that their dog had misbehaved. Dogs showed the "guilty look" most often when owners scolded them, regardless of whether they had actually eaten the treat, suggesting the look responds to the owner's behavior rather than to guilt.
CT:: || By arguing that the "guilty look" appears in response to owners' scolding, not necessarily because dogs misbehaved || By agreeing that dogs feel guilt after misbehaving || By claiming that dogs never react to scolding || By suggesting that dogs cannot eat treats >> The look appeared when scolded, regardless of actual behavior.
CT: Based on Text 2, the experiment included dogs whose treats were removed by researchers in order to || compare dogs that misbehaved with dogs that did not. || make the dogs hungry. || train the dogs to obey. || test the owners' memories. >> It separated actual misbehavior from scolding.
CT: Which choice best describes the relationship between the texts? || Text 2 offers evidence for a different explanation of the behavior described in Text 1. || Text 2 confirms the explanation in Text 1. || Text 2 describes a different animal. || Text 2 restates Text 1. >> The look reflects owners' behavior, not guilt.

P: Many people think that the Great Wall of China was built all at once as a single continuous structure.
P2: The walls known collectively as the Great Wall were built, rebuilt, and extended by different dynasties over roughly two thousand years. Many sections are separate walls rather than one continuous line, and they were constructed from local materials ranging from rammed earth to stone and brick.
CT:: || By explaining that the walls were built in many phases by different dynasties and do not form one continuous structure || By agreeing that the wall was built all at once || By claiming that the wall is made entirely of brick || By arguing that the wall was never built >> Built over two thousand years in separate sections.
CT: Based on Text 2, sections of the Great Wall differ in their materials because || builders used locally available materials. || every section was designed by the same person. || brick was the only material available. || the wall was built in a single year. >> "Constructed from local materials."
CT: Which choice best describes how Text 2 responds to the belief in Text 1? || It corrects the belief with historical information about how the walls were built. || It supports the belief with archaeological evidence. || It ignores the belief entirely. || It argues that the wall is a single brick structure. >> Many dynasties, separate sections.

P: Some parents believe that children who watch educational television learn as much as children who read books.
P2: Studies of young children suggest that well-designed educational programs can teach vocabulary and early math concepts. However, children tend to learn more when adults watch with them and discuss what they see, and shared book reading exposes children to a wider range of vocabulary than most television programs do.
CT:: || By acknowledging that educational programs can teach some skills while suggesting that shared reading offers additional benefits || By agreeing that television teaches exactly as much as books || By claiming that children learn nothing from television || By suggesting that adults should never watch television with children >> Programs help, but reading exposes children to more vocabulary.
CT: Based on Text 2, children learn more from educational programs when || adults watch with them and discuss what they see. || they watch alone. || programs have no vocabulary words. || they watch for many hours a day. >> Learning improves with adult discussion.
CT: The author of Text 2 would most likely agree with the parents in Text 1 that || educational television can help children learn. || television is better than reading. || books have no educational value. || children should avoid educational programs. >> Programs "can teach vocabulary and early math concepts."

P: Some scientists have suggested that humans can survive on Mars in the near future by building domed cities.
P2: Mars presents major challenges beyond breathable air: its thin atmosphere provides little protection from radiation, temperatures swing drastically, and dust storms can last for weeks. Engineers are studying underground habitats and radiation shielding, but many researchers believe that long-term settlement will require technologies that do not yet exist.
CT:: || By arguing that Mars poses challenges, such as radiation and dust storms, that may require technologies not yet developed || By agreeing that domed cities will solve every challenge on Mars || By claiming that Mars has a thick atmosphere || By suggesting that humans should never study Mars >> Radiation, temperature swings, and dust require new technology.
CT: Based on Text 2, engineers are studying underground habitats most likely because they || could offer protection from radiation. || are easier to see from Earth. || require no materials. || would prevent all dust storms. >> Radiation shielding is a key concern.
CT: Which choice best describes the relationship between the texts? || Text 2 describes obstacles that complicate the optimistic suggestion in Text 1. || Text 2 supports Text 1 by listing completed Martian cities. || Text 2 discusses the Moon rather than Mars. || Text 2 agrees that settlement is easy. >> Challenges make near-term settlement difficult.

P: Some art critics dismiss street art as vandalism with no artistic merit.
P2: Unauthorized graffiti can damage property, and many cities prohibit it. Yet some street artists create commissioned murals that neighborhoods welcome, and several museums have exhibited works by artists who began on the street. Whether a piece counts as vandalism or art may depend on permission, context, and community response.
CT:: || By arguing that street art can have artistic merit and that its status depends on factors such as permission and context || By agreeing that all street art is vandalism || By claiming that graffiti never damages property || By suggesting that museums should ban street artists >> Commissioned murals and museum exhibitions show merit.
CT: The author of Text 2 would most likely agree with the critics in Text 1 that || unauthorized graffiti can damage property. || all murals are vandalism. || museums should never show street art. || street artists never receive commissions. >> "Unauthorized graffiti can damage property."
CT: Based on Text 2, commissioned murals differ from vandalism mainly because they || are created with permission and welcomed by communities. || use different kinds of paint. || are always painted indoors. || are created only by museum employees. >> Permission and community response matter.

P: Some educators argue that students learn best when teachers explain concepts directly before students practice.
P2: Other educators favor having students attempt a problem before receiving instruction. Studies suggest that struggling with a problem first can help students notice what they do not understand, making the later explanation more meaningful. However, this approach works best when students have enough background knowledge to make progress; complete beginners may simply become frustrated.
CT:: || By suggesting that attempting problems before instruction can help, though only when students have sufficient background knowledge || By agreeing that direct explanation should always come first for every student || By claiming that instruction is unnecessary || By arguing that frustration always improves learning >> Productive struggle helps, with a caveat for beginners.
CT: Based on Text 2, attempting a problem before instruction can be helpful because it || helps students recognize gaps in their understanding. || replaces the need for explanation. || makes students more frustrated. || works best for complete beginners. >> Struggle helps students "notice what they do not understand."
CT: The author of Text 2 would most likely agree that the approach described in Text 1 may be especially suitable for || complete beginners with little background knowledge. || experts who have mastered a topic. || students who dislike explanations. || advanced students preparing for competitions. >> Beginners "may simply become frustrated" by struggling first.

P: Some ecologists argue that all non-native species should be removed from protected areas.
P2: Many non-native species cause serious harm, outcompeting native plants and animals. But some have become integrated into ecosystems in ways that benefit native wildlife; certain non-native shrubs, for example, now provide nesting sites for endangered birds where native vegetation has disappeared. Managers may need to evaluate each species' effects rather than applying a single rule.
CT:: || By arguing that while many non-native species are harmful, some benefit native wildlife and should be evaluated individually || By agreeing that every non-native species must be removed || By claiming that non-native species never cause harm || By suggesting that endangered birds prefer native shrubs only >> Some non-natives help; case-by-case evaluation is needed.
CT: The author of Text 2 mentions non-native shrubs mainly to || give an example of a non-native species that benefits native wildlife. || show that shrubs outcompete all native plants. || argue that birds should be relocated. || explain how shrubs were introduced. >> They provide nesting sites for endangered birds.
CT: The author of Text 2 would most likely agree with the ecologists in Text 1 that || many non-native species can harm ecosystems. || no non-native species are harmful. || protected areas need no management. || native vegetation is unimportant. >> "Many non-native species cause serious harm."

P: Some nutrition writers claim that drinking eight glasses of water a day is necessary for good health.
P2: The body's water needs vary with climate, activity, and body size, and much of the water people need comes from food and other beverages. Most healthy adults can rely on thirst to guide how much they drink. The eight-glass rule may be a useful reminder for some people but is not a scientific requirement for everyone.
CT:: || By arguing that water needs vary and that the eight-glass rule is not a universal requirement || By agreeing that everyone must drink exactly eight glasses || By claiming that people need no water || By suggesting that food contains no water >> Needs vary; thirst is usually a reliable guide.
CT: Based on Text 2, much of the water people need comes from || food and other beverages. || only plain water. || medical supplements. || sweat. >> "Much of the water people need comes from food and other beverages."
CT: The author of Text 2 would most likely say that the eight-glass rule || may help some people but is not required for everyone. || is harmful to everyone. || is a proven scientific requirement. || should be replaced by twenty glasses. >> "A useful reminder for some people."

P: Some historians argue that the invention of the printing press immediately transformed European society.
P2: Printing did make books cheaper and more widely available, but literacy rates rose slowly, and for decades most printed works were religious texts and classical writings already familiar to scholars. The press's broader social effects unfolded over generations as schooling expanded and new kinds of writing, such as newspapers, developed.
CT:: || By arguing that the printing press's effects on society developed gradually rather than immediately || By claiming that printing made books more expensive || By agreeing that society changed overnight || By suggesting that the printing press was never used >> Effects "unfolded over generations."
CT: Based on Text 2, one reason the printing press's social effects were gradual is that || literacy rates increased slowly. || books became more expensive. || newspapers were printed first. || scholars stopped reading. >> "Literacy rates rose slowly."
CT: The author of Text 2 would most likely agree with the historians in Text 1 that the printing press || made books more widely available. || had no effect on society. || was invented after newspapers. || reduced literacy. >> "Printing did make books cheaper and more widely available."

P: Some psychologists argue that people make better decisions when they carefully analyze every option.
P2: For complex choices with many factors, such as choosing an apartment, some studies have found that people who thought carefully and then took a break before deciding made choices they were later more satisfied with. For simple decisions, careful analysis works well. Deliberation is valuable, but the best approach may depend on the type of decision.
CT:: || By suggesting that the best decision-making approach may depend on the complexity of the decision || By agreeing that careful analysis is best for every decision || By claiming that people should never think about decisions || By arguing that simple decisions require breaks >> The approach depends on the decision type.
CT: Based on Text 2, people deciding among many complex options were more satisfied when they || thought carefully and then took a break before deciding. || decided instantly without thinking. || analyzed only one factor. || let someone else decide. >> They "thought carefully and then took a break."
CT: The author of Text 2 would most likely agree with the psychologists in Text 1 that || deliberation has value. || analysis always leads to worse decisions. || breaks are harmful. || all decisions are simple. >> "Deliberation is valuable."

P: Many people believe that goldfish have memories lasting only a few seconds.
P2: Experiments have shown that goldfish can be trained to respond to sounds or colors associated with feeding and can remember these associations for months. Some goldfish have learned to push levers for food at particular times of day. Their memory is far better than the popular belief suggests.
CT:: || By presenting experimental evidence that goldfish can remember associations for months || By agreeing that goldfish forget everything within seconds || By claiming that goldfish cannot learn || By arguing that goldfish do not respond to food >> Training experiments show long-lasting memory.
CT: The author of Text 2 mentions goldfish pushing levers mainly to || provide an additional example of goldfish learning. || show that goldfish are aggressive. || explain how aquariums are cleaned. || argue that goldfish should not be fed. >> It shows learning tied to times of day.
CT: Which choice best describes how Text 2 relates to Text 1? || It uses evidence to contradict the popular belief in Text 1. || It supports the belief in Text 1. || It discusses the memories of dogs. || It restates Text 1 without evidence. >> Memory lasts months, not seconds.
"""
