"""Cross-text units, batch 4 (format in passage_data1.py). Original texts; studies are illustrative."""

UNITS = """
P: Some commentators argue that social media has made teenagers less happy.
P2: Large surveys find a small average association between heavy social media use and lower well-being among teenagers, but the effect varies widely. For some teens, especially those who use it passively for many hours, social media is linked to worse mood; others use it to maintain friendships and find support. Researchers caution that the average link is modest and does not show that social media causes unhappiness.
CT:: || By noting that the association is small, varies among teens, and does not establish causation || By agreeing that social media makes all teenagers unhappy || By claiming that social media always improves well-being || By arguing that teenagers do not use social media >> Modest, variable association without causal proof.
CT: Based on Text 2, which teens are more likely to show a link between social media and worse mood? || Those who use it passively for many hours || Those who use it to maintain friendships || Those who never use it || Those who find support online >> Passive heavy use is linked to worse mood.
CT: The author of Text 2 would most likely say that the claim in Text 1 || overstates what the evidence shows. || is fully proven by surveys. || ignores teenagers entirely. || underestimates social media's harms. >> The link is modest and not causal.

P: Some farmers believe that plowing fields thoroughly before planting always produces the best harvests.
P2: Plowing can control weeds and loosen soil, but it also exposes soil to erosion and can reduce the organic matter that holds moisture. Many farmers who have switched to no-till methods, planting directly into the remains of the previous crop, report healthier soil and similar yields over time, though weeds can be harder to manage.
CT:: || By acknowledging plowing's benefits while noting its drawbacks and describing an alternative with comparable yields || By agreeing that plowing always produces the best harvests || By claiming that plowing has no benefits || By arguing that no-till methods eliminate weeds >> Plowing has pros and cons; no-till can match yields.
CT: Based on Text 2, a challenge of no-till farming is that || weeds can be harder to manage. || soil erodes more quickly. || yields always fall. || crops cannot be planted. >> "Weeds can be harder to manage."
CT: The author of Text 2 would most likely agree with the farmers in Text 1 that plowing || can help control weeds. || prevents all erosion. || always increases organic matter. || is the only way to plant crops. >> "Plowing can control weeds and loosen soil."

P: Some art historians argue that a famous painter worked alone and developed his distinctive style entirely by himself.
P2: Workshop records show that the painter employed several assistants who prepared canvases, mixed pigments, and sometimes painted backgrounds. Letters also reveal that he studied and admired the works of earlier artists. His style was distinctive, but it developed within a network of collaborators and influences.
CT:: || By arguing that the painter's work involved assistants and drew on earlier artists' influence || By agreeing that the painter worked entirely alone || By claiming that the painter's style was not distinctive || By arguing that assistants painted all of his works >> Records show assistants and influences.
CT: The author of Text 2 would most likely agree with the art historians in Text 1 that the painter's style || was distinctive. || was copied from his assistants. || did not exist. || was identical to earlier artists' styles. >> "His style was distinctive."
CT: Based on Text 2, the painter's assistants || sometimes painted backgrounds. || signed his paintings. || taught him to paint. || never touched the canvases. >> Assistants "sometimes painted backgrounds."

P: Some psychologists argue that people's personalities remain fixed after early adulthood.
P2: Long-term studies that followed people for decades found that many personality traits change gradually across adulthood. On average, people become more conscientious and emotionally stable as they age, though individuals differ in how much they change. Personality appears more stable in adulthood than in childhood but not entirely fixed.
CT:: || By presenting evidence that personality continues to change gradually during adulthood || By agreeing that personality never changes after early adulthood || By claiming that personality changes rapidly every year || By arguing that personality cannot be measured >> Traits shift across decades.
CT: Based on Text 2, on average people tend to become more || conscientious and emotionally stable as they age. || impulsive with age. || anxious as they age. || similar to their childhood selves. >> More conscientious and emotionally stable.
CT: The author of Text 2 would most likely agree with Text 1 that personality || is more stable in adulthood than in childhood. || is completely fixed after twenty. || changes more in adulthood than childhood. || has nothing to do with age. >> "More stable in adulthood than in childhood."

P: Some travelers believe that visiting popular tourist destinations during peak season offers the best experience.
P2: Peak season often brings pleasant weather and full schedules of events. Yet crowds, long lines, and higher prices can make visits stressful. Many travelers who visit during the "shoulder seasons" just before or after peak times report mild weather, lower costs, and a more relaxed experience.
CT:: || By acknowledging peak season's advantages while suggesting that shoulder seasons can offer a better overall experience for many travelers || By agreeing that peak season is always best || By claiming that peak season has no advantages || By arguing that travelers should avoid tourist destinations >> Shoulder seasons offer mild weather and lower costs.
CT: Based on Text 2, the shoulder seasons are || periods just before or after peak times. || the coldest months of the year. || the busiest times for tourism. || times when attractions are closed. >> "Just before or after peak times."
CT: The author of Text 2 would most likely agree with the travelers in Text 1 that peak season || often offers pleasant weather and many events. || is cheaper than other seasons. || has the shortest lines. || is the least crowded time. >> "Pleasant weather and full schedules of events."

P: Some scientists claim that honeybees are the most important pollinators for wild plants.
P2: Honeybees pollinate many crops, but studies of wild plant communities have found that native bees, such as bumblebees and solitary bees, often do more of the pollination. In some habitats, large honeybee colonies may even compete with native bees for flowers.
CT:: || By arguing that native bees often pollinate wild plants more than honeybees and that honeybees can compete with them || By agreeing that honeybees pollinate most wild plants || By claiming that honeybees pollinate no crops || By arguing that native bees do not visit flowers >> Native bees do more wild pollination.
CT: Based on Text 2, a possible concern about large honeybee colonies is that they || may compete with native bees for flowers. || pollinate too few crops. || cannot find flowers. || increase native bee populations. >> They "may even compete with native bees."
CT: The author of Text 2 would most likely agree with Text 1 that honeybees || pollinate many crops. || are the only pollinators of wild plants. || never compete with other bees. || cannot pollinate crops. >> "Honeybees pollinate many crops."

P: Some historians argue that a certain ancient empire fell primarily because of economic problems.
P2: The empire did suffer from inflation and heavy taxation, but it also faced repeated invasions, civil wars, and outbreaks of disease. Historians increasingly describe its decline as the result of many interacting pressures rather than a single cause.
CT:: || By acknowledging economic problems while arguing that many other pressures also contributed to the empire's decline || By claiming that the empire had no economic problems || By agreeing that economics was the only cause || By arguing that the empire never declined >> Multiple interacting pressures.
CT: Based on Text 2, which factor contributed to the empire's decline in addition to economic problems? || Repeated invasions || Declining taxes || Rapid population growth || A lack of civil wars >> "Repeated invasions, civil wars, and outbreaks of disease."
CT: The author of Text 2 would most likely agree with the historians in Text 1 that the empire || experienced economic difficulties. || fell because of disease alone. || never faced invasions. || had no inflation. >> "The empire did suffer from inflation and heavy taxation."

P: Some writers argue that owning a pet improves people's health.
P2: Some studies have linked dog ownership with more physical activity, since dog owners take regular walks. Other research finds that pet owners differ from non-owners in income, age, and lifestyle, which could explain some health differences. Pets may offer benefits, but the evidence that pets themselves improve health is mixed.
CT:: || By noting that some benefits have been linked to pets but that differences between owners and non-owners make the evidence mixed || By agreeing that pets always improve health || By claiming that pets harm health || By arguing that dog owners never walk >> Benefits are possible, but confounders exist.
CT: Based on Text 2, dog ownership has been linked to more physical activity because || dog owners take regular walks. || dogs require no exercise. || owners are younger than non-owners. || dogs discourage walking. >> "Dog owners take regular walks."
CT: The author of Text 2 mentions differences in income, age, and lifestyle mainly to || suggest other possible explanations for health differences. || show that pets are expensive. || describe who adopts pets. || argue that pets should be banned. >> These "could explain some health differences."

P: Some economists argue that raising the minimum wage always leads to large job losses.
P2: Studies comparing neighboring regions with different minimum wage increases have often found small or no effects on employment for moderate increases. Researchers caution, however, that very large increases, or increases in areas with low average wages, might have different effects that are harder to predict.
CT:: || By presenting evidence that moderate increases often have small employment effects, while noting uncertainty about very large increases || By agreeing that any increase causes large job losses || By claiming that minimum wage increases always create jobs || By arguing that minimum wages should be eliminated >> Small effects for moderate increases; uncertainty for large ones.
CT: Based on Text 2, researchers are less certain about the effects of || very large minimum wage increases. || moderate increases in neighboring regions. || increases that have already been studied. || wages above the minimum. >> Very large increases "might have different effects."
CT: The author of Text 2 would most likely object to the word "always" in Text 1 because || moderate increases have often shown little effect on employment. || minimum wages never change. || all increases create jobs. || job losses cannot be measured. >> Many studies found small or no effects.

P: Some teachers believe that students should not use calculators until they have mastered arithmetic by hand.
P2: Research suggests that calculators, used thoughtfully, do not harm basic skills and can let students focus on problem solving and patterns. However, studies also show that students benefit from understanding arithmetic concepts and developing number sense before relying heavily on calculators.
CT:: || By suggesting that calculators can be helpful when used thoughtfully, while agreeing that understanding arithmetic remains important || By claiming that calculators always harm basic skills || By arguing that students should never learn arithmetic || By agreeing that calculators should be banned entirely >> Thoughtful use helps, but number sense matters.
CT: The author of Text 2 would most likely agree with the teachers in Text 1 that || students benefit from understanding arithmetic concepts. || calculators should never be used. || problem solving is unimportant. || number sense cannot be taught. >> Students "benefit from understanding arithmetic concepts."
CT: Based on Text 2, calculators used thoughtfully can allow students to || focus on problem solving and patterns. || skip learning numbers. || avoid all math classes. || memorize answers without thinking. >> They let students "focus on problem solving and patterns."

P: Some scientists argue that whales are too large to be affected by small plastic particles in the ocean.
P2: Filter-feeding whales swallow enormous volumes of water to catch tiny prey, and researchers analyzing their feeding have estimated that some whales may ingest millions of microplastic particles daily. The long-term health effects are still being studied, but the scale of exposure suggests that size does not protect whales from plastic pollution.
CT:: || By arguing that whales' feeding methods may expose them to large amounts of microplastics despite their size || By agreeing that whales are unaffected by plastic || By claiming that whales avoid eating prey || By arguing that microplastics do not exist in oceans >> Filter feeding leads to heavy exposure.
CT: Based on Text 2, filter-feeding whales may ingest many microplastics because they || swallow huge volumes of water while feeding. || eat plastic deliberately. || live only near beaches. || have very small mouths. >> They "swallow enormous volumes of water."
CT: The author of Text 2 acknowledges that || the long-term health effects are still being studied. || microplastics are proven to kill all whales. || whales eat only large fish. || plastic pollution has ended. >> "The long-term health effects are still being studied."

P: Some writers claim that people who multitask are more productive.
P2: Experiments show that switching between tasks takes time and increases errors, because the brain must reorient each time attention shifts. People who frequently multitask often perform worse on tests of attention than people who multitask less, although they tend to believe they are skilled at it.
CT:: || By presenting evidence that multitasking tends to reduce efficiency and increase errors || By agreeing that multitaskers are more productive || By claiming that switching tasks takes no time || By arguing that attention cannot be tested >> Switching costs time and accuracy.
CT: Based on Text 2, frequent multitaskers tend to || believe they are good at multitasking despite performing worse on attention tests. || perform better on attention tests. || avoid switching tasks. || make fewer errors than others. >> They "tend to believe they are skilled at it."
CT: Which choice best describes the relationship between the texts? || Text 2 challenges the claim made in Text 1. || Text 2 supports the claim made in Text 1. || Text 2 discusses computer processors. || Text 2 agrees but adds that multitasking is fun. >> Evidence counters productivity claims.

P: Some urban officials argue that banning cars from city centers will harm local businesses.
P2: When several European cities closed central districts to most car traffic, some shops initially reported fewer customers. Within a few years, however, foot traffic increased in many of these districts, and surveys found that pedestrians often spent more time and money in shops than drivers had. Results varied by city and depended on transit access.
CT:: || By noting that early losses were often followed by increased foot traffic and spending, though results varied || By agreeing that car bans always harm businesses permanently || By claiming that shops had more customers immediately after every ban || By arguing that transit access is irrelevant >> Initial dips, later gains, with variation.
CT: Based on Text 2, the success of car-free districts depended partly on || access to public transit. || the number of parking lots. || the color of shop signs. || banning pedestrians. >> Results "depended on transit access."
CT: The author of Text 2 would most likely agree with the officials in Text 1 that || some shops may lose customers at first. || all businesses close after car bans. || pedestrians never shop. || car bans have no effects. >> "Some shops initially reported fewer customers."

P: Some literary critics argue that a novel's meaning is determined entirely by what its author intended.
P2: Authors' intentions can illuminate their works, and letters or interviews often reveal what writers hoped to achieve. Yet readers from different times and places frequently find meanings the author never anticipated, and many critics argue that these interpretations can be valid if they are supported by the text itself.
CT:: || By acknowledging the value of authors' intentions while arguing that readers can find valid meanings beyond them || By agreeing that only the author's intention matters || By claiming that authors' intentions are always irrelevant || By arguing that novels have no meaning >> Intentions help, but textual evidence supports other readings.
CT: Based on Text 2, a reader's interpretation is valid if it is || supported by the text itself. || approved by the author's family. || the same as the author's intention. || published in a newspaper. >> Valid "if they are supported by the text itself."
CT: The author of Text 2 would most likely agree with the critics in Text 1 that || authors' intentions can shed light on their works. || readers' interpretations are never valid. || letters from authors are unreliable. || novels have one fixed meaning. >> "Authors' intentions can illuminate their works."

P: Some researchers argue that fish do not feel pain because they lack certain brain structures found in mammals.
P2: Fish have nerve receptors that respond to harmful stimuli, and experiments show that fish exposed to such stimuli change their behavior, avoiding areas where they were harmed and responding to pain-relieving drugs. Although fish brains differ from mammal brains, some scientists argue that these findings suggest fish may experience something like pain.
CT:: || By presenting behavioral and physiological evidence that fish may experience something like pain despite brain differences || By agreeing that fish cannot feel pain || By claiming that fish brains are identical to mammal brains || By arguing that pain-relieving drugs have no effect on fish >> Receptors, avoidance, and response to drugs.
CT: Based on Text 2, evidence that fish may feel pain includes that fish || respond to pain-relieving drugs. || have the same brain structures as mammals. || never avoid harmful areas. || lack nerve receptors. >> They respond "to pain-relieving drugs."
CT: The author of Text 2 would most likely agree with the researchers in Text 1 that || fish brains differ from mammal brains. || fish cannot sense harmful stimuli. || fish have no nerves. || the question has been completely settled. >> "Although fish brains differ from mammal brains."

P: Some parents believe that children should be praised for being smart to build their confidence.
P2: Studies have found that children praised for intelligence were more likely to avoid challenging tasks afterward, perhaps fearing they would look less smart if they failed. Children praised for effort were more willing to try harder problems and persisted longer after mistakes.
CT:: || By presenting evidence that praising effort encourages persistence more than praising intelligence || By agreeing that praising intelligence always builds confidence || By claiming that children should never be praised || By arguing that effort is unimportant >> Effort praise leads to more challenge-seeking.
CT: Based on Text 2, children praised for intelligence may avoid challenges because they || fear failing would make them seem less smart. || find easy tasks boring. || prefer working in groups. || do not understand praise. >> "Fearing they would look less smart."
CT: Which choice best describes the relationship between the texts? || Text 2 presents evidence that complicates the approach recommended in Text 1. || Text 2 supports the approach in Text 1. || Text 2 discusses adult workers. || Text 2 restates Text 1. >> Intelligence praise may backfire.

P: Some geologists argue that earthquakes can be predicted precisely by monitoring animal behavior.
P2: There are many anecdotes of animals behaving strangely before earthquakes, but systematic studies have not found reliable patterns. Animals behave unusually for many reasons, and reports tend to be remembered after an earthquake occurs. Scientists instead focus on estimating the long-term probability of earthquakes in particular regions.
CT:: || By arguing that systematic studies have not found reliable animal warning signs and that reports may be shaped by hindsight || By agreeing that animal behavior predicts earthquakes precisely || By claiming that animals never behave unusually || By arguing that earthquake risks cannot be estimated >> Anecdotes are unreliable and remembered afterward.
CT: The author of Text 2 mentions that reports "tend to be remembered after an earthquake occurs" mainly to || suggest why anecdotes may seem more convincing than they are. || show that animals remember earthquakes. || explain how earthquakes form. || argue that scientists ignore animals. >> Hindsight makes anecdotes seem predictive.
CT: Based on Text 2, scientists currently focus on || estimating the long-term probability of earthquakes in regions. || predicting the exact day of earthquakes. || training animals to detect earthquakes. || preventing earthquakes. >> They estimate "long-term probability."

P: Some urban planners argue that suburbs are always worse for the environment than cities.
P2: City residents generally drive less and live in smaller homes, which tends to reduce energy use per person. However, some suburbs with good transit and compact development have lower emissions than car-dependent areas within city limits. The environmental impact depends more on density, transit, and housing type than on whether an area is labeled urban or suburban.
CT:: || By arguing that environmental impact depends on factors such as density and transit rather than simply on whether an area is a suburb || By agreeing that every suburb is worse than every city neighborhood || By claiming that cities always produce more emissions || By arguing that transit has no effect on emissions >> Design matters more than labels.
CT: The author of Text 2 would most likely agree with the planners in Text 1 that city residents || tend to drive less. || always live in larger homes. || produce more emissions than all suburbanites. || never use transit. >> "City residents generally drive less."
CT: Based on Text 2, a suburb could have lower emissions than part of a city if it || has good transit and compact development. || has larger homes. || depends entirely on cars. || has no public transportation. >> Compact suburbs with transit can outperform car-dependent city areas.

P: Some writers claim that the ancient city of Troy described in epic poetry was purely imaginary.
P2: Excavations at a site in western Turkey have uncovered a city with multiple layers of settlement, including one destroyed around the time associated with the legendary war. While the poems contain myth and exaggeration, many archaeologists believe they may preserve memories of a real city and conflicts in the region.
CT:: || By presenting archaeological evidence of a real city that may have inspired the poems, while acknowledging their mythical elements || By agreeing that Troy was entirely imaginary || By claiming that the poems are completely accurate historical records || By arguing that no cities existed in western Turkey >> Excavations suggest a real basis.
CT: The author of Text 2 acknowledges that the poems || contain myth and exaggeration. || are exact historical accounts. || were written by archaeologists. || describe a city in Egypt. >> "The poems contain myth and exaggeration."
CT: Based on Text 2, the excavated city is significant because one of its layers || was destroyed around the time associated with the legendary war. || contains a copy of the poems. || proves every event in the poems. || was built in the modern era. >> The destruction layer matches the war's timing.

P: Some health writers argue that vitamin supplements are necessary for everyone.
P2: People with certain conditions, diets, or life stages may benefit from specific supplements; for example, pregnant women are often advised to take folic acid. For most healthy adults who eat a varied diet, however, large studies have found little benefit from routine multivitamins in preventing major diseases.
CT:: || By arguing that supplements help some groups but offer little benefit for most healthy adults with varied diets || By agreeing that everyone needs supplements || By claiming that supplements harm everyone || By arguing that pregnant women should avoid folic acid >> Targeted benefits, little general benefit.
CT: The author of Text 2 mentions folic acid for pregnant women mainly to || give an example of a group that may benefit from a specific supplement. || argue that all supplements are unnecessary. || explain how vitamins are made. || criticize doctors' advice. >> An example of targeted benefit.
CT: Based on Text 2, large studies found that routine multivitamins for healthy adults with varied diets || showed little benefit in preventing major diseases. || prevented most diseases. || caused serious harm. || were required by law. >> "Little benefit from routine multivitamins."
"""
