"""Passage units, batch 6 (format documented in passage_data1.py). Original texts; people and studies are illustrative."""

UNITS = """
P: When a hospital added a small garden where patients could sit outdoors, staff expected it to be used mainly by visitors. Instead, nurses began bringing patients recovering from surgery outside for short periods. Records later showed that these patients requested less pain medication on average than similar patients who stayed indoors, though the researchers noted that the patients who went outside may have been healthier to begin with.
CI:: || Patients who spent time in a hospital garden used less pain medication, though this may partly reflect differences in their health. || The hospital garden was used only by visitors. || Spending time outdoors doubled patients' need for pain medication. || Researchers proved that gardens cure illness. >> Less medication was requested, with a caution about health differences.
TS: Which choice best describes the function of the final clause, beginning with "though," in the text? || It acknowledges a possible alternative explanation for the finding. || It explains why the garden was built. || It describes how nurses chose which patients to bring outside. || It provides additional evidence that the garden reduced pain. >> Healthier patients might have needed less medication anyway.
IN: Based on the text, the researchers would most likely agree that || a study that randomly assigned patients to go outdoors would give stronger evidence. || the garden should be closed. || patients who stayed indoors were healthier. || pain medication should be eliminated. >> Their caution suggests a need to rule out preexisting differences.

P: The following text is from a novel. Grandfather had kept bees for fifty years, and he spoke to them every morning. "Good morning, ladies," he would say, lifting the lid. My mother said it was nonsense. But the summer he was in the hospital and she tended the hives, I heard her through the kitchen window, standing by the boxes in her bathrobe, saying softly, "Good morning, ladies. He'll be home soon."
CI:: || The narrator's mother, who once dismissed her father's habit, adopts it while he is in the hospital. || The narrator's mother refuses to care for the bees. || The grandfather stops keeping bees after fifty years. || The narrator teaches the bees to respond to speech. >> She repeats his greeting while he is away.
TS: Which choice best describes the function of the sentence "My mother said it was nonsense" in the text? || It establishes the mother's earlier attitude, which contrasts with her later behavior. || It explains why the grandfather talked to the bees. || It shows that the mother was afraid of bees. || It describes the hospital where the grandfather stayed. >> She calls it nonsense but later does it herself.
IN: Based on the text, the mother's words to the bees most likely reveal || her concern for her father and her wish to keep his routine going. || her belief that the bees were ill. || her plan to sell the hives. || her annoyance at having to wake up early. >> "He'll be home soon" shows care and continuity.

P: Scientists studying bamboo noticed that many species flower only once every several decades, and when they do, nearly all plants of the species flower at the same time, even in different countries. After flowering, the plants die. The simultaneous flowering produces an enormous quantity of seeds. Researchers suggest that this strategy may overwhelm seed-eating animals, which cannot eat all the seeds, allowing many to sprout.
CI:: || Some bamboo species flower all at once after decades, possibly producing more seeds than animals can eat. || Bamboo flowers every year in small numbers. || Seed-eating animals prevent bamboo from spreading. || Bamboo plants survive for decades after flowering. >> Mass flowering may overwhelm seed predators.
TS: Which choice best describes the overall structure of the text? || It describes an unusual pattern and then presents a possible explanation for it. || It explains how to grow bamboo at home. || It compares bamboo with trees. || It argues that bamboo should be protected. >> Pattern, then the explanation about overwhelming seed eaters.
IN: Based on the text, if bamboo plants flowered at different times over many years, seed-eating animals would most likely || be able to eat a larger share of the seeds. || starve because no seeds were produced. || avoid eating bamboo seeds. || cause the bamboo to flower more often. >> Staggered flowering would not overwhelm seed eaters.

P: In the 1970s, a city tore down an elevated highway that divided its waterfront from downtown. Many business owners predicted traffic chaos. Traffic did shift to other streets, but congestion did not increase as much as feared, partly because some drivers changed their routes or schedules and some switched to transit. The land along the water became a popular promenade lined with restaurants.
CI:: || Removing an elevated highway did not cause the predicted traffic chaos and opened the waterfront to public use. || Tearing down the highway caused severe traffic jams for decades. || Business owners supported removing the highway. || The city built a larger highway along the water. >> Congestion rose less than feared, and the waterfront was revitalized.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It presents a prediction that later developments did not fully support. || It explains why the highway was built. || It describes the promenade's restaurants. || It provides evidence that traffic decreased. >> Business owners predicted chaos.
IN: Based on the text, congestion increased less than predicted mainly because || drivers adapted by changing routes, schedules, or modes of travel. || the city banned cars downtown. || the population of the city fell. || a new highway was built elsewhere. >> Some drivers changed routes or schedules and some switched to transit.

P: Some animals appear to understand basic numbers. In one experiment, researchers trained chicks that were only a few days old to find food behind a screen marked with a certain number of dots. When the number of dots stayed the same but the dots' size and spacing changed, the chicks still chose correctly most of the time. This suggests that the chicks were responding to quantity rather than to the overall appearance of the pattern.
CI:: || Young chicks appear able to recognize a quantity of dots even when the dots' appearance changes. || Chicks cannot distinguish between different numbers of objects. || Chicks prefer larger dots to smaller dots. || Chicks learn numbers only after several months. >> They chose correctly despite changes in size and spacing.
TS: Which choice best describes the function of the third sentence in the text as a whole? || It describes a test that helps distinguish responding to number from responding to appearance. || It explains how the chicks were fed. || It contradicts the claim in the first sentence. || It describes the age of the chicks. >> Changing size and spacing isolates quantity.
IN: Based on the text, if the chicks had chosen correctly only when the dots looked exactly the same as during training, researchers would most likely conclude that the chicks || might have been responding to the pattern's appearance rather than quantity. || understood numbers better than adults. || could not see the dots. || preferred one screen for unrelated reasons. >> Success only with identical patterns would not show number sense.

P: The following text is adapted from an essay. We tend to think of maps as neutral pictures of the world, but every map involves choices. A mapmaker decides what to include and what to leave out, which places deserve large labels, and what to put at the center. A subway map that shows stations evenly spaced, for instance, is useful for riders precisely because it distorts real distances.
CI:: || Maps are not neutral, because mapmakers make choices about what to show and how, sometimes distorting reality to make maps useful. || Maps always show distances accurately. || Subway maps are less useful than street maps. || Mapmakers include every feature of a place. >> Every map reflects choices; subway maps distort usefully.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It provides an example of a deliberate distortion that serves a purpose. || It contradicts the claim that maps involve choices. || It explains how subway stations are built. || It describes the history of mapmaking. >> The subway map illustrates purposeful choices.
IN: Based on the text, the writer would most likely agree that a map's value depends partly on || how well its choices fit the needs of its users. || how many features it includes. || whether it shows exact distances. || how old it is. >> The subway map is useful because of its distortion.

P: When a regional power company offered customers a discount for using less electricity during late afternoon peak hours, officials expected only a small response. Many households began running dishwashers and washing machines later in the evening instead. Peak demand fell enough that the company postponed building a new power plant it had planned.
CI:: || A discount for reducing peak-hour electricity use shifted household habits enough to delay a planned power plant. || Customers ignored the company's discount. || The company built a new power plant earlier than planned. || Households used more electricity during peak hours. >> Shifted usage lowered peak demand and delayed construction.
TS: Which choice best describes the overall structure of the text? || It describes an incentive, customers' responses, and a larger consequence. || It explains how electricity is generated. || It compares power companies in two regions. || It argues that dishwashers waste energy. >> Discount, behavior change, and a postponed plant.
IN: Based on the text, the company had planned to build a new power plant most likely because || it expected peak demand to exceed its existing capacity. || customers asked for higher prices. || the old plant produced too much electricity. || it wanted to shut down during the evening. >> Lower peak demand removed the immediate need.

P: Many species of songbird learn their songs by listening to adults during a sensitive period early in life. Researchers raising young birds in soundproof rooms found that birds that never heard adult songs developed simple, unusual songs. Birds that heard recordings of their own species during the sensitive period developed normal songs, while those exposed only after the period ended did not.
CI:: || Young songbirds must hear adult songs during an early sensitive period to develop normal songs. || Songbirds sing normal songs without ever hearing other birds. || Recordings have no effect on songbird learning. || Adult songbirds learn new songs every year. >> Timing of exposure determined whether songs developed normally.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It presents results showing that the timing of exposure matters. || It explains how soundproof rooms work. || It describes the birds' diet. || It contradicts the first sentence. >> Exposure during versus after the sensitive period.
IN: Based on the text, a young songbird that first hears adult songs after its sensitive period would most likely || fail to develop a fully normal song. || develop a normal song immediately. || stop singing altogether. || learn songs of other species instead. >> Birds exposed after the period "did not" develop normal songs.

P: Some libraries have eliminated late fees. Supporters argue that fees discourage low-income patrons, who may stop borrowing books rather than risk charges. One library system that removed fees found that many cardholders who had been blocked because of unpaid fines returned, and the rate at which books came back on time barely changed.
CI:: || Removing late fees brought back many patrons without significantly affecting how promptly books were returned. || Removing late fees caused most books to be returned late. || Late fees encourage more people to use libraries. || Libraries raised fees to improve return rates. >> Blocked patrons returned, and on-time returns barely changed.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It presents the reasoning of those who favor eliminating fees. || It describes the results of eliminating fees. || It explains how late fees are calculated. || It argues that libraries should charge more. >> Supporters argue fees discourage low-income patrons.
IN: Based on the text, a concern about eliminating late fees that the library system's results address is that || patrons would stop returning books on time. || libraries would lose all their books. || fewer people would visit libraries. || staff would need more training. >> On-time return rates "barely changed."

P: The following text is from a short story. Ana had always hated her middle name, Esperanza, which the other kids pronounced wrong on purpose. At her grandmother's funeral, the priest explained that Esperanza meant "hope," and that her grandmother had chosen it during a hard winter when the family had very little. Walking out of the church, Ana said the name quietly to herself, trying it out as if for the first time.
CI:: || Learning the meaning and history of her middle name changes how Ana feels about it. || Ana decides to change her middle name. || Ana's grandmother never liked the name Esperanza. || Ana's classmates begin pronouncing her name correctly. >> The name's meaning and origin lead her to reconsider it.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It establishes Ana's negative feelings about her name, which later shift. || It explains why the grandmother chose the name. || It describes the funeral in detail. || It reveals what the name means. >> She "had always hated" it before learning its story.
IN: Based on the text, Ana says the name "as if for the first time" because she || now sees it as meaningful rather than embarrassing. || had never heard the name before. || could not pronounce it correctly. || wanted to practice for a school play. >> Its meaning gives the name new significance.

P: Researchers studying ants noticed that when a colony's usual path to food was blocked, the ants quickly found a new route. Individual ants wandered somewhat randomly, but those that found food laid down chemical trails on the way back. Shorter routes were traveled more often, so their trails grew stronger, attracting more ants. In time, most ants followed the shortest available path, even though no single ant planned it.
CI:: || Ant colonies find short routes through chemical trails that strengthen with use, without any individual planning the route. || A leader ant chooses the best route for the colony. || Ants avoid paths that other ants have used. || Blocked paths prevent ants from finding food. >> Stronger trails on shorter routes lead most ants to them.
TS: Which choice best describes the overall structure of the text? || It describes an observation and then explains the process that produces it. || It compares ants with bees. || It describes how to remove ants from a home. || It argues that ants are smarter than other insects. >> New routes found, then explained by trail reinforcement.
IN: Based on the text, shorter routes develop stronger trails because || ants complete trips on them more often, adding chemicals more frequently. || they are chosen by the colony's queen. || longer routes have no chemical trails. || ants avoid walking on longer routes entirely. >> More frequent travel reinforces the trail.

P: In the nineteenth century, many people believed that tomatoes, a member of the nightshade family, were poisonous. Some nightshade plants are indeed toxic, and tomato leaves contain small amounts of harmful compounds. The fruit itself, however, is safe to eat. As more people cooked with tomatoes and suffered no ill effects, the fear faded, and tomatoes became a staple in many cuisines.
CI:: || Fears that tomatoes were poisonous faded as people ate the fruit safely, and tomatoes became widely used. || Tomato fruits are poisonous to eat. || All nightshade plants are safe. || Tomatoes were never eaten in the nineteenth century. >> The misconception had some basis but faded with experience.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It explains why the belief described in the first sentence was understandable. || It proves that the belief was correct. || It describes how tomatoes are cooked. || It explains how tomatoes became popular. >> Some relatives are toxic and the leaves contain harmful compounds.
IN: Based on the text, people's fear of tomatoes most likely faded because || experience showed that eating the fruit caused no harm. || scientists removed toxins from all tomatoes. || the government banned other nightshades. || tomato leaves became safe to eat. >> People "suffered no ill effects."

P: A company that manufactures outdoor jackets began offering free repairs for life. Executives worried that the program would reduce sales, since customers would buy fewer new jackets. Instead, sales rose. Surveys suggested that customers valued the promise that their jackets would last, and many chose the brand specifically because of the repair program.
CI:: || A lifetime repair program increased a jacket company's sales because customers valued durability. || The repair program caused the company's sales to fall. || Customers stopped buying jackets from the company. || Executives canceled the repair program. >> Sales rose as customers chose the brand for its repair promise.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It presents a concern that the outcome did not support. || It describes how jackets are repaired. || It explains why the jackets are durable. || It provides survey results. >> Executives feared lower sales, but sales rose.
IN: Based on the text, many customers most likely viewed the repair program as || evidence that the jackets were a worthwhile long-term purchase. || a reason to buy jackets from a competitor. || a sign that the jackets were poorly made. || an unnecessary expense. >> Customers "valued the promise that their jackets would last."

P: The following text is from a poem. My mother's garden in December / is only sticks and string, / the tags still marking rows / of what the ground will someday bring. / She walks it anyway each morning, / hands deep in her coat, / reading the empty beds / like a letter no one wrote.
CI:: || In winter, the speaker's mother walks through her bare garden, imagining what will grow there. || The speaker's mother has abandoned her garden. || The garden is full of flowers in December. || The speaker plants the garden with her mother. >> She walks the empty beds, marked for future growth.
TS: Which choice best describes the function of the final two lines of the poem? || They suggest that the mother finds meaning in the garden even when nothing is growing. || They reveal that the mother has received a letter. || They describe the plants blooming in spring. || They explain why the garden failed. >> Reading empty beds like a letter implies imagined meaning.
IN: Based on the text, the tags in the garden most likely || indicate where plants will grow in the coming season. || show the prices of plants for sale. || mark the graves of pets. || label plants that died during the winter. >> They mark "what the ground will someday bring."

P: Scientists investigating why some people get more mosquito bites than others found that mosquitoes are attracted partly by carbon dioxide and certain skin chemicals. People who produced more of particular fatty acids on their skin attracted mosquitoes far more strongly in lab tests, and this preference remained consistent when the same people were tested months apart.
CI:: || Mosquitoes are attracted to some people more than others partly because of consistent differences in skin chemicals. || Mosquitoes bite everyone equally. || Mosquito preferences change from week to week. || Carbon dioxide repels mosquitoes. >> Skin fatty acids predicted consistent attraction.
TS: Which choice best describes the function of the phrase "when the same people were tested months apart" in the text? || It indicates that the difference in attractiveness was stable over time. || It explains how mosquitoes detect carbon dioxide. || It suggests that the tests were unreliable. || It describes how participants were chosen. >> Consistency over months shows a lasting trait.
IN: Based on the text, a person who produces unusually high amounts of the relevant fatty acids would most likely || tend to be bitten more often than others. || never be bitten by mosquitoes. || attract mosquitoes only in winter. || repel mosquitoes from nearby people. >> These people "attracted mosquitoes far more strongly."

P: For much of the twentieth century, doctors advised patients with back pain to rest in bed. Later studies found that patients who stayed active, within limits, often recovered faster than those who rested. Many guidelines now recommend gentle movement, such as walking, for most cases of short-term back pain.
CI:: || Research has shifted medical advice for back pain from bed rest toward staying gently active. || Bed rest is the best treatment for all back pain. || Walking always worsens back pain. || Doctors have never recommended bed rest. >> Studies showing faster recovery with activity changed guidelines.
TS: Which choice best describes the overall structure of the text? || It describes earlier advice, presents research that challenged it, and states current recommendations. || It describes the causes of back pain. || It compares treatments for different illnesses. || It argues that doctors should stop treating back pain. >> Old advice, new studies, and current guidelines.
IN: Based on the text, a patient with short-term back pain following current guidelines would most likely be advised to || take short, gentle walks. || stay in bed for several weeks. || avoid all movement. || lift heavy weights immediately. >> Guidelines "recommend gentle movement, such as walking."

P: When archaeologists excavated an ancient village, they found that one house contained far more imported pottery, jewelry, and fine tools than the others. Some suggested that a wealthy chief lived there. Others noted that the house was also unusually large and contained many storage pits, and proposed that it may have been a communal building where valuable goods were kept for the whole village.
CI:: || Archaeologists disagree about whether a house full of valuable goods belonged to a wealthy leader or served as a communal storage building. || Archaeologists agree that a chief lived in the largest house. || The village had no imported goods. || Every house in the village contained the same objects. >> Two interpretations of the same evidence are presented.
TS: Which choice best describes the overall structure of the text? || It presents a finding and then describes two competing interpretations of it. || It describes the village's construction methods. || It compares two villages. || It explains how pottery was imported. >> Unusual house, chief interpretation, communal interpretation.
IN: Based on the text, which finding would most support the idea that the building was communal? || Evidence that goods in the storage pits were distributed to many households || A burial of a single wealthy individual beneath the house || Decorations showing one person's name || A single bed in the house >> Distribution to many households fits communal storage.

P: Some city governments have begun painting large murals on the walls of buildings in neighborhoods with high rates of graffiti. In several cities, murals were rarely tagged with graffiti, while plain walls nearby continued to be marked. Observers suggest that graffiti writers may respect the murals as art, or that the busy designs leave little blank space that invites tagging.
CI:: || Murals appear to discourage graffiti, possibly because of respect for the art or a lack of blank space. || Murals attract more graffiti than plain walls. || Graffiti writers prefer painting on murals. || Cities stopped painting murals because they were tagged. >> Murals were rarely tagged; two explanations are offered.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It offers possible explanations for the pattern described earlier. || It describes how murals are painted. || It contradicts the observation about murals. || It explains why graffiti is illegal. >> Respect for art or less blank space.
IN: Based on the text, a large, plain wall in the same neighborhood would most likely || be more likely to receive graffiti than a wall with a mural. || never be tagged with graffiti. || be tagged less often than a mural. || be chosen for a mural by graffiti writers. >> "Plain walls nearby continued to be marked."

P: The following text is from a memoir. My father repaired watches in a narrow shop with a single window. As a child, I thought his work was boring: hours bent over tiny gears, not speaking. Only when I tried it myself, years later, did I understand. The silence was not emptiness. It was concentration so complete that the rest of the world simply stepped aside.
CI:: || The narrator later realizes that her father's silent work reflected deep concentration rather than boredom. || The narrator still believes watch repair is boring. || The narrator's father talked constantly while working. || The narrator never tried repairing watches. >> Trying the work herself changes her understanding.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It presents the narrator's childhood view, which she later revises. || It describes the tools her father used. || It explains why the shop had one window. || It reveals the narrator's current career. >> "I thought his work was boring" is revised later.
IN: Based on the text, the narrator's understanding of her father's work changed because she || experienced the concentration it required firsthand. || read a book about watchmaking. || asked her father to explain his silence. || visited a larger watch factory. >> "Only when I tried it myself."

P: Many people assume that pandas eat bamboo because it is highly nutritious. In fact, bamboo is low in nutrients, and pandas digest only a small portion of what they eat. To survive, they eat for up to fourteen hours a day and conserve energy by moving relatively little. Their low-energy lifestyle is an adaptation to a diet that provides little fuel.
CI:: || Pandas survive on nutrient-poor bamboo by eating large amounts and conserving energy. || Bamboo is the most nutritious food available to pandas. || Pandas digest nearly all of the bamboo they eat. || Pandas are extremely active animals. >> Low nutrition leads to long feeding and low activity.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It introduces a mistaken assumption that the rest of the text corrects. || It explains why pandas live in forests. || It describes how pandas digest bamboo. || It summarizes the text's conclusion. >> "In fact, bamboo is low in nutrients."
IN: Based on the text, if pandas became much more active, they would most likely || need to find even more food to meet their energy needs. || be able to eat less bamboo. || digest bamboo more efficiently. || stop eating bamboo. >> Their low activity compensates for limited energy from food.

P: A study of online product reviews found that reviews rated as "helpful" by other shoppers tended to mention both positive and negative aspects of a product. Entirely positive reviews were rated helpful less often, perhaps because shoppers suspected them of being exaggerated or written by the seller.
CI:: || Shoppers found balanced reviews more helpful than entirely positive ones, possibly because they seemed more trustworthy. || Shoppers rated entirely positive reviews as most helpful. || Negative reviews are never considered helpful. || Sellers write most online reviews. >> Mixed reviews were rated helpful more often.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It contrasts entirely positive reviews with balanced ones and suggests a reason for the difference. || It describes how reviews are written. || It explains how the study was funded. || It argues that online reviews should be banned. >> Positive reviews were rated less helpful, possibly due to suspicion.
IN: Based on the text, a seller hoping to write a product description that shoppers trust might || acknowledge some limitations of the product. || describe the product only in glowing terms. || avoid mentioning the product's features. || remove all reviews from the website. >> Balanced information appears more credible.

P: When a coastal town was hit by a severe storm, residents who lived near a restored salt marsh reported less flooding than those living near a stretch of shoreline protected only by a concrete wall. Scientists noted that the marsh's plants slowed incoming waves and absorbed water, and that, unlike the wall, the marsh had not been damaged by the storm.
CI:: || A restored salt marsh reduced flooding during a storm and withstood the storm better than a concrete wall. || The concrete wall prevented more flooding than the marsh. || Residents near the marsh experienced more flooding. || The marsh was destroyed by the storm. >> Less flooding near the marsh; the marsh was undamaged.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It explains why the marsh provided better protection. || It describes how the concrete wall was built. || It presents residents' opinions about the storm. || It suggests that the marsh made flooding worse. >> Plants slowed waves and absorbed water.
IN: Based on the text, which statement about the concrete wall is best supported? || It was damaged by the storm. || It absorbed more water than the marsh. || It slowed waves more effectively than plants. || It protected residents from all flooding. >> "Unlike the wall, the marsh had not been damaged."

P: The following text is from a novel. The new teacher did not take attendance by reading names. Instead, on the first morning, she asked each student to say one thing they had noticed on the way to school. The answers were slow at first: a red car, a barking dog. By Friday, students were describing the shape of clouds, the smell of rain on hot pavement, and the exact number of steps from the bus stop to the door.
CI:: || A teacher's unusual attendance routine gradually makes her students more observant. || Students refuse to participate in the teacher's attendance routine. || The teacher reads each student's name aloud. || Students stop noticing anything on the way to school. >> Answers grow more detailed by Friday.
TS: Which choice best describes the overall structure of the text? || It introduces a new routine and shows how students' responses develop over a week. || It describes the teacher's background and training. || It compares two different schools. || It explains the rules for riding the school bus. >> First responses are simple; later ones are rich and precise.
IN: Based on the text, the teacher's routine was most likely intended to || encourage students to pay closer attention to the world around them. || find out which students rode the bus. || test students' memory of names. || shorten the school day. >> Students become more observant over the week.

P: Engineers designing a new stadium roof studied the structure of bird bones, which are hollow but reinforced with thin internal struts. The design allows bones to be light yet strong. Using a similar approach, the engineers created roof beams with hollow interiors crossed by thin supports, reducing the roof's weight by nearly a third without sacrificing strength.
CI:: || Engineers used the internal structure of bird bones as a model to create lighter, strong roof beams. || Bird bones are solid and heavy. || The stadium roof was made heavier to increase strength. || Engineers replaced the roof with bird feathers. >> Hollow, strutted beams mimic bird bones.
TS: Which choice best describes the function of the first two sentences in the text as a whole? || They describe the natural design that inspired the engineers' solution. || They explain why stadium roofs collapse. || They describe the stadium's location. || They compare birds with other animals. >> Bird bone structure is the model.
IN: Based on the text, the thin internal supports in the roof beams most likely serve to || add strength while keeping the beams light. || make the beams heavier. || let light into the stadium. || attract birds to the roof. >> Like struts in bones, they reinforce hollow beams.

P: A researcher studying how people choose where to sit in cafés found that most customers first selected seats along walls or near windows, leaving tables in the middle of the room empty until the café was crowded. The researcher suggests that people may prefer seats that offer a view while protecting their backs, a preference that may reflect a long-standing wariness of open spaces.
CI:: || Café customers tend to choose seats along walls or windows first, possibly reflecting a preference for protected positions with a view. || Customers prefer tables in the center of cafés. || Café customers choose seats randomly. || Cafés should remove wall seating. >> Wall and window seats fill first.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It offers an explanation for the seating pattern observed. || It describes the café's menu. || It contradicts the observation in the first sentence. || It explains how the researcher counted customers. >> A view with a protected back.
IN: Based on the text, a café owner who wanted center tables to be used more often might || add partitions or plants that make those tables feel more sheltered. || remove all windows. || make center tables smaller. || place center tables closer to the door. >> Sheltering center seats might satisfy the protective preference.

P: For centuries, scholars believed that a certain medieval poem was the work of a single author. A computer analysis of word choices and sentence patterns found distinct differences between the first half of the poem and the second. Some scholars now suggest that a second poet completed the work, though others argue that a single author's style may simply have changed over many years of writing.
CI:: || A computer analysis revealed stylistic differences in a medieval poem, leading to debate about whether it had one author or two. || The computer analysis proved that the poem had one author. || Scholars agree that three poets wrote the poem. || The poem's two halves are identical in style. >> Differences prompt two competing explanations.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It presents two possible interpretations of the analysis's results. || It explains how the computer analysis was performed. || It describes the poem's subject. || It concludes that the analysis was flawed. >> A second poet or a changing style.
IN: Based on the text, the scholars who favor a single author would most likely point to evidence that || the poem was written over a long period. || the poem was written in a single week. || two different names appear in the manuscript. || the two halves are written in different languages. >> A style may change "over many years of writing."
"""
