"""Passage units, batch 7 (format documented in passage_data1.py). Original texts; people and studies are illustrative."""

UNITS = """
P: When a university cafeteria stopped offering trays, officials hoped to save water used for washing them. They also found that food waste dropped by about a quarter. Without trays, students carried fewer dishes at once and tended to take only what they planned to eat, returning for seconds if they were still hungry.
CI:: || Removing trays from a cafeteria saved water and also reduced food waste as students took less food at a time. || Removing trays increased food waste in the cafeteria. || Students stopped eating in the cafeteria after trays were removed. || The cafeteria began washing trays more often. >> Waste dropped because students took only what they planned to eat.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It presents an additional, unexpected benefit of the change. || It explains why trays were expensive. || It describes how trays were washed. || It presents a drawback of removing trays. >> The water-saving goal led to a second benefit.
IN: Based on the text, students without trays wasted less food most likely because || carrying fewer dishes led them to take smaller amounts at once. || the cafeteria served smaller portions. || students were fined for leaving food. || fewer students ate in the cafeteria. >> They "tended to take only what they planned to eat."

P: The following text is from a novel. Every photograph in the hallway showed Grandmother smiling, but Lena had never once seen her smile in person. At the funeral, an old woman Lena did not recognize took her hand and said, "Your grandmother laughed louder than anyone I ever knew, before the war." Lena looked back at the hallway photographs and noticed, for the first time, that all of them had been taken long ago.
CI:: || Lena learns that her grandmother was once joyful and realizes that the smiling photographs come from an earlier time in her life. || Lena's grandmother smiled frequently in Lena's presence. || The old woman had never met Lena's grandmother. || The hallway photographs were taken recently. >> The stranger's comment and the old photographs reveal her grandmother's past.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It shows Lena connecting the stranger's comment to the photographs. || It explains why the grandmother stopped smiling. || It describes the funeral in detail. || It reveals that the photographs are of someone else. >> Noticing their age links them to "before the war."
IN: Based on the text, the phrase "before the war" most likely suggests that || the grandmother's experiences during the war changed her. || the grandmother did not live through the war. || the old woman met the grandmother after the war. || the photographs were taken during the war. >> Her laughter belongs to the time before the war.

P: Researchers studying sleep in dolphins found that the animals rest one half of their brain at a time while the other half stays alert. During this state, a dolphin keeps one eye open, surfaces regularly to breathe, and continues to watch for threats. After a period of time, the halves switch roles.
CI:: || Dolphins rest one half of the brain at a time, which lets them keep breathing and watching for danger. || Dolphins never sleep at all. || Dolphins sleep with both eyes closed at the bottom of the ocean. || Dolphins rest both halves of the brain at once. >> Alternating halves allow breathing and vigilance.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It describes activities dolphins can continue while half of the brain rests. || It explains how researchers measured brain activity. || It argues that dolphins sleep less than other animals. || It describes the dolphins' diet. >> One eye open, surfacing, and watching for threats.
IN: Based on the text, this form of sleep is most likely useful to dolphins because || they must keep breathing at the surface and stay alert even while resting. || they need to hunt continuously. || it allows them to dream more. || it prevents them from ever being tired. >> They "surface regularly to breathe" and watch for threats.

P: A city that installed sensors to monitor noise levels discovered that the loudest hours in one neighborhood were not late at night, as residents' complaints had suggested, but early in the morning, when delivery trucks unloaded at restaurants. Officials worked with businesses to shift deliveries to midday, and noise complaints fell.
CI:: || Noise sensors revealed that early-morning deliveries were a major source of noise, and rescheduling them reduced complaints. || Late-night noise was the main problem in the neighborhood. || Residents stopped complaining after the sensors were installed. || Restaurants stopped receiving deliveries. >> Sensors identified the true peak, leading to schedule changes.
TS: Which choice best describes the overall structure of the text? || It describes an unexpected finding and the action officials took in response. || It compares noise in several cities. || It explains how noise sensors work. || It argues that restaurants should close earlier. >> Discovery about morning noise, then shifted deliveries.
IN: Based on the text, residents' complaints before the sensors were installed were most likely || inaccurate about when the noise was worst. || entirely invented. || focused on midday deliveries. || caused by sensor malfunctions. >> Complaints suggested late night, but the loudest hours were early morning.

P: For years, scientists debated whether some dinosaurs cared for their young. Discoveries of fossilized nests changed the conversation. At one site, adult skeletons were found sitting on clutches of eggs in positions resembling those of brooding birds, suggesting that the adults were protecting or warming the eggs when they died.
CI:: || Fossils of adults positioned over eggs suggest that some dinosaurs cared for their eggs. || Dinosaurs abandoned their eggs immediately after laying them. || Scientists have never found dinosaur nests. || Brooding birds are descended from dinosaurs that ate eggs. >> Adults on nests resemble brooding birds.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It describes evidence that supports the idea of parental care. || It explains why scientists stopped studying dinosaurs. || It describes how fossils form. || It contradicts the first sentence. >> Adults found sitting on eggs.
IN: Based on the text, the adults' positions were significant because they || resembled those of modern birds that care for eggs. || showed that the adults were eating the eggs. || proved that the eggs never hatched. || indicated that the adults were running away. >> They resemble "brooding birds."

P: The following text is adapted from an essay. The first time I saw the ocean, I was sixteen and disappointed. I had imagined something like the postcards: impossible blue, gentle waves. The real ocean that day was gray and loud and cold, and it smelled of salt and seaweed. It took me years to understand that I had not been disappointed by the ocean. I had been disappointed by the postcards.
CI:: || The writer eventually realizes that her disappointment came from unrealistic expectations rather than from the ocean itself. || The writer still dislikes the ocean. || The writer's first visit to the ocean matched her expectations exactly. || The writer collects postcards of the ocean. >> She blames the postcards' idealized image.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It reframes the writer's early disappointment by identifying its true source. || It describes the weather on the day of the visit. || It explains why the writer bought postcards. || It shows that the writer never returned to the ocean. >> The disappointment was with the postcards.
IN: Based on the text, the details about the gray, loud, cold ocean mainly emphasize || the contrast between reality and the writer's expectations. || the danger of swimming in the ocean. || the writer's love of cold weather. || the pollution of the beach. >> They contrast with the "impossible blue" postcards.

P: When a school introduced a program in which students grew vegetables in a garden and then cooked them in class, researchers surveyed students' eating habits before and after. Students in the program reported eating more vegetables at home, and many said they were more willing to try unfamiliar foods. Students at a similar school without the program showed no such change.
CI:: || A school gardening and cooking program was linked to students eating more vegetables and trying new foods. || Students in the program ate fewer vegetables. || The comparison school also saw large changes in eating habits. || Students refused to cook the vegetables they grew. >> The program students improved; the comparison school did not.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It provides a comparison that strengthens the link between the program and the changes. || It describes the vegetables grown in the garden. || It suggests that the program had no effect. || It explains why the program was created. >> No change at the comparison school.
IN: Based on the text, growing vegetables themselves most likely made students || more interested in eating and trying foods. || less willing to eat vegetables. || unwilling to cook at home. || uninterested in gardening. >> Students became more willing to try unfamiliar foods.

P: Ancient Polynesian navigators crossed vast stretches of the Pacific without instruments. They read the positions of stars, the direction and shape of ocean swells, and the flight paths of seabirds, which head out to sea in the morning and return to land at dusk. By combining these clues, navigators could locate islands far beyond the horizon.
CI:: || Polynesian navigators found distant islands by combining clues from stars, swells, and seabirds. || Polynesian navigators relied on modern instruments. || Seabirds always fly away from land at dusk. || Navigators could not travel beyond sight of land. >> Multiple natural clues guided voyages.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It lists the natural clues navigators used. || It explains why Polynesians began voyaging. || It describes the construction of canoes. || It contradicts the first sentence. >> Stars, swells, and seabirds.
IN: Based on the text, a navigator who saw seabirds flying in a certain direction at dusk would most likely conclude that || land lay in that direction. || a storm was approaching. || the birds were heading out to sea. || the canoe was sailing away from land. >> Seabirds "return to land at dusk."

P: Researchers found that people shopping online tend to buy more when a website shows how many other people have recently purchased an item. When the counter was removed from one site, sales of those items fell modestly. The researchers suggest that people use others' choices as a shortcut when they are uncertain about what to buy.
CI:: || Showing how many others bought an item appears to increase purchases because shoppers use others' choices as guidance. || Online shoppers ignore information about other buyers. || Removing purchase counters increased sales. || Shoppers prefer items that no one else has bought. >> Sales fell when the counter was removed.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It provides evidence supporting the pattern described in the first sentence. || It explains why websites add counters. || It suggests that counters have no effect. || It describes how items are shipped. >> Removing the counter reduced sales.
IN: Based on the text, purchase counters would most likely have the greatest effect when shoppers || are unsure which product to choose. || already know exactly what they want. || are buying items they have purchased before. || shop in physical stores. >> People use others' choices "when they are uncertain."

P: The following text is from a short story. The lighthouse keeper had not spoken to another person in three weeks when the supply boat arrived. He had rehearsed what he would say: news about the storms, a request for more lamp oil. But when the young sailor jumped onto the dock and said hello, the keeper found that all he wanted was to hear the boy talk, about anything at all.
CI:: || After weeks alone, the lighthouse keeper discovers that he longs simply for conversation. || The lighthouse keeper refuses to speak to the sailor. || The sailor brings news that the lighthouse will close. || The keeper forgets to request lamp oil because he is angry. >> He wants "to hear the boy talk, about anything at all."
TS: Which choice best describes the function of the second sentence in the text as a whole? || It describes the keeper's practical plans, which contrast with what he actually wants. || It explains why the keeper lives alone. || It describes the supply boat. || It reveals the keeper's age. >> Rehearsed topics contrast with his desire for simple talk.
IN: Based on the text, the keeper's reaction most likely reflects || the loneliness of his long isolation. || his dislike of the young sailor. || his worry about the storms. || his lack of interest in supplies. >> Three weeks without speaking to anyone.

P: A tech company tested two versions of a sign-up page. One asked visitors for their name, email, phone number, and address. The other asked only for an email address. The shorter form had nearly twice as many sign-ups. The company concluded that each additional request for information discourages some visitors from completing the process.
CI:: || A sign-up page that requested less information attracted far more sign-ups. || Visitors preferred longer sign-up forms. || Asking for phone numbers increased sign-ups. || The company removed its sign-up page. >> The shorter form nearly doubled sign-ups.
TS: Which choice best describes the overall structure of the text? || It describes a test comparing two options, reports the result, and states a conclusion. || It explains how to design websites. || It compares two companies. || It argues that email is outdated. >> Two versions, result, and conclusion.
IN: Based on the text, a company that wanted more newsletter sign-ups would most likely benefit from || requesting only the information it truly needs. || adding more required questions. || requiring visitors to create passwords first. || hiding the sign-up form. >> Each additional request discourages visitors.

P: Early astronomers noticed that the planet Mars sometimes appeared to move backward across the sky for several weeks before resuming its usual direction. Some explained this with complex systems of circles within circles. The motion is now understood as an effect of perspective: Earth, moving faster in its orbit, periodically overtakes Mars, making Mars appear to slip backward.
CI:: || Mars's apparent backward motion is an illusion caused by Earth overtaking it in orbit. || Mars actually reverses direction in its orbit. || Early astronomers never noticed Mars's motion. || Earth moves more slowly than Mars. >> The apparent reversal is a perspective effect.
TS: Which choice best describes the overall structure of the text? || It describes a puzzling observation, an early explanation, and the modern explanation. || It compares Mars and Venus. || It describes how telescopes work. || It argues that early astronomers were correct. >> Observation, circles within circles, and perspective.
IN: Based on the text, a similar backward motion might be observed for another planet if || Earth passed it while both orbited the Sun. || the planet stopped orbiting. || Earth moved more slowly than the planet. || the planet were closer to Earth than the Moon. >> The effect results from Earth overtaking a planet.

P: When a museum added benches to its galleries, curators noticed that visitors spent more time looking at individual artworks. Before, most people walked past paintings quickly while standing. With a place to sit, visitors often stayed in front of a single piece for several minutes, and some reported noticing details they would otherwise have missed.
CI:: || Adding benches in galleries led museum visitors to spend more time looking closely at artworks. || Visitors spent less time in galleries after benches were added. || Benches were removed because visitors complained. || Visitors preferred standing while viewing art. >> Sitting encouraged longer, closer viewing.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It describes visitors' behavior before the change, for comparison. || It explains how the benches were designed. || It describes the museum's most famous painting. || It argues that museums should remove paintings. >> Walking past quickly contrasts with sitting and looking.
IN: Based on the text, visitors noticed more details most likely because they || could comfortably look at a work for a longer time. || were given magnifying glasses. || were required to take notes. || visited fewer galleries. >> Seating allowed them to stay several minutes.

P: Salmon that hatch in rivers spend years in the ocean before returning to spawn. When they die after spawning, their bodies decompose along riverbanks. Scientists have found traces of ocean nitrogen in streamside trees, delivered by salmon carcasses dragged into the forest by bears. The fish, in effect, carry nutrients from the sea into the forest.
CI:: || Salmon returning from the ocean deliver marine nutrients to forests when their carcasses decompose near rivers. || Trees near rivers absorb nitrogen only from rainfall. || Bears prevent salmon from reaching rivers. || Salmon spend their entire lives in rivers. >> Ocean nitrogen appears in trees via salmon carcasses.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It summarizes the significance of the process described. || It introduces a new animal. || It contradicts the evidence about nitrogen. || It explains how bears catch salmon. >> Salmon carry sea nutrients into the forest.
IN: Based on the text, a decline in salmon returning to a river would most likely || reduce the marine nutrients reaching nearby forests. || increase nitrogen in streamside trees. || have no effect on the forest. || cause bears to plant more trees. >> Fewer carcasses means fewer delivered nutrients.

P: The following text is from a memoir. My grandmother never threw anything away. Jars held buttons, rubber bands, and bits of string. As a teenager I found this embarrassing. Then, during a week-long power outage, our neighbors came to her door one by one, asking for candles, batteries, a length of wire, a spare key. She had everything. She handed it all over with a small, satisfied smile.
CI:: || The grandmother's habit of saving things, once embarrassing to the narrator, proves valuable during a power outage. || The grandmother throws away old items before the outage. || The neighbors refuse to accept the grandmother's help. || The narrator organizes the grandmother's belongings. >> Saved items help neighbors during the outage.
TS: Which choice best describes the function of the sentence "As a teenager I found this embarrassing" in the text? || It presents the narrator's earlier attitude, which the later events challenge. || It explains why the grandmother saved items. || It describes the power outage. || It shows the neighbors' opinion of the grandmother. >> Embarrassment gives way to appreciation.
IN: Based on the text, the grandmother's "small, satisfied smile" most likely suggests that she || felt her habit had been proven worthwhile. || was annoyed by the neighbors' requests. || wanted the neighbors to pay her. || was embarrassed by her collection. >> Her saving habit was vindicated.

P: Engineers designing bridges in earthquake zones once focused on making structures as rigid as possible. Newer designs often include flexible bearings and dampers that allow parts of a bridge to move slightly during shaking. By absorbing energy rather than resisting it, these features can reduce damage to the main structure.
CI:: || Newer earthquake-resistant bridges use flexible parts that absorb energy, reducing structural damage. || Bridges in earthquake zones should be completely rigid. || Flexible bearings make bridges more likely to collapse. || Earthquakes do not affect bridges. >> Absorbing energy reduces damage.
TS: Which choice best describes the overall structure of the text? || It contrasts an older design approach with a newer one and explains the newer approach's advantage. || It describes a famous bridge collapse. || It compares bridges with tunnels. || It lists materials used in bridges. >> Rigid versus flexible designs.
IN: Based on the text, a completely rigid bridge would most likely || have to resist earthquake forces rather than absorb them. || move easily during shaking. || require dampers to remain rigid. || be immune to earthquake damage. >> Rigidity resists rather than absorbs energy.

P: Linguists recording conversations noticed that speakers often pause briefly before important or unexpected words. Listeners, in experiments, were better at remembering words that followed such pauses. The researchers suggest that pauses may help listeners by signaling that something worth attention is coming.
CI:: || Brief pauses before important words may help listeners remember those words by signaling their significance. || Pauses make speech harder to understand. || Speakers never pause during conversations. || Listeners remember words that come before pauses best. >> Words after pauses were remembered better.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It offers an explanation for the findings described earlier. || It describes how conversations were recorded. || It contradicts the experimental results. || It lists the words used in the experiment. >> Pauses may signal importance.
IN: Based on the text, a teacher who wanted students to remember a key term might || pause briefly before saying it. || say it as quickly as possible. || avoid pausing during the lesson. || say it only in writing. >> Pauses improved memory for following words.

P: For decades, a small town's annual fair featured a pie contest judged by the same three residents. When the organizers began inviting judges from neighboring towns, several longtime participants worried that outsiders would not appreciate local recipes. Instead, entries increased, and a pie made with a rarely used local fruit won first prize for the first time, drawing new attention to the fruit.
CI:: || Bringing in outside judges increased participation and led to recognition of a local fruit in a town's pie contest. || The pie contest ended after outside judges were invited. || Local recipes were ignored by the new judges. || Longtime participants stopped entering the contest. >> Entries rose, and a local-fruit pie won.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It presents a worry that the outcome described in the final sentence did not support. || It describes the pies entered in the contest. || It explains why the fair was founded. || It lists the judges' names. >> Fears about outsiders were not borne out.
IN: Based on the text, the winning pie most likely drew attention to the local fruit because || few people had used the fruit in contest entries before. || the fruit was imported from another country. || the judges were growers of the fruit. || the fruit was banned from the contest. >> It was a "rarely used local fruit."

P: Scientists studying why zebras have stripes tested several ideas. When horses wore striped coats, biting flies landed on them far less often than on horses wearing solid-colored coats, although flies still approached. The researchers suggest that stripes may confuse flies as they try to land, which could help zebras avoid insect-borne diseases.
CI:: || Experiments suggest that stripes may help protect animals from biting flies by making landing difficult. || Stripes attract biting flies. || Horses in striped coats were bitten more often. || Flies cannot see striped patterns. >> Flies approached but landed less on stripes.
TS: Which choice best describes the function of the phrase "although flies still approached" in the text? || It clarifies that stripes interfered with landing rather than keeping flies away entirely. || It shows that the experiment failed. || It explains how the coats were made. || It suggests that flies prefer solid colors. >> Flies came near but struggled to land.
IN: Based on the text, zebras' stripes would be most beneficial in regions where || biting flies spread diseases. || flies are absent. || zebras live in cold climates. || predators hunt at night. >> Stripes may help avoid "insect-borne diseases."

P: A city experimented with "complete streets," redesigning several roads to include wider sidewalks, bike lanes, and crosswalks with shorter crossing distances. Some drivers predicted longer commutes. Travel times for cars increased only slightly, while the number of pedestrians and cyclists on those streets rose substantially, and serious crashes declined.
CI:: || Redesigning streets for all users slightly increased car travel times while increasing walking and cycling and reducing serious crashes. || Car travel times doubled after the redesign. || Fewer people walked on the redesigned streets. || Serious crashes increased after the redesign. >> Small car delays, more walking and cycling, fewer crashes.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It presents a prediction that proved only partly accurate. || It describes how bike lanes were painted. || It explains why the city chose those streets. || It summarizes the results of the redesign. >> Commutes lengthened "only slightly."
IN: Based on the text, city officials would most likely view the redesign as || largely successful, given its safety and mobility benefits. || a failure that should be reversed. || irrelevant to pedestrians. || harmful to cyclists. >> Benefits outweighed a small increase in travel time.

P: The following text is from a poem. The old bridge knows the river's moods: / the spring flood's rushing rage, / the summer's lazy silver hum, / the winter's frozen stage. / It does not fight the water, / it simply holds its ground, / and lets each season pass beneath / without a single sound.
CI:: || The poem describes a bridge that endures the river's changing seasons calmly and steadily. || The poem describes a bridge destroyed by a flood. || The speaker complains about the river's noise. || The poem compares two bridges over the same river. >> The bridge "holds its ground" through every season.
TS: Which choice best describes the overall structure of the poem? || It lists the river's seasonal changes and then describes the bridge's steady response. || It narrates the construction of the bridge. || It compares a river with an ocean. || It describes a journey across the bridge. >> Seasons first, then the bridge's endurance.
IN: Based on the text, the bridge is presented as || patient and resilient. || fragile and fearful. || constantly changing. || in conflict with the river. >> It "does not fight" yet "holds its ground."

P: Researchers studying how people read food labels used eye-tracking devices and found that most shoppers looked at the calorie count and the price but rarely read the ingredient list. When the ingredient list was moved to the front of the package and printed in larger type, shoppers were far more likely to read it.
CI:: || Shoppers rarely read ingredient lists unless the lists are made more prominent on packages. || Shoppers always read ingredient lists carefully. || Moving ingredient lists reduced how often they were read. || Shoppers ignore calorie counts. >> Prominent placement increased reading.
TS: Which choice best describes the overall structure of the text? || It describes a pattern in shoppers' behavior and then a change that altered it. || It explains how eye-tracking devices are built. || It compares the prices of several foods. || It argues that calorie counts should be removed. >> Rarely read lists, then prominent lists read more.
IN: Based on the text, the placement and size of information on packages most likely || influence whether shoppers notice it. || have no effect on shoppers. || matter only for prices. || make shoppers less likely to buy food. >> Moving and enlarging the list increased reading.

P: Many desert plants have waxy coatings on their leaves. The wax reduces water loss by sealing the leaf surface. Some plants in rain forests also have waxy leaves, but for a different reason: the slick surface helps rainwater run off quickly, preventing mold and algae from growing on the leaves.
CI:: || Waxy leaf coatings serve different purposes in different environments, reducing water loss in deserts and shedding water in rain forests. || Waxy leaves are found only in deserts. || Rain forest plants use wax to store water. || Waxy coatings increase water loss. >> The same trait serves different functions.
TS: Which choice best describes the overall structure of the text? || It describes a trait in one environment and then explains how the same trait serves a different purpose elsewhere. || It explains how wax is produced. || It compares deserts and oceans. || It argues that rain forest plants should grow in deserts. >> Desert purpose, then rain forest purpose.
IN: Based on the text, a rain forest leaf without a waxy coating would most likely || stay wet longer and be more likely to grow mold or algae. || lose water faster in dry air. || be immune to mold. || shed rain more quickly. >> Wax helps water run off, preventing growth.

P: When a regional newspaper began publishing weekly articles written by high school students about their communities, editors expected little interest from adult readers. Instead, the student articles were among the most read on the paper's website, and several local officials cited them at public meetings as helpful views of issues they had overlooked.
CI:: || Articles by high school students proved popular with adult readers and influenced local officials. || Adult readers ignored the student articles. || The newspaper stopped publishing student articles. || Local officials criticized the students for writing articles. >> High readership and citations by officials.
TS: Which choice best describes the function of the first clause, "editors expected little interest from adult readers," in the text? || It establishes an expectation that the results contradicted. || It explains why students wrote the articles. || It describes the newspaper's history. || It summarizes officials' reactions. >> Low expectations contrast with high readership.
IN: Based on the text, local officials valued the student articles most likely because they || offered perspectives on issues the officials had not fully considered. || were written by professional journalists. || agreed with every decision officials made. || were published only in print. >> They were "helpful views of issues they had overlooked."

P: Scientists once thought that adult brains could not produce new neurons. Studies of songbirds, and later of mammals, found evidence that new neurons form in certain brain regions throughout life. In some animals, the formation of new neurons increased with learning and exercise, though researchers continue to debate how much this occurs in adult humans.
CI:: || Evidence shows that some adult brains produce new neurons, though the extent in humans is still debated. || Adult brains can never produce new neurons. || Exercise prevents the formation of new neurons. || Scientists agree that adult humans produce many new neurons. >> Evidence of neurogenesis, with human extent debated.
TS: Which choice best describes the function of the final clause, beginning with "though," in the text? || It notes an unresolved question about the findings. || It proves that humans form many new neurons. || It describes how songbirds learn. || It explains why scientists held the earlier belief. >> Human extent remains debated.
IN: Based on the text, scientists would most likely want further research to determine || how much new neuron formation occurs in adult humans. || whether songbirds can sing. || whether exercise exists. || whether the brain has neurons at all. >> The human question "continue[s] to be debated."

P: The following text is from a novel. Marco had lived above the bakery for ten years and had long since stopped noticing the smell of bread. Then he spent a month traveling for work. On the night he returned, he climbed the stairs, opened his door, and stopped, overwhelmed by the warm scent of yeast and butter drifting up through the floorboards, as though the building itself were welcoming him home.
CI:: || After being away, Marco notices again the familiar smell of bread that makes his home feel welcoming. || Marco moves away from the bakery permanently. || Marco dislikes the smell of bread. || The bakery closed while Marco was traveling. >> Time away renews his awareness of the scent.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It establishes that Marco had grown used to the smell, which makes his later reaction meaningful. || It explains why Marco traveled for work. || It describes the bakery's menu. || It reveals that Marco owns the bakery. >> He "had long since stopped noticing" the smell.
IN: Based on the text, Marco notices the smell on his return most likely because || being away made the familiar scent new to him again. || the bakery had started baking a new kind of bread. || he had never smelled bread before. || the floorboards had been removed. >> A month away renewed his awareness.
"""
