"""Passage units, batch 4 (format documented in passage_data1.py). Original texts; people and studies are illustrative."""

UNITS = """
P: Sea levels were far lower during the last ice age, when enormous amounts of water were locked in glaciers. Areas that are now shallow seas were once dry land. Archaeologists have begun searching these submerged landscapes with sonar and divers, and they have found stone tools and the remains of hearths beneath the seafloor. Such discoveries suggest that some early human settlements now lie underwater, which may explain gaps in the archaeological record on land.
CI:: || Evidence of early human activity on land now covered by the sea may help fill gaps in the archaeological record. || Early humans lived only in areas that are still dry land today. || Sea levels were higher during the last ice age than they are now. || Archaeologists have stopped searching for settlements on land. >> Tools and hearths under the seafloor suggest some settlements are now submerged.
TS: Which choice best describes the function of the first two sentences in the text as a whole? || They explain why land that people once lived on is now underwater. || They describe the tools that archaeologists use. || They present a claim that the rest of the text disputes. || They explain why hearths were built near the sea. >> Lower sea levels made now-submerged areas dry land.
IN: Based on the text, the "gaps in the archaeological record on land" most likely refer to || periods or places where evidence of human activity has been hard to find. || damaged tools stored in museums. || disagreements among archaeologists about sonar. || areas where glaciers never formed. >> Missing evidence may lie underwater.

P: The following text is from a novel. Every Saturday, Rafael's grandmother made tamales, and every Saturday she refused to write down the recipe. "It's in my hands," she would say, holding them up, dusted with masa. So Rafael began standing beside her, watching how much she scooped, how long she kneaded, and how she folded each husk. Years later, in his own kitchen, he realized that the recipe had become his hands too.
CI:: || By watching his grandmother closely over time, Rafael learns a family recipe that was never written down. || Rafael's grandmother writes down her recipe so that he can learn it. || Rafael dislikes cooking tamales with his grandmother. || Rafael forgets how to make tamales after his grandmother stops cooking. >> He learns by watching, and the recipe "had become his hands too."
TS: Which choice best describes the function of the final sentence in the text as a whole? || It shows that Rafael has absorbed the knowledge his grandmother described as being "in my hands." || It explains why Rafael's grandmother refused to write down the recipe. || It describes a disagreement between Rafael and his grandmother. || It reveals that Rafael has lost the recipe. >> It echoes her words, showing the skill has passed to him.
IN: Based on the text, the grandmother's statement "It's in my hands" most likely means that || her knowledge of the recipe comes from practice rather than written instructions. || she has hurt her hands while cooking. || she keeps the recipe hidden in her apron. || she wants Rafael to find a written recipe elsewhere. >> She knows it by feel and experience.

P: Researchers wondered whether dogs understand where a person is pointing or simply follow the movement of a hand. In one test, a researcher pointed at one of two cups while standing still, then lowered her arm before the dog was released. Most dogs still went to the indicated cup, even though the arm was no longer moving or extended. The results suggest that dogs interpret pointing as a signal about a location, not merely as a motion to follow.
CI:: || An experiment suggests that dogs understand pointing as indicating a location rather than just following hand movements. || Dogs ignore people who point at objects. || Dogs can find hidden food only by smell. || Dogs follow any moving object regardless of where it points. >> Dogs chose the indicated cup even after the arm was lowered.
TS: Which choice best describes the overall structure of the text? || It poses a question, describes a test designed to answer it, and states what the results suggest. || It compares several breeds of dog. || It describes how to train a dog to find hidden objects. || It argues that dogs are smarter than all other animals. >> Question, experimental design, result, and conclusion.
IN: Based on the text, lowering the arm before releasing the dog was important because it || removed the possibility that dogs were simply following a moving or extended arm. || made it easier for dogs to smell the food. || tested whether dogs could see the researcher. || encouraged dogs to ignore the cups. >> It separated understanding from simply tracking motion.

P: When the price of a city's public transit passes was cut in half for residents over sixty-five, officials expected ridership among older residents to rise modestly. It nearly doubled. Surveys revealed that many older residents had wanted to use transit more but had been deterred by cost. Several also reported visiting friends, libraries, and parks more often, suggesting that the policy affected not only transportation but also social life.
CI:: || Cutting transit fares for older residents greatly increased their ridership and appeared to broaden their social activities. || Older residents stopped using public transit after the price change. || The city doubled transit fares for residents over sixty-five. || Most older residents already used transit as much as they wanted. >> Ridership nearly doubled, and residents reported visiting people and places more often.
TS: Which choice best describes the function of the sentence "It nearly doubled" in the text? || It shows that the actual result far exceeded officials' expectations. || It describes how officials planned the policy. || It indicates that the policy failed. || It explains why transit passes were expensive. >> Officials expected a modest rise.
IN: Based on the text, before the price cut, cost had most likely || kept some older residents from using transit as often as they wished. || encouraged older residents to ride transit more. || had no effect on how often older residents traveled. || caused older residents to buy cars. >> Many "had been deterred by cost."

P: Most spiders have eight eyes, but their eyesight varies widely. Web-building spiders often see poorly and sense prey mainly through vibrations in their silk. Jumping spiders, which hunt without webs, have large forward-facing eyes that give them some of the sharpest vision among small animals. This contrast suggests that a spider's hunting method is closely linked to how much it relies on sight.
CI:: || Differences in spiders' eyesight appear to be tied to how they catch prey. || All spiders have excellent eyesight. || Jumping spiders build larger webs than other spiders. || Web-building spiders hunt by chasing prey across the ground. >> Web builders rely on vibrations, and jumping spiders rely on sharp vision.
TS: Which choice best describes the overall structure of the text? || It notes that spiders' vision varies, contrasts two types of spiders, and draws a conclusion from the contrast. || It describes the life cycle of a single spider species. || It explains how spiders build webs step by step. || It argues that spiders should be protected. >> Variation, two contrasting examples, and a conclusion.
IN: Based on the text, a spider that stalks and pounces on insects would most likely || have relatively sharp vision. || rely entirely on vibrations in silk. || have fewer than eight eyes. || build large webs. >> Hunting without webs is linked to sharp eyesight.

P: The following text is adapted from an essay about walking. I used to measure a walk by its destination: the store, the office, the train. Then an injury took away my car for a season, and I began walking everywhere, slowly. I learned which porch held a sleeping cat, which corner smelled of bread at seven, which tree dropped its leaves first. The destinations were the same, but the walks had become places in themselves.
CI:: || Walking slowly out of necessity taught the writer to value the journey itself, not just the destination. || The writer dislikes walking and prefers driving. || The writer moved to a new neighborhood after an injury. || The writer's walks became shorter after the injury. >> The walks "had become places in themselves."
TS: Which choice best describes the overall structure of the text? || It describes the writer's earlier view, an event that changed it, and the new perspective that resulted. || It gives directions to several locations in a town. || It compares walking with cycling. || It explains how the writer recovered from an injury. >> Old view (destination), injury, and new appreciation.
IN: Based on the text, the details about the cat, the bread, and the tree mainly show that the writer || began noticing small features of the route. || had moved to a farm. || walked only early in the morning. || wanted to find a faster route. >> They illustrate the attention gained by walking slowly.

P: Many people assume that the Great Pyramid's builders used slaves forced to work under harsh conditions. Excavations near the pyramid, however, have uncovered workers' villages with bakeries, breweries, and cemeteries where laborers were buried with bread and beer for the afterlife. Some skeletons show healed injuries that suggest the workers received medical care. These findings have led many archaeologists to conclude that the builders were paid laborers who were respected for their work.
CI:: || Archaeological evidence suggests that the Great Pyramid's builders were paid, respected workers rather than slaves. || The Great Pyramid was built entirely by slaves. || Workers near the pyramid had no access to food or medical care. || Archaeologists have found no evidence about the pyramid's builders. >> Villages, burials, and healed injuries support the paid-laborer view.
TS: Which choice best describes the function of the second and third sentences in the text as a whole? || They present evidence that challenges the assumption described in the first sentence. || They describe how the pyramid was built. || They support the assumption described in the first sentence. || They explain why the pyramid was built. >> Bakeries, respectful burials, and medical care contradict the slave assumption.
IN: Based on the text, workers being buried with bread and beer most likely suggests that || they were treated with a degree of respect. || they were punished after death. || bread and beer were rare in the region. || they did not work on the pyramid. >> Burial offerings indicate respect.

P: A company that makes running shoes gave one group of runners shoes with thick cushioning and another group shoes with minimal cushioning. After six months, the two groups reported similar rates of injury. However, runners in each group tended to change how their feet struck the ground: those in minimal shoes landed more lightly on the middle of the foot, while those in cushioned shoes more often landed on the heel. The researchers suggested that runners may adapt their stride to their shoes.
CI:: || Runners in shoes with different cushioning had similar injury rates but appeared to adjust their stride to their footwear. || Cushioned shoes greatly reduced injuries compared with minimal shoes. || Runners in minimal shoes were injured far more often. || The type of shoe had no effect on how runners' feet struck the ground. >> Injury rates matched, but foot strike patterns differed.
TS: Which choice best describes the function of the third sentence in the text as a whole? || It describes a difference between the groups that the injury data did not reveal. || It explains how injuries were measured. || It contradicts the conclusion in the final sentence. || It describes how the shoes were manufactured. >> "However" introduces differences in stride.
IN: Based on the text, a runner switching from cushioned to minimal shoes would most likely || begin landing more lightly on the middle of the foot. || stop running altogether. || become injured more often. || land harder on the heel. >> Runners in minimal shoes landed "more lightly on the middle of the foot."

P: The following text is from a short story. For weeks, Mei had avoided the old man who sold newspapers outside the station, embarrassed by her halting attempts at the language. One morning she was a coin short. Before she could apologize, he waved his hand, pressed the paper into hers, and pointed at a headline, slowly pronouncing each word. She repeated them after him. The next morning, she stopped at his stand on purpose.
CI:: || An act of kindness from a newspaper seller helps Mei overcome her embarrassment about speaking a new language. || Mei stops buying newspapers because she cannot afford them. || The newspaper seller refuses to sell Mei a paper. || Mei teaches the newspaper seller a new language. >> He helps her and practices words with her; she then visits "on purpose."
TS: Which choice best describes the function of the final sentence in the text as a whole? || It shows that Mei's attitude toward the seller has changed. || It explains why Mei was a coin short. || It describes the headline Mei read. || It reveals that the seller has moved away. >> She once avoided him but now seeks him out.
IN: Based on the text, Mei had avoided the newspaper seller mainly because she || felt self-conscious about her difficulty speaking the language. || disliked the newspapers he sold. || believed he charged too much. || was always late for her train. >> She was "embarrassed by her halting attempts at the language."

P: Scientists once thought that the deep ocean floor was nearly lifeless, too dark and cold to support much activity. Then researchers exploring volcanic vents discovered thriving communities of giant tube worms, clams, and shrimp. These animals depend not on sunlight but on bacteria that draw energy from chemicals released by the vents. The discovery showed that life can flourish in conditions once considered impossible.
CI:: || The discovery of life around deep-sea vents showed that ecosystems can thrive without sunlight. || The deep ocean floor contains no living things. || Tube worms need sunlight to survive. || Volcanic vents are found only in shallow water. >> Vent communities rely on chemical energy rather than sunlight.
TS: Which choice best describes the overall structure of the text? || It describes an earlier belief, presents a discovery that contradicted it, and explains the discovery's significance. || It explains how volcanic vents form. || It lists the animals found in shallow reefs. || It describes a debate that remains unresolved. >> Old belief, vent discovery, and broader significance.
IN: Based on the text, the bacteria at the vents are important to the other animals because they || provide a source of energy that does not depend on sunlight. || keep the water warm. || protect the animals from predators. || block chemicals released by the vents. >> Animals depend on bacteria that "draw energy from chemicals."

P: When a large bookstore chain opened near a small independent bookshop, many predicted that the smaller store would close within a year. Instead, the owner began hosting weekly author readings, a children's story hour, and a book club that met in the shop after hours. Sales of new books dipped slightly, but sales of books connected to events rose, and the shop celebrated its twentieth anniversary a decade later.
CI:: || An independent bookshop survived competition from a large chain by building a community around events. || The independent bookshop closed soon after the chain store opened. || The chain store began hosting author readings to compete. || The independent bookshop stopped selling new books. >> Events built community and supported sales.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It presents a prediction that the rest of the text shows to be wrong. || It explains why the chain store chose that location. || It describes the history of the independent shop. || It summarizes the shop's anniversary celebration. >> Many predicted closure; instead the shop thrived.
IN: Based on the text, the shop's events most likely helped it by || giving customers reasons to visit that the chain store did not offer. || lowering the prices of all its books. || replacing book sales entirely. || attracting the chain store's employees. >> Event-related sales rose while the shop built a community.

P: Some bird species are known to use the sun and stars to navigate, but a study of young songbirds raised indoors suggests that they may also inherit a sense of direction. Birds that had never migrated and had never seen the sky still became restless and tried to fly in the correct migratory direction at the right time of year. The researchers propose that young birds may be born with a rough compass that experience later refines.
CI:: || Young songbirds raised without seeing the sky still oriented in the correct migratory direction, suggesting an inborn sense of direction. || Songbirds must see the stars before they can navigate. || Birds raised indoors never try to migrate. || Adult birds teach young birds which direction to fly. >> Birds with no experience still faced the right direction.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It offers an interpretation of the behavior described in the previous sentence. || It describes how the birds were raised. || It contradicts the study's findings. || It explains how birds use the stars. >> The inborn-compass idea explains the birds' orientation.
IN: Based on the text, the phrase "that experience later refines" suggests that || birds' navigation likely becomes more accurate as they gain experience migrating. || birds lose their sense of direction as they age. || experience is unnecessary for navigation. || birds raised indoors can never migrate successfully. >> An inborn rough compass becomes more precise with experience.

P: The following text is from a memoir. My first job was washing dishes in a busy diner. I thought of it only as a way to earn money for a bicycle. But the cook, a woman named Dolores, noticed me watching her flip eggs and began teaching me during slow hours: how to crack an egg with one hand, how to tell by sound when the oil was hot. Thirty years and two restaurants later, I still crack eggs the way she taught me.
CI:: || A dishwashing job the narrator took for money led to lessons that shaped a lifelong career in cooking. || The narrator never learned to cook. || Dolores refused to teach the narrator. || The narrator used the job to save for a car. >> Dolores's lessons led to a career in restaurants.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It presents the narrator's limited view of the job, which later events change. || It describes Dolores's cooking techniques. || It explains how the narrator opened a restaurant. || It suggests that the narrator disliked Dolores. >> "Only a way to earn money" contrasts with what the job became.
IN: Based on the text, Dolores began teaching the narrator most likely because she || noticed the narrator's interest in cooking. || needed someone to replace her immediately. || was asked to by the diner's owner. || wanted the narrator to stop washing dishes. >> She "noticed me watching her flip eggs."

P: Roads built through forests can divide wildlife habitats, making it dangerous for animals to cross. In one mountain region, engineers built bridges covered with soil and native plants over a busy highway. Motion cameras showed deer, bears, and even small mammals using the crossings regularly. Collisions between vehicles and large animals on that stretch of highway dropped by more than eighty percent.
CI:: || Vegetated bridges over a highway allowed animals to cross safely and greatly reduced collisions with vehicles. || Animals avoided the bridges built over the highway. || The highway was closed to protect wildlife. || Collisions between vehicles and animals increased after the bridges were built. >> Cameras showed frequent use, and collisions dropped sharply.
TS: Which choice best describes the overall structure of the text? || It describes a problem, a solution that was tried, and evidence of the solution's success. || It compares highways in two countries. || It explains how motion cameras work. || It describes the habitats of several animals. >> Divided habitats, bridges, and camera and collision data.
IN: Based on the text, the bridges were covered with soil and native plants most likely to || make the crossings resemble the animals' natural habitat. || make the bridges easier for cars to use. || reduce the cost of building them. || prevent animals from using them. >> Natural cover would encourage wildlife to cross.

P: A researcher analyzing thousands of restaurant reviews noticed that reviewers used different words depending on price. In reviews of expensive restaurants, words associated with long, complex descriptions appeared more often, while reviews of inexpensive places more often compared food to comforting or addictive things. The researcher suggests that people may describe food partly to signal something about themselves, not only to describe the meal.
CI:: || An analysis of restaurant reviews suggests that the language people use to describe food may reflect how they want to present themselves. || Expensive restaurants always serve better food than inexpensive ones. || Reviewers use exactly the same words for all restaurants. || Restaurant reviews are mostly written by chefs. >> Word choices varied with price, suggesting self-presentation.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It gives specific examples of the pattern mentioned in the first sentence. || It explains how the reviews were collected. || It presents a finding that contradicts the first sentence. || It describes the researcher's favorite restaurant. >> It details how word choice differed by price.
IN: Based on the text, the researcher would most likely agree that a restaurant review || can reveal information about its writer as well as about the food. || describes only the food and nothing else. || is always written to criticize a restaurant. || is more accurate when the meal is expensive. >> People may describe food "to signal something about themselves."

P: The following text is from a poem. My grandfather's hands were maps of work, / the knuckles hills, the scars like rivers crossed. / He never told me where he'd been, / but I could read it there: / the rope burns of the fishing years, / the calluses from building walls, / the pale half-moon a saw once carved / the winter the barn was raised.
CI:: || The speaker learns about the grandfather's life by reading the marks of work on his hands. || The speaker's grandfather often told stories about his travels. || The speaker describes a map of the town where the grandfather lived. || The speaker's grandfather worked only as a fisherman. >> The hands reveal his history even though he "never told."
TS: Which choice best describes how the poem develops its central comparison? || It compares the grandfather's hands to maps and then identifies specific marks that record his experiences. || It compares the grandfather to a river and describes a journey. || It compares two people's hands and judges which worked harder. || It describes a barn and then explains how it was built. >> "Maps of work," followed by rope burns, calluses, and a scar.
IN: Based on the text, the "pale half-moon" is most likely || a scar from an injury the grandfather received while building a barn. || a birthmark the grandfather has had since childhood. || a drawing on one of the grandfather's maps. || a tattoo of the moon. >> A saw "carved" it "the winter the barn was raised."

P: Many schools ban phones in classrooms, arguing that the devices distract students. One district tested a policy requiring students to store phones in lockers during the school day. Over a year, teachers reported fewer interruptions and students' test scores rose slightly, with the largest gains among students who had previously struggled. Some students, however, reported feeling anxious without access to their phones, especially in the first weeks.
CI:: || A district's phone storage policy was linked to fewer interruptions and modest score gains, though some students initially felt anxious. || Banning phones caused test scores to fall sharply. || Students unanimously supported the phone policy. || Teachers reported more interruptions after the policy began. >> Benefits and a drawback are both reported.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It presents a drawback that complicates the policy's otherwise positive results. || It explains why the district adopted the policy. || It summarizes the test score gains. || It describes how phones were stored. >> "However" introduces student anxiety.
IN: Based on the text, the policy's benefits for test scores appeared to be || greatest for students who had been struggling. || limited to students who already had high scores. || entirely absent. || largest in the first few weeks. >> The largest gains were "among students who had previously struggled."

P: Paper was invented in China and spread gradually westward over many centuries. For much of that time, knowledge of papermaking was closely guarded. Historians note that papermaking reached new regions most often through trade routes and the movement of skilled workers, who brought their techniques with them. Once established, local paper mills made written records cheaper and far more common.
CI:: || Papermaking spread slowly through trade and skilled workers, and its arrival made written records more affordable and widespread. || Paper was invented simultaneously in many regions. || Papermaking techniques were freely shared from the beginning. || Paper made written records more expensive and rare. >> Spread via trade and workers; effects on records.
TS: Which choice best describes the overall structure of the text? || It traces how a technology spread and then describes one effect of that spread. || It describes how paper is made step by step. || It compares paper with other writing materials. || It argues that paper should replace digital records. >> Spread of papermaking, then cheaper and more common records.
IN: Based on the text, a region that received skilled papermakers along a trade route would most likely || soon begin producing paper locally. || stop keeping written records. || have no need for trade. || keep papermaking techniques completely secret. >> Techniques spread with the workers, leading to local mills.

P: Mangrove trees grow in salty coastal water, where most plants cannot survive. Some mangroves filter salt out at their roots, while others absorb salt and then push it out through their leaves, which can be seen coated with white crystals. Mangrove forests also protect shorelines by slowing waves with their dense, tangled roots.
CI:: || Mangroves have ways of coping with salt water and help protect coastlines. || Mangroves cannot survive in salt water. || All mangroves remove salt in exactly the same way. || Mangrove roots speed up waves along the shore. >> The text describes salt-handling methods and shoreline protection.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It describes different ways mangroves deal with the salt mentioned in the first sentence. || It explains why mangroves protect shorelines. || It compares mangroves with desert plants. || It questions whether mangroves really live in salt water. >> Filtering at roots or excreting through leaves.
IN: Based on the text, white crystals on a mangrove's leaves are most likely || salt that the tree has pushed out. || frost from cold weather. || a sign that the tree is diseased. || sand blown from the beach. >> Some mangroves "push it out through their leaves."

P: For decades, a popular brand of breakfast cereal was sold in a tall box. When the company switched to a shorter, wider box containing the same amount of cereal, shoppers complained that they were getting less. Sales dipped until the company printed the weight in large numbers on the front and added a line stating "Same amount, new shape." Sales then recovered.
CI:: || Shoppers mistakenly believed a reshaped cereal box contained less cereal until the company clearly displayed the weight. || The company reduced the amount of cereal in each box. || Shoppers preferred the new box shape from the start. || Sales rose immediately after the box changed shape. >> The shape change caused a false impression that labeling corrected.
TS: Which choice best describes the overall structure of the text? || It describes a change, a problem it caused, and how the problem was resolved. || It compares two cereal brands. || It explains how cereal is manufactured. || It argues that tall boxes are always better. >> New box, complaints and falling sales, and labeling that fixed it.
IN: Based on the text, shoppers likely thought they were getting less cereal because they || judged the amount by the box's height rather than its actual weight. || read the weight printed on the old box. || noticed that the price had increased. || tasted a difference in the cereal. >> The same amount in a shorter box seemed smaller.

P: The following text is from a novel. The storm had passed, but the town was silent. No cars, no radios, no hum of refrigerators. Luis walked outside and heard things he had never noticed: water dripping from the gutter in a steady rhythm, a dog barking three streets away, his neighbor laughing on her porch. He stood there a long time, listening to a town he thought he knew.
CI:: || The silence after a storm allows Luis to notice sounds in his town that he had never heard before. || Luis is frightened by the storm and stays inside. || Luis's neighbors are angry about the power outage. || Luis leaves town after the storm. >> Without ordinary noise, he hears new sounds.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It explains the absence of everyday noise that makes the new sounds noticeable. || It describes damage caused by the storm. || It introduces a conflict between Luis and his neighbor. || It lists the objects Luis owns. >> No cars, radios, or refrigerators.
IN: Based on the text, the phrase "a town he thought he knew" suggests that Luis || realizes there is more to his familiar town than he had noticed. || has just moved to the town. || plans to leave the town soon. || does not recognize his neighbor. >> He discovers unnoticed sounds in a familiar place.

P: Economists studying a coastal fishing town found that when the government set strict limits on how many fish each boat could catch, conflicts among fishers initially increased. Over time, however, fish populations recovered, catches became more predictable, and fishers' average incomes rose above their levels before the limits. Many fishers who had opposed the rules came to support them.
CI:: || Catch limits in a fishing town caused early conflict but eventually led to recovered fish populations, more stable catches, and higher incomes. || Catch limits permanently reduced fishers' incomes. || Fish populations declined after the limits were introduced. || Fishers unanimously supported the limits from the start. >> The limits were unpopular at first but produced long-term benefits.
TS: Which choice best describes the function of the word "however" in the text? || It signals a shift from the limits' early difficulties to their later benefits. || It introduces a reason the limits were created. || It indicates that the fish populations never recovered. || It contrasts the fishing town with other towns. >> Initial conflict, "however," recovery and higher incomes.
IN: Based on the text, many fishers most likely changed their view of the rules because || they saw the rules improve fish populations and their own incomes. || the government removed the rules. || conflicts among fishers increased over time. || they stopped fishing entirely. >> Benefits over time led opponents to support the rules.

P: Some ancient Roman concrete structures, such as harbor walls, have survived in seawater for nearly two thousand years, while many modern concrete structures crack within decades. Researchers analyzing samples found that seawater seeping into the Roman concrete reacted with volcanic ash in the mixture, forming new minerals that filled cracks and made the material stronger over time.
CI:: || Roman concrete has lasted in seawater partly because reactions with volcanic ash strengthened it over time. || Modern concrete lasts longer in seawater than Roman concrete. || Seawater weakens all types of concrete. || Roman builders avoided building near the sea. >> Seawater plus volcanic ash formed crack-filling minerals.
TS: Which choice best describes the overall structure of the text? || It notes a striking difference in durability and then explains what researchers found about its cause. || It describes how the Romans built harbors. || It argues that modern concrete should never be used. || It lists famous Roman buildings. >> Contrast in durability, then the mineral explanation.
IN: Based on the text, modern concrete intended for use in seawater might be improved by || including ingredients that react with seawater to form strengthening minerals. || removing all volcanic ash from the mixture. || keeping seawater from ever touching it. || making it thinner. >> The Roman mixture's reaction with seawater made it stronger.

P: When a city library began lending musical instruments, librarians expected mostly children to borrow them. The most frequent borrowers turned out to be adults who had played instruments decades earlier and wanted to see whether they could still play. Several formed a small band that now rehearses in a library meeting room every Thursday evening.
CI:: || A library's instrument-lending program unexpectedly drew many adults returning to music, some of whom formed a band. || Children were the only people who borrowed the library's instruments. || The library stopped lending instruments after one year. || Adults in the city had never played instruments before. >> Adults, not children, were the main borrowers, and some formed a band.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It states an expectation that the following sentences show was incorrect. || It explains how the library purchased instruments. || It describes the band's first performance. || It lists the instruments available to borrow. >> Librarians expected children; adults borrowed most.
IN: Based on the text, many adult borrowers were most likely motivated by || curiosity about whether they still had skills they had once developed. || a requirement from their employers. || a desire to sell the instruments. || the library's rule limiting instruments to adults. >> They "wanted to see whether they could still play."

P: The following text is adapted from a letter written by a young teacher in the early twentieth century. The schoolhouse has one room, one stove, and twenty-three children between the ages of six and fifteen. I teach all of them at once. The older ones help the younger with their letters, and I have come to believe they learn as much by teaching as by listening to me. Yesterday a boy of twelve explained long division to a girl of eight more clearly than I could have.
CI:: || The teacher observes that older students in her one-room school learn by helping younger students. || The teacher struggles to control a large class and plans to quit. || The school has separate rooms for each age group. || The older students refuse to help the younger ones. >> Older students teach younger ones, and the teacher believes they learn by teaching.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It gives an example supporting the teacher's belief about students learning by teaching. || It describes the schoolhouse's furnishings. || It explains why the teacher chose her profession. || It contradicts the teacher's earlier statement. >> The boy explaining division illustrates her point.
IN: Based on the text, the teacher's attitude toward the older students' help is best described as || appreciative. || resentful. || indifferent. || suspicious. >> She believes they learn from it and praises the boy's explanation.

P: Scientists studying elephants noticed that the animals sometimes gathered and stood still, lifting a foot or leaning forward, even when no other elephants were visible. Recordings revealed that elephants produce very low-frequency rumbles that travel through the ground over long distances. Experiments suggested that elephants can detect these vibrations through sensitive nerve endings in their feet, which may explain the unusual postures.
CI:: || Elephants may communicate over long distances with low-frequency rumbles that they detect through their feet. || Elephants lift their feet only when they are injured. || Elephants cannot hear sounds made by other elephants. || Low-frequency rumbles travel only through the air. >> Rumbles travel through the ground and may be sensed through the feet.
TS: Which choice best describes the overall structure of the text? || It describes a puzzling behavior, presents findings about elephant communication, and offers an explanation for the behavior. || It compares elephants with other large mammals. || It explains how scientists record animal sounds. || It describes an elephant herd's migration route. >> Puzzling postures, rumbles through the ground, and the foot-sensing explanation.
IN: Based on the text, an elephant leaning forward with a foot lifted is most likely || paying attention to vibrations from distant elephants. || preparing to charge at a predator. || resting because it is tired. || searching for food on the ground. >> The postures may relate to detecting ground vibrations.

P: Many museums keep only a small fraction of their collections on display, storing the rest in warehouses. One natural history museum decided to let visitors view part of its storage area through glass walls, where scientists could be seen cataloging specimens. Visitor surveys showed that many people found the working storage area more interesting than some traditional exhibits, because it showed how museum research is actually done.
CI:: || Visitors to a museum found a glass-walled storage area engaging because it revealed the museum's research work. || Museums display nearly all of their collections at all times. || Visitors complained that the storage area was boring. || The museum closed its traditional exhibits. >> Surveys showed interest in seeing research in action.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It provides background that explains why opening storage areas could show visitors something new. || It describes the results of the visitor surveys. || It argues that museums should stop collecting specimens. || It explains how specimens are cataloged. >> Most collections are hidden in storage.
IN: Based on the text, the museum's decision most likely helped visitors || better understand what museum scientists do. || view every item in the collection. || handle specimens themselves. || avoid traditional exhibits entirely. >> It showed "how museum research is actually done."

P: Farmers in one region traditionally planted beans, corn, and squash together in the same field. Corn stalks give beans a structure to climb. Bean plants add nitrogen to the soil, which benefits the corn. Squash leaves spread across the ground, shading out weeds and helping the soil retain moisture. Each crop, in other words, helps the others grow.
CI:: || Planting beans, corn, and squash together benefits all three crops because each supports the others. || Corn, beans, and squash should be planted in separate fields. || Squash leaves prevent corn from growing. || Beans remove nitrogen from the soil. >> Each crop provides support, nutrients, or shade.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It summarizes the relationship illustrated by the preceding details. || It introduces a new crop. || It contradicts the details about squash. || It explains why the region is dry. >> "In other words, helps the others grow."
IN: Based on the text, if squash were removed from the field, the farmers would most likely face || more weeds and drier soil. || taller corn. || less nitrogen in the soil. || beans with nothing to climb. >> Squash shades out weeds and helps the soil retain moisture.
"""
