"""Passage units, batch 13 (format documented in passage_data1.py). Original texts; people and studies are illustrative."""

UNITS = """
P: When a small city replaced its paper parking tickets with a smartphone payment system, officials expected mainly convenience benefits. They also discovered that the data showed which blocks were almost always full and which were rarely used. The city then adjusted prices block by block, raising them where spaces were scarce and lowering them where spaces sat empty, and drivers found open spaces more easily.
CI:: || Data from a parking payment app let a city adjust prices by block, making it easier for drivers to find spaces. || The app made parking harder to find. || The city raised prices on every block equally. || Drivers stopped using the app. >> Usage data led to targeted pricing.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It describes an unexpected benefit that made the later policy possible. || It explains how smartphones process payments. || It presents a drawback of the app. || It describes the city's history. >> Usage data revealed demand patterns.
IN: Based on the text, lowering prices on rarely used blocks was most likely intended to || encourage drivers to park in spaces that were usually empty. || reduce the city's revenue. || force drivers to use paper tickets. || close those blocks to parking. >> Cheaper spaces spread demand.

P: The following text is from a novel. Grandfather's toolbox had sat in the garage untouched since his funeral. When the porch step cracked, Esteban's mother reached for her phone to call a carpenter. Esteban stopped her. He opened the toolbox, found the hammer with the tape-wrapped handle, and felt his fingers settle into the worn places where his grandfather's had been.
CI:: || Esteban uses his grandfather's tools to fix the step, feeling a physical connection to him. || Esteban's mother repairs the porch step herself. || Esteban throws away his grandfather's tools. || A carpenter repairs the porch step. >> His hand fits the worn grip.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It establishes the toolbox's connection to the grandfather's absence. || It explains how the porch step cracked. || It describes the carpenter's prices. || It reveals Esteban's age. >> Untouched since the funeral.
IN: Based on the text, Esteban's decision to use the toolbox most likely reflects || a desire to connect with his grandfather's memory. || a lack of money to hire a carpenter. || his mother's request that he fix the step. || his dislike of carpenters. >> He feels his fingers settle into his grandfather's grip.

P: Biologists found that some trees in dry regions shed their leaves during drought and quickly regrow them after rain, while other trees keep their leaves but close tiny pores to conserve water. Trees that drop their leaves avoid water loss almost entirely but cannot produce food until they regrow leaves. Trees that keep leaves can resume food production immediately but still lose some water.
CI:: || Trees in dry regions use different strategies for drought, each with its own trade-off. || All trees in dry regions keep their leaves during drought. || Trees that drop leaves produce food continuously. || Trees that keep leaves lose no water. >> Two strategies with costs and benefits.
TS: Which choice best describes the overall structure of the text? || It introduces two strategies and then describes an advantage and disadvantage of each. || It explains how rain forms. || It compares trees with shrubs. || It argues that one strategy is always better. >> Leaf-dropping versus pore-closing trade-offs.
IN: Based on the text, after a brief rain in the middle of a long drought, which trees would most likely begin producing food first? || Trees that kept their leaves || Trees that dropped their leaves || Both types at exactly the same time || Neither type >> Leaf keepers "can resume food production immediately."

P: When a university library began staying open twenty-four hours during exam weeks, administrators expected crowded nights. Usage between midnight and six a.m. was lower than expected, but those who came reported that the quiet space helped them focus. The library kept the extended hours but reduced staffing during the least busy periods.
CI:: || A library's overnight hours during exams attracted fewer users than expected but helped those who came, so the library kept them with reduced staffing. || The library closed early during exams. || Overnight hours were extremely crowded. || Students disliked the quiet space. >> Lower use, but valued, so hours remained.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It describes how the library responded to the mixed results. || It explains why exams are stressful. || It describes the library's architecture. || It contradicts the survey results. >> Kept hours, reduced staff.
IN: Based on the text, the library reduced staffing during certain hours most likely because || few people used the library at those times. || students asked for fewer staff. || the library planned to close permanently. || staff preferred working at night. >> Usage was lowest during those periods.

P: Scientists studying the sounds of healthy forests found that dawn choruses of birds were louder and more varied in forests with greater biodiversity. In logged or degraded forests, recordings contained fewer species and longer silences. The researchers suggest that automated audio recorders could help monitor forest health across large, remote areas.
CI:: || Forest soundscapes reflect biodiversity, suggesting that audio recorders could help monitor forest health. || Degraded forests produce louder bird choruses. || Biodiversity cannot be measured with sound. || Logged forests contain more bird species. >> Sound varies with biodiversity.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It proposes a practical application of the findings. || It describes how recorders are made. || It contradicts the earlier findings. || It explains why birds sing at dawn. >> Monitoring with recorders.
IN: Based on the text, a recording from a remote forest with long silences and few species would most likely indicate || a forest with reduced biodiversity. || an unusually healthy forest. || a forest with more birds than usual. || a problem with the recorder only. >> Degraded forests had fewer species and longer silences.

P: The following text is from a memoir. I learned patience from my grandmother's bread. She would mix the dough and then do nothing at all for two hours, reading or knitting while it rose. As a child I found this unbearable and would lift the towel every ten minutes to check. "Watching doesn't make it grow faster," she'd say, and pull the towel back down.
CI:: || Through waiting for bread dough to rise, the narrator's grandmother taught her the value of patience. || The narrator's grandmother baked bread quickly. || The narrator never helped with baking. || Checking the dough made it rise faster. >> "Watching doesn't make it grow faster."
TS: Which choice best describes the function of the first sentence in the text as a whole? || It states the lesson that the rest of the text illustrates. || It describes the ingredients of the bread. || It explains why the grandmother knitted. || It reveals the narrator's career. >> Patience is illustrated by the bread.
IN: Based on the text, the narrator repeatedly lifted the towel as a child because she || was impatient to see the dough rise. || wanted to add more flour. || thought the dough was burning. || was helping her grandmother knead. >> She "found this unbearable."

P: A company that manufactures phone cases switched from plastic packaging to paper made from recycled cardboard. Surveys showed that customers noticed the change and viewed the brand more favorably. Shipping costs also fell slightly because the new packaging was lighter.
CI:: || Switching to recycled paper packaging improved customers' views of a brand and slightly reduced shipping costs. || Customers disliked the new packaging. || Shipping costs rose because paper is heavier. || The company returned to plastic packaging. >> Better perception and lower costs.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It describes an additional, practical benefit of the change. || It explains how cardboard is recycled. || It contradicts the survey results. || It describes the phone cases. >> Lighter packaging lowered shipping costs.
IN: Based on the text, the company would most likely regard the packaging change as || beneficial both for its reputation and its expenses. || costly and unpopular. || irrelevant to customers. || harmful to shipping. >> Favorable views and lower costs.

P: Linguists studying a remote village found that elderly residents used many words for types of snow and ice that younger residents did not know. As the climate warmed and people traveled less over frozen land, the precise terms were used less often. The researchers are recording elders' speech to preserve this detailed knowledge.
CI:: || Specialized words for snow and ice are fading in a village as conditions and activities change, prompting efforts to record them. || Younger residents know more snow words than elders. || The climate in the village has become colder. || Researchers are teaching elders new words. >> Changing environment reduces use of precise terms.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It explains why younger residents are less familiar with the terms. || It describes how researchers record speech. || It lists the words for snow. || It contradicts the first sentence. >> Warming and less travel reduced use.
IN: Based on the text, the precise terms were most likely important in the past because they || helped people travel safely and knowledgeably over frozen land. || were required by village law. || described only summer weather. || were borrowed from other languages. >> Usage declined as travel over frozen land decreased.

P: When a community garden added raised beds at wheelchair height, organizers hoped to include gardeners with disabilities. The beds proved popular with many older gardeners as well, who found them easier on their backs and knees. The garden later replaced several ground-level plots with raised beds because of demand.
CI:: || Wheelchair-height garden beds benefited gardeners with disabilities and many older gardeners, leading to more such beds. || The raised beds were unpopular with older gardeners. || The garden removed its raised beds. || Only young gardeners used the raised beds. >> Accessibility features had broad appeal.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It shows that the beds benefited more people than originally intended. || It explains how raised beds are built. || It describes the garden's vegetables. || It presents a drawback of the beds. >> Older gardeners also benefited.
IN: Based on the text, older gardeners preferred the raised beds most likely because they || required less bending and kneeling. || produced more vegetables. || were located indoors. || needed no watering. >> Easier "on their backs and knees."

P: The following text is from a poem. Each autumn my mother pressed a leaf / between the pages of whatever book she read, / so that years later, opening a novel, / I'd find a maple, flat and red, / marking not a chapter / but a season of her life, / a small dry letter / from a year I barely knew.
CI:: || The speaker finds pressed leaves in her mother's books that serve as reminders of moments in her mother's life. || The speaker's mother disliked autumn. || The leaves mark chapters the mother wanted to reread. || The speaker presses leaves in her own books. >> Leaves mark seasons of her mother's life.
TS: Which choice best describes the function of the phrase "not a chapter / but a season of her life" in the poem? || It shifts the leaf's meaning from a practical bookmark to a personal memento. || It explains how books are organized. || It describes the colors of maple leaves. || It reveals that the books were never read. >> The leaf records time in her life.
IN: Based on the text, the speaker most likely feels that the leaves || offer glimpses into parts of her mother's past. || damage the books. || are meaningless decorations. || were placed there by the speaker. >> "A small dry letter from a year I barely knew."

P: Researchers measuring air quality inside schools found that classrooms with poor ventilation had high levels of carbon dioxide by midday. Students in those rooms scored lower on tests of attention given in the afternoon. When ventilation was improved, carbon dioxide levels fell and afternoon test scores rose.
CI:: || Improving classroom ventilation lowered carbon dioxide levels and was linked to better afternoon attention scores. || Ventilation had no effect on carbon dioxide levels. || Students scored higher in poorly ventilated rooms. || Carbon dioxide levels were lowest by midday. >> Better air, better scores.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It describes an intervention that strengthens the link between air quality and attention. || It explains how tests were written. || It contradicts the earlier findings. || It describes the classroom furniture. >> Improved ventilation raised scores.
IN: Based on the text, students' attention was likely weakest || in the afternoon in poorly ventilated rooms. || in the morning in well-ventilated rooms. || before carbon dioxide levels rose. || after ventilation was improved. >> CO2 peaked by midday; afternoon scores were lower.

P: When a town's historic movie theater faced closure, residents formed a nonprofit and raised money through small donations to buy the building. They showed older films, hosted local music performances, and rented the space for community events. Within five years, the theater was financially stable and had become a gathering place for the town.
CI:: || Residents saved a historic theater by turning it into a community-run venue that became financially stable. || The theater closed permanently. || The theater showed only new films. || A large company bought the theater. >> A nonprofit made it sustainable.
TS: Which choice best describes the overall structure of the text? || It describes a threat, the community's response, and the outcome. || It compares two theaters. || It explains how films are projected. || It argues that theaters are unnecessary. >> Closure threat, nonprofit efforts, and stability.
IN: Based on the text, the theater's variety of events most likely helped it survive by || attracting different audiences and sources of income. || reducing the number of visitors. || focusing only on film. || relying on a single donor. >> Films, music, and rentals diversified use.

P: Scientists studying desert tortoises found that the animals dig burrows that can stay cool even when surface temperatures are extremely high. Other species, including snakes, lizards, and insects, often use abandoned tortoise burrows to escape the heat. The researchers describe the tortoises as important to the survival of many other desert animals.
CI:: || Tortoise burrows provide cool shelter used by many other desert animals, making tortoises important to the ecosystem. || Tortoise burrows are too hot for other animals. || Only tortoises use tortoise burrows. || Desert surface temperatures are mild. >> Burrows benefit many species.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It shows how other species benefit from the burrows. || It explains how tortoises dig. || It describes tortoises' diets. || It contradicts the first sentence. >> Snakes, lizards, and insects use them.
IN: Based on the text, a decline in desert tortoises would most likely || reduce shelter available to other desert animals. || increase the number of cool burrows. || have no effect on other species. || cause surface temperatures to fall. >> Many animals rely on their burrows.

P: When a hospital began allowing family members to stay overnight with patients in the intensive care unit, some staff worried that visitors would interfere with care. Instead, nurses reported that families often noticed changes in patients' conditions and alerted staff early. Patients and families also reported lower stress levels.
CI:: || Allowing families to stay overnight in intensive care helped staff notice changes and reduced stress, rather than interfering with care. || Families interfered with patient care. || Nurses opposed the policy after it began. || Patients reported higher stress levels. >> Families helped and stress decreased.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It presents a concern that the later results did not support. || It explains how intensive care units work. || It describes nurses' training. || It summarizes the results. >> Staff worried about interference.
IN: Based on the text, families were helpful partly because they || knew patients well enough to notice changes. || performed medical procedures. || replaced nurses at night. || prevented doctors from visiting. >> They "noticed changes ... and alerted staff."

P: The following text is from a short story. Leo had practiced his speech for the class election until he knew every word. At the podium, he looked out at his classmates, and the words vanished. After a long, awful pause, he said the only thing he could think of: "I forgot my speech. But I remember what I wanted to say." Then he told them, plainly, why he wanted to help. The room was quiet when he finished, and then it applauded.
CI:: || After forgetting his rehearsed speech, Leo speaks honestly and plainly, and his classmates respond with applause. || Leo delivers his memorized speech perfectly. || Leo leaves the podium without speaking. || The class boos Leo's speech. >> Honest words replace the forgotten speech.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It establishes Leo's preparation, which makes his forgetting more dramatic. || It explains why Leo ran for office. || It describes the election results. || It reveals the other candidates' names. >> He knew every word before forgetting.
IN: Based on the text, the classmates' applause most likely suggests that they || appreciated Leo's sincerity. || were relieved the speech was over. || did not hear the speech. || preferred memorized speeches. >> Plain honesty earned applause.

P: Farmers in one region began releasing ladybugs into greenhouses to control aphids instead of spraying insecticides. Aphid numbers fell, and the farmers saved money on chemicals. However, ladybugs sometimes flew away when food was scarce, so farmers learned to release them in smaller groups more frequently.
CI:: || Ladybugs helped greenhouse farmers control aphids and save money, though farmers adjusted their release methods. || Ladybugs increased aphid populations. || Farmers switched back to insecticides immediately. || Ladybugs never leave greenhouses. >> Biological control worked with adjustments.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It describes a challenge and how farmers adapted to it. || It explains why aphids damage plants. || It restates the benefits. || It describes insecticide ingredients. >> Ladybugs flew away, so releases changed.
IN: Based on the text, releasing ladybugs in smaller groups more frequently most likely || kept enough ladybugs present without leaving them short of food. || attracted more aphids. || required more insecticide. || reduced the farmers' savings. >> Scarcity caused ladybugs to leave.

P: When a city offered free public Wi-Fi in parks, officials expected people to use it mainly for entertainment. Surveys found that many users were students completing homework and job seekers submitting applications, especially in neighborhoods where many households lacked home internet.
CI:: || Free park Wi-Fi was widely used for homework and job applications, especially in areas where home internet was less common. || Park Wi-Fi was used only for entertainment. || Students avoided using park Wi-Fi. || Most households in all neighborhoods had home internet. >> Practical uses in underserved areas.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It presents an expectation that the survey findings complicated. || It explains how Wi-Fi works. || It describes the parks' size. || It summarizes the survey results. >> Officials expected entertainment use.
IN: Based on the text, the Wi-Fi program was likely most valuable in neighborhoods where || many households did not have internet at home. || every household had fast internet. || there were no parks. || students had no homework. >> Use was highest where home internet was lacking.

P: Ornithologists studying crows in a city found that the birds dropped hard-shelled nuts onto crosswalks and waited for cars to crack them. The crows then retrieved the nut pieces when traffic lights stopped the cars. Researchers noted that the birds appeared to time their retrieval to the light signals.
CI:: || City crows use traffic to crack nuts and appear to time retrieving the pieces with traffic lights. || Crows avoid roads entirely. || Crows crack nuts using only their beaks. || Cars intentionally stop for crows. >> Clever use of traffic and signals.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It highlights a detail suggesting the crows' behavior is especially sophisticated. || It explains how nuts grow. || It describes the city's traffic laws. || It contradicts the first sentence. >> Timing with light signals.
IN: Based on the text, the crows most likely retrieve nut pieces when lights stop traffic because || it is safer to walk on the road when cars are not moving. || the nuts crack only at red lights. || drivers feed them at stoplights. || the lights attract insects. >> Stopped cars reduce danger.

P: The following text is from a memoir. My father could fix almost anything, but he rarely explained how. When I was twelve and the lawnmower broke, he handed me the manual and a screwdriver and went inside. I spent the entire afternoon covered in grease, furious. By evening the mower started. He came out, listened to it run, nodded once, and went back in. I have never been prouder of a nod.
CI:: || The narrator's father taught her self-reliance by letting her fix the mower alone, and his brief approval meant a great deal to her. || The narrator's father fixed the mower for her. || The narrator failed to repair the mower. || The father praised the narrator at length. >> Independence and a meaningful nod.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It shows how much the father's small gesture of approval meant to the narrator. || It explains how lawnmowers work. || It suggests the narrator was still angry. || It describes the father's career. >> "Never been prouder of a nod."
IN: Based on the text, the father's decision to go inside most likely reflects || his intention to let the narrator solve the problem independently. || his lack of interest in the lawnmower. || his belief that the mower could not be fixed. || his wish to call a repair service. >> He left her with tools and the manual.

P: When a regional power grid began paying households with rooftop solar panels and home batteries to share stored electricity during peak demand, the grid needed fewer backup power plants on hot afternoons. Households earned money, and the grid avoided building new capacity. Some households, however, worried that their batteries would wear out faster.
CI:: || Paying households to share stored solar power reduced the grid's need for backup plants, though some worried about battery wear. || The program increased the need for power plants. || Households lost money in the program. || No households had concerns about the program. >> Benefits plus a battery-wear concern.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It presents a concern some participants had about the program. || It explains how solar panels work. || It restates the program's benefits. || It describes the grid's history. >> Battery wear worries.
IN: Based on the text, the grid most likely benefited because shared household power || helped meet demand during the hottest periods. || replaced all power plants permanently. || was used only at night. || increased electricity prices. >> Fewer backup plants were needed on hot afternoons.

P: A study of museum visitors found that people who took photographs of artworks remembered fewer details about them later than people who simply looked. However, when visitors zoomed in on a specific part of an artwork while photographing it, their memory for that part improved. Researchers suggest that focused attention, not photography itself, affects memory.
CI:: || Taking photos generally reduced visitors' memory of artworks, but focused attention while photographing improved memory for details. || Photographing art always improves memory. || Zooming in reduced memory for details. || Visitors who only looked remembered nothing. >> Attention, not the camera, matters.
TS: Which choice best describes the function of the word "However" in the text? || It introduces a finding that qualifies the general effect of photography on memory. || It contradicts the idea that visitors took photos. || It explains how cameras zoom. || It describes the museum's collection. >> Zooming in reversed the effect for that detail.
IN: Based on the text, a visitor who wants to remember a painting's details while taking photos should most likely || deliberately focus attention on specific parts of the painting. || take many quick photos without looking. || avoid looking at the painting. || photograph only the frame. >> Focused attention improves memory.

P: Researchers studying why some neighborhoods have more street trees than others found that wealthier areas often had greater tree cover, partly because homeowners could afford to plant and maintain trees. In response, several cities launched programs to plant trees in neighborhoods with low tree cover and to fund their care during the first few years.
CI:: || Tree cover often reflects neighborhood wealth, prompting cities to plant and maintain trees in areas with fewer trees. || Wealthier neighborhoods have fewer trees. || Cities stopped planting trees. || Tree cover is equal across all neighborhoods. >> Unequal cover and city responses.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It describes actions taken to address the pattern described in the first sentence. || It explains how trees grow. || It contradicts the research findings. || It describes the costs of homes. >> Programs respond to unequal tree cover.
IN: Based on the text, cities funded tree care during the first few years most likely because || young trees require care that residents may not be able to afford. || mature trees need no care. || trees are cheaper to plant than to maintain. || residents asked cities to remove trees. >> Maintenance costs had limited tree cover.

P: When a publishing company began releasing audiobooks narrated by the authors themselves, sales of those audiobooks rose compared with versions read by professional narrators. Listeners reported that hearing authors' own voices made the books feel more personal. Some reviewers noted, however, that not all authors were skilled readers.
CI:: || Author-narrated audiobooks sold better and felt more personal to listeners, though some authors read less skillfully. || Professional narrators always sold more audiobooks. || Listeners disliked hearing authors' voices. || All authors were excellent readers. >> Popularity with a caveat.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It notes a limitation of author narration. || It explains how audiobooks are recorded. || It supports the claim that sales rose. || It describes the books' plots. >> Not all authors read well.
IN: Based on the text, listeners valued author narration mainly because it || created a sense of personal connection to the book. || was always more polished. || was shorter than other versions. || cost less. >> It made books "feel more personal."

P: Scientists examining ancient teeth found that people in one farming village had more cavities than hunter-gatherers who lived nearby at the same time. The farmers ate diets rich in grains, which break down into sugars that feed bacteria in the mouth. The finding suggests that changes in diet during the transition to farming affected dental health.
CI:: || Ancient farmers had more cavities than nearby hunter-gatherers, likely because grain-rich diets affected dental health. || Hunter-gatherers had more cavities than farmers. || Grains prevent tooth decay. || Diet has no effect on teeth. >> Grain diets linked to cavities.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It explains why the farmers may have had more cavities. || It describes how teeth were excavated. || It compares tools used by the two groups. || It contradicts the first sentence. >> Grains break down into sugars that feed bacteria.
IN: Based on the text, hunter-gatherers most likely had fewer cavities because they || ate fewer grain-based foods. || brushed their teeth more often. || lived in colder climates. || ate only sweet fruits. >> The farmers' grain-rich diets fed bacteria.

P: The following text is from a novel. The fog rolled in every afternoon at four, as reliably as a train. Newcomers complained that it ruined their plans. The fishermen, though, set their clocks by it, pulling in their nets as the gray wall crept over the harbor. "The fog isn't the problem," old Marisol liked to say. "Expecting the sun is."
CI:: || While newcomers resent the daily fog, local fishermen accept it as part of life, as Marisol's saying suggests. || The fog appears at random times. || The fishermen refuse to work in fog. || Marisol dislikes the fog more than newcomers do. >> Acceptance versus frustration.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It expresses a view that frustration comes from unrealistic expectations rather than the fog itself. || It explains how fog forms. || It describes the fishermen's nets. || It reveals that the fog will stop. >> "Expecting the sun is" the problem.
IN: Based on the text, the fishermen differ from the newcomers mainly in that the fishermen || adapt their routines to the fog. || have never seen fog before. || prefer sunny weather. || leave the harbor when fog arrives. >> They "set their clocks by it."

P: When a school district replaced sugary drinks in vending machines with water and milk, researchers expected students might simply buy sodas elsewhere. Surveys found that overall soda consumption among students did decline, though some students did bring drinks from home. Consumption fell most among younger students, who had fewer opportunities to buy drinks off campus.
CI:: || Removing sugary drinks from school vending machines reduced soda consumption, especially among younger students. || Soda consumption increased after the change. || All students brought soda from home. || Older students reduced soda the most. >> Overall decline, largest among younger students.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It identifies which students' consumption changed most and offers a reason. || It describes the vending machines. || It contradicts the survey results. || It explains how milk is produced. >> Younger students had fewer off-campus options.
IN: Based on the text, older students' soda consumption likely fell less because they || had more chances to buy drinks away from school. || preferred milk. || did not use vending machines. || were not surveyed. >> Younger students "had fewer opportunities to buy drinks off campus."

P: When a small bookstore installed a shelf labeled "Staff Picks" with handwritten notes explaining why employees loved each book, sales of those titles rose sharply. Customers said the notes felt like recommendations from a friend. Several books that had been sitting unsold for months became bestsellers at the store.
CI:: || Handwritten staff recommendations boosted sales, even for books that had not been selling. || Staff Picks reduced book sales. || Customers ignored the handwritten notes. || Only bestsellers were placed on the shelf. >> Personal notes drove sales.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It provides a striking example of the shelf's effect. || It explains how books are shipped. || It describes the store's owner. || It contradicts the earlier sentences. >> Unsold books became bestsellers.
IN: Based on the text, the notes were effective most likely because they || made the recommendations feel personal and trustworthy. || lowered book prices. || listed authors' awards. || were printed by the publisher. >> They "felt like recommendations from a friend."

P: Biologists studying salmon in a river with a newly removed dam found that fish began swimming upstream to spawning grounds they had not reached in decades. Within a few years, populations of insects, birds, and bears along the upper river also increased, as salmon carcasses and eggs provided food.
CI:: || Removing a dam allowed salmon to reach upstream spawning grounds, benefiting other wildlife along the river. || The dam removal reduced salmon populations. || Salmon had always reached the upper river. || Other wildlife declined after the dam was removed. >> Restored access and ecosystem benefits.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It describes broader ecological effects of the salmon's return. || It explains how dams are built. || It describes fishing regulations. || It contradicts the first sentence. >> Insects, birds, and bears increased.
IN: Based on the text, the dam had most likely || blocked salmon from reaching upstream spawning grounds. || increased food for bears. || helped salmon reproduce. || had no effect on the river. >> Salmon reached areas "they had not reached in decades."

P: When a city introduced a program allowing residents to report potholes through a phone app with photos and locations, repair crews could plan efficient routes and fix clusters of potholes in a single trip. Average repair times fell, and residents reported greater satisfaction with road maintenance.
CI:: || A pothole-reporting app helped crews plan efficient repairs, reducing repair times and increasing satisfaction. || Repair times increased after the app was introduced. || Residents stopped reporting potholes. || Crews ignored reports from the app. >> Better data enabled efficient routes.
TS: Which choice best describes the function of the phrase "with photos and locations" in the text? || It identifies the information that allowed crews to plan efficient routes. || It explains how phones take pictures. || It describes the city's roads. || It suggests the app was difficult to use. >> Precise data enabled planning.
IN: Based on the text, repair crews became more efficient mainly because they || could see where potholes were clustered and plan trips accordingly. || stopped repairing some roads. || worked longer hours. || received fewer reports. >> Fixing "clusters of potholes in a single trip."

P: The following text is from a poem. My grandmother's hands / were never still: / shelling peas, / mending hems, / braiding my hair / tight enough to last a week. / Even in the hospital, / her fingers moved across the blanket, / looking for something to do.
CI:: || The poem portrays a grandmother whose hands were always busy, even when she was ill. || The grandmother rested her hands often. || The speaker braids the grandmother's hair. || The grandmother disliked sewing. >> Her hands "were never still."
TS: Which choice best describes the function of the final three lines of the poem? || They show that the grandmother's lifelong habit continued even in illness. || They describe a new hobby. || They explain why she was in the hospital. || They contrast her with other patients. >> Fingers still searching for work.
IN: Based on the text, the image of the grandmother's fingers "looking for something to do" suggests that || being useful was deeply part of who she was. || she was trying to call a nurse. || she wanted to leave the hospital. || she had forgotten how to sew. >> A lifetime of busy hands persists.

P: When a city planted wildflower meadows along highway medians instead of mowed grass, maintenance crews mowed only once a year instead of every few weeks. The city saved money on fuel and labor, and surveys of the medians found many more bees and butterflies than before. Some drivers initially complained that the medians looked overgrown, but complaints declined as the flowers bloomed.
CI:: || Replacing mowed median grass with wildflowers cut maintenance costs and supported pollinators, and early complaints faded. || Wildflower medians required more frequent mowing. || Bees avoided the new wildflower medians. || Drivers complained more as the flowers bloomed. >> Savings, pollinators, and declining complaints.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It describes an initial objection and how it changed over time. || It explains how wildflowers are planted. || It restates the cost savings. || It describes the highway's traffic. >> Complaints declined as flowers bloomed.
IN: Based on the text, drivers' complaints most likely declined because || the blooming flowers made the medians look more attractive. || the city mowed the medians more often. || drivers stopped using the highway. || the wildflowers were removed. >> Complaints fell "as the flowers bloomed."

P: The following text is from a short story. For weeks, Nadia's little brother had begged to come along on her early-morning runs, and for weeks she had said no. He was too slow, she told him. One Saturday she finally gave in. He fell behind within a block, red-faced and panting, but he did not stop. At the end of the route, Nadia found herself jogging in place, waiting, and cheering louder than she ever had for herself.
CI:: || After reluctantly letting her brother join her run, Nadia is moved by his determination and cheers him on. || Nadia's brother quits the run after a block. || Nadia refuses to wait for her brother. || Nadia's brother runs faster than she does. >> His persistence changes her attitude.
TS: Which choice best describes the function of the sentence "He was too slow, she told him" in the text? || It gives Nadia's reason for refusing, which contrasts with her later response. || It explains why the brother wanted to run. || It describes the running route. || It reveals the brother's age. >> Her dismissal contrasts with her cheering.
IN: Based on the text, Nadia's cheering "louder than she ever had for herself" suggests that she || felt proud of her brother's effort. || was annoyed at having to wait. || wanted her brother to stop running. || was cheering for another runner. >> His determination inspires her pride.
"""
