"""Passage units, batch 3 (format documented in passage_data1.py). Original texts; people and studies are illustrative."""

UNITS = """
P: When the town of Millbrook lost its only grocery store, residents who did not own cars faced a forty-minute bus ride to buy fresh food. A group of retirees responded by organizing a weekly market in the church parking lot, inviting farmers from nearby counties to sell produce directly. The market began with four vendors. Five years later it hosts thirty, and the town council has voted to make the parking lot a permanent public market space.
CI:: || After losing its grocery store, a town gained access to fresh food through a market that residents organized and that has since grown. || Millbrook's residents prefer shopping at farmers' markets to shopping at grocery stores. || The town council built a new grocery store to replace the one that closed. || Farmers from nearby counties opened a grocery store in Millbrook. >> The text moves from the loss of the store to the retirees' market and its growth and official recognition.
TS: Which choice best describes the overall structure of the text? || It presents a problem, describes a community response, and then shows how that response developed over time. || It compares two grocery stores and explains why one closed. || It describes the history of a church and its parking lot. || It argues that towns should not rely on grocery stores. >> Problem (no store), response (market), development (thirty vendors, permanent space).
IN: Based on the text, the town council's vote most likely reflects || recognition that the market has become an important and lasting resource for the town. || a decision to replace the market with a new grocery store. || concern that the market has attracted too few vendors. || a plan to close the church. >> The council made the lot a permanent market after the market grew from four vendors to thirty.

P: The following text is from a novel. Every evening at six, Mr. Hadley walked the length of Harbor Road with his hands clasped behind his back, nodding to each neighbor by name. When he fell ill one winter and the walks stopped, no one mentioned it at first. But by the third evening, doors along Harbor Road began to open, and one neighbor after another found a reason to carry soup, or a newspaper, or simply a question, to the small blue house at the end of the street.
CI:: || The neighbors' response to Mr. Hadley's absence shows how much his daily presence meant to them. || Mr. Hadley's neighbors did not notice when he stopped taking his evening walks. || Mr. Hadley moved away from Harbor Road during the winter. || The neighbors on Harbor Road rarely spoke to one another. >> When his walks stop, the neighbors come to his house with soup and newspapers.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It establishes a routine whose interruption drives the rest of the text. || It explains why Mr. Hadley became ill. || It describes the layout of Harbor Road in detail. || It introduces a conflict between Mr. Hadley and his neighbors. >> The daily walk sets up the change when "the walks stopped."
IN: Based on the text, the neighbors most likely "found a reason" to visit Mr. Hadley because they || wanted to check on him without making a fuss about his absence. || needed his help with a problem on Harbor Road. || had been asked by a doctor to deliver his meals. || were hoping to buy the small blue house. >> They bring small items or "simply a question," suggesting a quiet way to check on him.

P: Many people picture icebergs as white, but some are strikingly blue. The color comes from ice that formed under great pressure deep within a glacier. That pressure squeezes out the tiny air bubbles that normally scatter all colors of light and make ice look white. Without those bubbles, the dense ice absorbs more red light than blue, so blue light is what reaches our eyes.
CI:: || Some icebergs look blue because pressure removed air bubbles from their ice, changing how the ice interacts with light. || All icebergs are blue when they first break off from glaciers. || Blue icebergs contain more air bubbles than white icebergs. || Icebergs appear white because they absorb blue light. >> The text explains how pressure removes bubbles, letting dense ice absorb red and show blue.
TS: Which choice best describes the overall structure of the text? || It points out a surprising observation and then explains its cause step by step. || It describes an experiment and then questions its results. || It compares icebergs in two different oceans. || It lists several types of glaciers and their locations. >> Blue icebergs (observation), then pressure, bubbles, and light absorption (explanation).
IN: Based on the text, ice that contains many tiny air bubbles would most likely appear || white. || blue. || red. || transparent. >> Bubbles "normally scatter all colors of light and make ice look white."

P: Historians studying a seventeenth-century merchant's account books noticed that his profits rose sharply in the years after he began recording every transaction, however small, in a single ledger. Earlier, he had kept separate notebooks for each ship and often lost track of debts owed to him. The historians suggest that the change in record keeping, rather than any change in the goods he traded, may explain his improved fortunes.
CI:: || Historians suggest that a merchant's profits may have risen because he adopted a more organized system of record keeping. || A seventeenth-century merchant began trading more valuable goods and became wealthy. || The merchant lost several ships and had to rely on a single ledger. || Historians believe that account books from the period are unreliable. >> The text connects the switch to a single ledger with rising profits.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It describes the merchant's earlier practice, which helps explain why the change mattered. || It presents evidence that the merchant traded different goods over time. || It suggests that the historians' conclusion is incorrect. || It explains how historians located the account books. >> Separate notebooks and lost debts contrast with the later single ledger.
IN: Based on the text, which situation would most likely have contributed to the merchant's lower profits before the change? || Money owed to him going uncollected because he could not track it. || A sudden drop in demand for all of the goods he sold. || A law requiring merchants to keep separate notebooks for each ship. || A decision to stop trading overseas. >> He "often lost track of debts owed to him."

P: The following text is from a poem. The kettle hums before it sings, / a low and patient sound, / as if it knows the morning / needs a little time to come around. / And I, who rush from bed to door, / could stand to learn its art: / to warm up slowly, steadily, / before I make a start.
CI:: || The speaker admires the kettle's gradual warming and wishes to approach the morning in the same unhurried way. || The speaker is frustrated that the kettle takes too long to boil. || The speaker prefers to skip breakfast in order to leave early. || The speaker describes how to repair a broken kettle. >> The speaker "could stand to learn its art: to warm up slowly."
TS: Which choice best describes the overall structure of the text? || It describes an object's behavior and then applies a lesson from that behavior to the speaker's own life. || It narrates a sequence of events from a busy morning. || It compares two kettles and chooses the better one. || It describes a sound and then explains its scientific cause. >> The first half describes the kettle; the second half turns to the speaker.
IN: Based on the text, the speaker's usual morning routine is best described as || hurried. || leisurely. || carefully planned. || silent. >> The speaker "rush[es] from bed to door."

P: In many cities, rooftop gardens are praised for cooling buildings and reducing stormwater runoff. A research team measuring rooftops in one city confirmed both benefits but found a third that residents had not expected: the gardens attracted dozens of species of bees, including several rarely seen elsewhere in the city. The researchers now argue that rooftop gardens should be designed with pollinators in mind, using flowering plants that bloom at different times of year.
CI:: || A study found that rooftop gardens also support bees, leading researchers to recommend designing the gardens to help pollinators. || Rooftop gardens do not actually cool buildings or reduce runoff. || Bees in the city prefer to nest on the ground rather than on rooftops. || Rooftop gardens should contain only plants that bloom in summer. >> The unexpected bee finding leads to the recommendation about pollinator-friendly design.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It presents a recommendation that follows from the unexpected finding. || It questions whether the study's measurements were accurate. || It restates the benefits described in the first sentence. || It explains how the researchers counted the bees. >> The recommendation builds on the discovery of many bee species.
IN: Based on the text, the researchers recommend plants that bloom at different times of year most likely because || such plants would provide food for bees across more of the year. || such plants cool buildings more effectively. || such plants are less expensive to maintain. || bees avoid plants that bloom in summer. >> Staggered blooming would support pollinators over a longer period.

P: For years, a small theater company performed classic plays in their original formal language. Attendance slowly declined. When a new director proposed staging the same plays with modern costumes and settings while keeping every original word, longtime members worried that the changes would distract from the text. Instead, audiences grew, and several reviewers wrote that the unfamiliar settings made them listen to the familiar words more closely than ever.
CI:: || Modern staging of classic plays, with the original words unchanged, attracted larger audiences and helped viewers engage with the text. || The theater company rewrote classic plays in modern language. || Longtime members successfully prevented the director's changes. || Reviewers criticized the new productions for distracting from the text. >> Audiences grew, and reviewers said the settings made them listen more closely.
TS: Which choice best describes the overall structure of the text? || It describes a decline, a proposed change and the concern it raised, and then the unexpected result. || It traces the history of a single classic play. || It compares acting styles in two theater companies. || It argues that modern plays are better than classic ones. >> Declining attendance, proposal and worry, then growth and positive reviews.
IN: Based on the text, the longtime members' concern turned out to be || largely unfounded. || fully justified. || shared by most reviewers. || the reason attendance declined. >> Reviewers said the settings helped them listen "more closely than ever."

P: Hummingbirds have one of the highest metabolic rates of any animal and must eat almost constantly while awake. At night, however, many species enter a state called torpor, lowering their body temperature and heart rate dramatically. A hummingbird in torpor can use a small fraction of the energy it would need to stay fully active overnight, allowing it to survive until it can feed again in the morning.
CI:: || Hummingbirds survive the night by entering torpor, which greatly reduces the energy they use. || Hummingbirds eat throughout the night to maintain their energy. || Hummingbirds have unusually slow metabolisms. || Torpor causes hummingbirds to lose weight quickly. >> The text explains how torpor helps hummingbirds conserve energy overnight.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It establishes the energy demands that make torpor useful. || It describes what happens to hummingbirds during torpor. || It argues that hummingbirds should be fed at night. || It compares hummingbirds with other birds. >> Their constant need for food explains why saving energy at night matters.
IN: Based on the text, a hummingbird that could not enter torpor on a cold night would most likely || use far more energy overnight than a hummingbird in torpor. || need no food the next morning. || have a lower heart rate than usual. || stop needing to eat during the day. >> Torpor uses "a small fraction of the energy" needed to stay active.

P: In the early twentieth century, a city built its main library with enormous windows on every side, at a time when most libraries relied on small windows and gas lamps. Critics complained that the glass would make the building cold and fade the books. The architect responded by placing reading tables near the windows and shelving the books in the building's interior, away from direct sunlight. The library's reading room became one of the most popular public spaces in the city.
CI:: || An architect designed a library with large windows and arranged its interior to address critics' concerns, creating a popular public space. || Critics convinced the architect to remove the library's windows. || Most early twentieth-century libraries had very large windows. || The library's books were badly faded by sunlight. >> The design, the criticism, the architect's arrangement, and the result.
TS: Which choice best describes the function of the third sentence in the text as a whole? || It describes how the architect addressed one of the critics' concerns. || It explains why gas lamps were common in libraries. || It provides evidence that the critics were correct. || It describes the library's popularity. >> Shelving books away from sunlight answers the worry about fading.
IN: Based on the text, the architect placed reading tables near the windows most likely to || let readers take advantage of the natural light. || keep the books away from the tables. || make the building warmer in winter. || block sunlight from reaching the interior. >> Readers near windows benefit from light, while books stay in the interior.

P: A psychologist asked participants to predict how happy they would feel a year after a major event, such as moving to a new city. Most predicted that their happiness would change a great deal, for better or worse. When the psychologist checked in a year later, most participants' happiness had returned close to their original levels. The study adds to evidence that people tend to overestimate how long the emotional effects of events will last.
CI:: || People tend to predict that events will affect their happiness for longer than they actually do. || Moving to a new city usually makes people much happier. || People accurately predict how they will feel a year after major events. || Happiness levels always decline over time. >> Predictions of big, lasting change contrasted with happiness returning to near original levels.
TS: Which choice best describes the overall structure of the text? || It describes participants' predictions, compares them with what later happened, and states a broader conclusion. || It explains how to become happier after moving. || It describes a debate between two psychologists. || It lists several major life events in order of importance. >> Predictions, follow-up results, then the general conclusion.
IN: Based on the text, a person who expects to feel miserable for years after failing a driving test would most likely || feel better sooner than they expect. || feel exactly as miserable as they predicted. || never recover from the disappointment. || feel happier than ever within a day. >> People "overestimate how long the emotional effects of events will last."

P: The following text is adapted from a nineteenth-century travel diary. We reached the pass at noon, and the guide told us to rest. I could not. Before me the valley opened like a book whose pages I had waited all my life to read: the river glinting silver, the villages no larger than thumbprints, and beyond them, rank upon rank, mountains I had known only from maps. My legs ached, but I stood until the guide took my arm and insisted that I sit.
CI:: || The writer is so moved by the view from the mountain pass that she ignores her fatigue. || The writer is disappointed by the view after a long climb. || The guide refuses to let the travelers see the valley. || The writer is too tired to look at the view. >> She "could not" rest and stood despite aching legs until the guide insisted.
TS: Which choice best describes the function of the comparison of the valley to "a book" in the text? || It conveys the writer's long-held eagerness to see the landscape. || It suggests that the writer is reading while resting. || It explains how the maps of the region were made. || It emphasizes that the valley is small and ordinary. >> Pages "I had waited all my life to read" express anticipation.
IN: Based on the text, why did the guide most likely take the writer's arm? || To make sure she rested after the tiring climb. || To lead her back down the mountain. || To point out a village in the valley. || To stop her from reading a book. >> The guide had told them to rest and "insisted that I sit."

P: In one study, researchers placed identical bowls of candy on desks in an office, some in clear bowls and some in opaque bowls. Over several weeks, employees ate noticeably more candy from the clear bowls. When the researchers moved the clear bowls just two meters away from the desks, candy consumption dropped sharply. The findings suggest that small changes in how visible and convenient food is can significantly affect how much people eat.
CI:: || Making candy less visible or less convenient reduced how much of it people ate. || Employees preferred candy in opaque bowls to candy in clear bowls. || Moving bowls closer to desks reduced candy consumption. || The type of candy in the bowls affected how much people ate. >> Clear bowls led to more eating; moving them farther away reduced it.
TS: Which choice best describes the function of the third sentence in the text as a whole? || It presents a second finding that shows the effect of convenience. || It contradicts the finding presented in the second sentence. || It explains why the researchers chose clear bowls. || It describes the type of candy used. >> Distance, like visibility, changed consumption.
IN: Based on the text, an office that wanted employees to eat more fruit would most likely benefit from || placing fruit in clear bowls close to where people work. || storing fruit in opaque containers in a separate room. || removing all other snacks from the building. || buying more expensive fruit. >> Visible, convenient food was eaten more.

P: For centuries, residents of a desert region have built underground channels that carry water from distant mountain aquifers to their villages. Because the channels run beneath the surface, little water is lost to evaporation, even in extreme heat. Maintaining the channels requires workers to climb down vertical shafts to clear sand and repair walls, a skill traditionally passed from parents to children. As fewer young people learn the trade, some channels have fallen into disrepair.
CI:: || Underground channels efficiently supply desert villages with water, but their future depends on passing down the skills needed to maintain them. || Desert villages no longer need water from mountain aquifers. || Underground channels lose more water to evaporation than open canals. || Young people in the region have built many new channels. >> The text praises the channels' efficiency and notes the risk as fewer people learn maintenance.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It introduces a threat to the system described earlier in the text. || It explains how the channels were first built. || It summarizes the benefits of the channels. || It describes where the aquifers are located. >> Fewer workers and disrepair present a problem.
IN: Based on the text, the channels' underground design is most valuable in the region because || it protects the water from being lost in the region's intense heat. || it prevents sand from ever entering the channels. || it allows the channels to be built without workers. || it makes the channels easy to see from a distance. >> "Little water is lost to evaporation, even in extreme heat."

P: When a zoo redesigned its gorilla habitat, keepers replaced the concrete floor with soil, logs, and tall grasses and scattered food throughout the space instead of placing it in a single pile. Within months, the gorillas spent far more time exploring and foraging and far less time sitting idle. The keepers also observed fewer conflicts among the animals, perhaps because food was no longer concentrated in one spot that dominant gorillas could control.
CI:: || A more natural habitat with scattered food made zoo gorillas more active and may have reduced conflicts among them. || The gorillas preferred their old concrete habitat. || Dominant gorillas ate all the food in the new habitat. || Zoo keepers stopped feeding the gorillas after the redesign. >> The changes increased foraging and exploration and coincided with fewer conflicts.
TS: Which choice best describes the overall structure of the text? || It describes changes to a habitat and then reports the effects of those changes. || It compares gorillas in the wild with gorillas in zoos. || It explains how gorillas choose their leaders. || It argues that zoos should release gorillas into the wild. >> The redesign, then more activity and fewer conflicts.
IN: Based on the text, conflicts among the gorillas were probably more common before the redesign because || dominant gorillas could control access to food placed in one pile. || the gorillas had too much space to explore. || the logs and grasses made the gorillas nervous. || the keepers scattered food throughout the habitat. >> The keepers link fewer conflicts to food no longer being "concentrated in one spot."

P: Early photographs often show people with stiff, serious expressions. It is tempting to conclude that people in the nineteenth century were more solemn than people today. But early cameras required subjects to stay perfectly still for many seconds, sometimes minutes, and holding a natural smile that long is difficult. Many portrait traditions of the time also associated dignity with a calm, composed face.
CI:: || The serious expressions in early photographs likely reflect technical limits and portrait customs rather than people's personalities. || People in the nineteenth century rarely smiled in daily life. || Early cameras could capture images almost instantly. || Photographers in the nineteenth century encouraged subjects to smile. >> The text offers long exposure times and portrait traditions as explanations.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It presents a tempting conclusion that the rest of the text challenges. || It describes how early cameras worked. || It provides evidence that supports the final sentence. || It explains why portrait traditions valued calm faces. >> "It is tempting to conclude" is followed by "But," which offers other explanations.
IN: Based on the text, if early cameras had captured images in a fraction of a second, old photographs would most likely show || more natural expressions, though portrait customs might still favor composed faces. || exactly the same stiff expressions for the same reasons. || only people who were smiling. || no people at all. >> Removing the long exposure removes one reason for stiffness, but customs remain.

P: A city once required new buildings to include large parking garages, reasoning that plenty of parking would reduce traffic on crowded streets. Urban researchers later studied the policy's effects. They found that abundant, cheap parking encouraged more people to drive downtown, adding to congestion, while the garages took up space that could have been used for housing or shops. After reviewing the research, the city eliminated the requirement in its central district.
CI:: || Research showed that a city's parking requirement increased driving and used valuable space, leading the city to end the rule downtown. || Building more parking garages reduced traffic congestion downtown. || The city required new buildings to include housing instead of parking. || Urban researchers recommended building larger parking garages. >> The policy's reasoning, the research findings, and the city's decision.
TS: Which choice best describes the overall structure of the text? || It describes a policy and its reasoning, presents research on its effects, and reports the resulting change. || It compares traffic in two cities over several decades. || It explains how parking garages are designed. || It argues that no one should drive downtown. >> Policy, research findings, and policy change.
IN: Based on the text, the city's original reasoning about parking turned out to be || the opposite of what the policy actually produced. || fully supported by the research. || irrelevant to downtown traffic. || the reason more housing was built. >> Officials expected less traffic, but parking "encouraged more people to drive downtown."

P: The following text is from a short story. Priya had practiced the violin piece for months, but in the recital hall her hands shook so badly that the first notes wavered. She thought of stopping. Then she noticed her grandfather in the third row, eyes closed, head tilted slightly, the way he listened to the radio on Sunday mornings. She drew the bow again, and this time the note held steady.
CI:: || Seeing her grandfather listen calmly helps Priya overcome her nervousness during a recital. || Priya decides to stop playing because she is too nervous. || Priya's grandfather falls asleep during the recital. || Priya has not practiced enough for her recital. >> After noticing him, "this time the note held steady."
TS: Which choice best describes the function of the third sentence in the text as a whole? || It describes a moment that marks a turning point in Priya's performance. || It explains why Priya began playing the violin. || It describes the recital hall in detail. || It reveals that Priya's grandfather disapproves of her playing. >> The image of her grandfather comes just before her playing steadies.
IN: Based on the text, Priya's grandfather's posture most likely reminds her of || moments of relaxed, attentive listening that feel familiar and comforting. || the strict instructions of her violin teacher. || a time when he was disappointed in her. || the radio program she dislikes. >> It echoes how he listened "on Sunday mornings," a familiar scene.

P: Many historians once believed that a certain medieval trade route declined because of a single event: the collapse of a major bridge. More recent work draws on tax records, merchant letters, and archaeological surveys of roadside inns. Together they suggest a gradual decline that began decades before the bridge fell, as new sea routes offered cheaper and faster ways to move goods. The bridge's collapse, in this view, hastened a change already under way.
CI:: || Newer evidence suggests that a trade route declined gradually because of competition from sea routes, not solely because a bridge collapsed. || The trade route declined only because a major bridge collapsed. || Sea routes were more expensive than land routes in the Middle Ages. || Historians have found no records related to the trade route. >> The text replaces the single-event explanation with a gradual decline linked to sea routes.
TS: Which choice best describes the overall structure of the text? || It presents an earlier explanation, describes new evidence, and offers a revised explanation. || It describes how medieval bridges were built. || It lists goods carried along the trade route. || It argues that archaeological surveys are unreliable. >> Old view (bridge), new sources, revised view (gradual decline).
IN: Based on the text, which finding would best support the more recent view of the trade route? || Tax records showing that trade along the route was already falling well before the bridge collapsed || A letter describing the day the bridge collapsed || Evidence that the bridge was rebuilt soon after it fell || Records showing that sea routes were rarely used in the period >> The recent view holds that decline began decades before the collapse.

P: Crows are known for their intelligence, but a study of city crows revealed a particularly surprising ability. Researchers wearing a distinctive mask trapped and released a few crows. For years afterward, crows in the area scolded and dive-bombed anyone wearing that mask, including crows that had never been trapped, while ignoring researchers in other masks. The birds had apparently learned to recognize a dangerous face and passed that knowledge to others.
CI:: || City crows learned to recognize a mask associated with danger and apparently shared that knowledge with other crows. || Crows attack every person who wears a mask. || Only crows that had been trapped reacted to the mask. || Crows forget threatening experiences within a few days. >> Even crows never trapped scolded the mask wearer for years.
TS: Which choice best describes the function of the phrase "including crows that had never been trapped" in the text? || It indicates that the reaction to the mask spread beyond the crows that had direct experience with it. || It suggests that the researchers trapped every crow in the area. || It explains how the researchers chose the mask. || It shows that the crows reacted to all masks equally. >> Untrapped crows reacting supports the idea that knowledge was passed on.
IN: Based on the text, if the researchers had trapped the crows while wearing no mask, the crows would most likely have || had a harder time identifying which people to avoid later. || attacked every person in the city. || become unable to recognize any faces. || stopped living in the area immediately. >> The distinctive mask gave the crows a clear feature to recognize.

P: In the 1950s, engineers designing a new highway through a valley proposed cutting down an old grove of oak trees. Local residents objected, noting that the grove was among the last remnants of the forest that once covered the valley. After months of debate, the engineers shifted the highway's route slightly to the east. The adjustment added a few hundred meters to the road, but today the grove is a protected park crossed by walking trails.
CI:: || Residents' objections led engineers to reroute a highway, preserving an old oak grove that is now a park. || Engineers cut down the oak grove to build a shorter highway. || The valley's forest was fully preserved in the 1950s. || Residents asked engineers to build a highway through the grove. >> The debate ended with a rerouted highway and a preserved grove.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It describes a cost of the decision and its lasting benefit. || It explains why residents objected to the plan. || It describes the original route of the highway. || It argues that highways should never be rerouted. >> A slightly longer road, but a protected park today.
IN: Based on the text, the residents most likely valued the grove because || it was a rare surviving part of the valley's original forest. || it provided the shortest route for the highway. || it had recently been planted by the town. || it blocked the view of the new highway. >> It was "among the last remnants of the forest."

P: Children learning to read often sound out unfamiliar words letter by letter. Skilled adult readers, by contrast, recognize most familiar words instantly as whole units. Researchers studying eye movements have found, however, that even skilled readers slow down and fix their gaze longer on rare or unfamiliar words, suggesting that the older strategy of decoding piece by piece never disappears entirely but is used when needed.
CI:: || Even skilled readers fall back on slower, piece-by-piece decoding when they encounter unfamiliar words. || Adults sound out every word they read. || Children recognize all words instantly as whole units. || Eye movements are unrelated to reading skill. >> Skilled readers slow down on unfamiliar words, showing the old strategy remains available.
TS: Which choice best describes the overall structure of the text? || It contrasts two reading strategies and then presents a finding that complicates the contrast. || It describes a reading lesson and evaluates its success. || It lists several methods for teaching reading. || It explains why children dislike reading aloud. >> Children decode, adults recognize words, "however" skilled readers still decode when needed.
IN: Based on the text, a skilled reader encountering the rare word "sesquipedalian" would most likely || pause longer on the word than on common words. || recognize it instantly without slowing down. || skip the sentence entirely. || read the word faster than familiar words. >> Skilled readers "fix their gaze longer on rare or unfamiliar words."

P: When a regional orchestra noticed that few young people attended its concerts, it began offering a free "pay what you wish" performance each month. Critics warned that people would come once for free and never buy full-price tickets. Two years of sales data showed a different pattern: many first-time attendees at the free concerts later returned to regular concerts, and the average age of subscribers dropped by nearly a decade.
CI:: || An orchestra's free monthly concerts attracted younger audiences who later returned for regular performances. || The orchestra stopped charging for all of its concerts. || Critics were correct that free concerts would reduce ticket sales. || Older audiences stopped attending the orchestra's concerts. >> Sales data showed returning attendees and younger subscribers.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It presents a prediction that the data described in the final sentence contradict. || It explains why young people rarely attended concerts. || It describes how the orchestra set its ticket prices. || It provides evidence that supports the orchestra's plan. >> Critics predicted no return visits; data showed many returned.
IN: Based on the text, the drop in subscribers' average age most likely indicates that || younger people who first attended free concerts went on to subscribe. || the orchestra lost all of its older subscribers. || subscriptions became more expensive. || the free concerts were attended mostly by older people. >> First-time attendees returned, and subscribers became younger on average.

P: The following text is from a memoir. My mother kept a garden that never looked like the ones in magazines. Tomato cages leaned at angles, the beans climbed a fence made from old bed frames, and the marigolds grew wherever their seeds happened to fall. Visitors sometimes offered to help her "fix it up." She would smile, hand them a basket, and send them out to pick whatever was ripe.
CI:: || The narrator's mother valued her garden's usefulness and abundance more than its neat appearance. || The narrator's mother wanted her garden to look like those in magazines. || Visitors refused to help in the narrator's mother's garden. || The narrator's mother grew only flowers. >> Instead of tidying, she sends visitors to pick ripe food.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It provides details that illustrate how the garden differed from magazine gardens. || It explains why the mother started gardening. || It describes the mother's plan to rebuild the garden. || It presents a visitor's criticism of the garden. >> Leaning cages, bed-frame fence, and scattered marigolds show its untidiness.
IN: Based on the text, the mother's response to offers to "fix up" the garden suggests that she || did not see the garden's untidiness as a problem. || was embarrassed by the garden. || planned to hire a gardener. || wanted visitors to leave quickly. >> She smiles and invites them to harvest rather than tidy.

P: Many coastal towns once dumped the shells left over from seafood processing into landfills. In one bay, a restoration group began collecting oyster shells from restaurants and returning them to the water in mesh bags. Young oysters need hard surfaces to attach to, and the recycled shells gave them a place to settle. Within a few years, new reefs had formed, filtering the water and providing habitat for fish and crabs.
CI:: || Recycling oyster shells back into a bay gave young oysters a place to grow, leading to new reefs that benefit the ecosystem. || Restaurants in the bay stopped serving oysters. || Oyster shells should always be sent to landfills. || Fish and crabs prevent oysters from forming reefs. >> Returned shells provided surfaces for young oysters, creating reefs.
TS: Which choice best describes the function of the third sentence in the text as a whole? || It explains why returning shells to the water helps oysters. || It describes how restaurants prepare oysters. || It presents a problem with the restoration project. || It compares oysters with other shellfish. >> Young oysters need hard surfaces, which the shells provide.
IN: Based on the text, a bay with muddy bottoms and no hard surfaces would most likely || have difficulty supporting the growth of new oyster reefs. || develop oyster reefs faster than other bays. || have clearer water than a bay with reefs. || attract more fish than a bay with reefs. >> Young oysters "need hard surfaces to attach to."

P: For most of history, sailors navigated by the stars, but measuring longitude at sea remained extremely difficult. Longitude depends on knowing the time at a reference location while at sea, and ordinary clocks of the era lost accuracy on rolling ships. The problem was largely solved when clockmakers designed timekeepers precise and sturdy enough to keep accurate time through storms and temperature changes, allowing navigators to calculate their position far more reliably.
CI:: || Accurate, durable clocks solved the long-standing problem of determining longitude at sea. || Sailors stopped using the stars to navigate. || Longitude can be measured without knowing the time. || Ordinary clocks worked well on ships during storms. >> The need for accurate time and the invention of sturdy clocks.
TS: Which choice best describes the overall structure of the text? || It identifies a problem, explains why it was difficult, and describes how it was solved. || It describes the life of a famous sailor. || It compares navigation by stars with navigation by maps. || It argues that clocks were more important than ships. >> Longitude problem, reason (clocks on ships), solution (precise timekeepers).
IN: Based on the text, before reliable sea clocks existed, sailors were most likely || often uncertain about how far east or west they had traveled. || unable to see the stars at night. || always certain of their exact location. || forbidden from sailing in storms. >> Longitude measurement "remained extremely difficult" without accurate time.

P: A school district tested a program in which high school students tutored younger children in reading twice a week. As expected, the younger children's reading scores improved. Less expected was the effect on the tutors: their own reading comprehension scores rose more than those of classmates who did not participate, and many reported feeling more confident speaking in class.
CI:: || A tutoring program helped not only the younger children being tutored but also the high school students who served as tutors. || Only the younger children benefited from the tutoring program. || High school tutors reported feeling less confident after the program. || The program was canceled because reading scores fell. >> Both groups improved, with an unexpected benefit for tutors.
TS: Which choice best describes the function of the third sentence in the text as a whole? || It presents an unexpected finding about the program's effects. || It restates the expected result described in the second sentence. || It explains how tutors were selected. || It describes a weakness of the program. >> "Less expected was the effect on the tutors."
IN: Based on the text, the tutors' improved comprehension most likely resulted in part from || explaining and practicing reading skills while helping younger students. || receiving reading tutoring from younger children. || taking extra reading classes instead of tutoring. || skipping their own classes. >> Tutoring required them to work with reading material and explain it.

P: The following text is from a novel. The letter had sat unopened on Tomas's desk for three days. He knew the university's decision was inside. Each morning he picked it up, weighed it in his hand as if its thickness could tell him the answer, and set it down again. On the fourth morning his little sister marched in, tore it open before he could stop her, and read the first line aloud with a shriek of delight.
CI:: || Tomas is too anxious to open a letter containing a university decision until his sister opens it and reveals good news. || Tomas throws away the letter without reading it. || Tomas's sister is disappointed by the university's decision. || Tomas opens the letter immediately and shares the news. >> He avoids opening it for days; his sister's "shriek of delight" suggests good news.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It breaks the tension built up in the earlier sentences. || It explains why Tomas applied to the university. || It describes Tomas's desk in detail. || It reveals that the letter was sent to the wrong person. >> After days of hesitation, the sister opens the letter.
IN: Based on the text, Tomas most likely "weighed it in his hand" because he || hoped the letter's size might reveal whether the news was good or bad. || needed to know how much postage it had required. || planned to mail the letter to someone else. || wanted to see whether his sister had opened it. >> "As if its thickness could tell him the answer."

P: Wind turbines are often placed on ridges and hilltops, where winds are strongest. Some wildlife biologists raised concerns that turbines in such locations could harm migrating birds of prey, which ride the same updrafts along ridges. A study tracking hawks and eagles near one wind farm found that collisions were concentrated at a few turbines positioned directly in the birds' main flight corridors. Shutting down those turbines during peak migration weeks reduced collisions sharply while cutting the farm's yearly energy production by less than one percent.
CI:: || Temporarily shutting down a few turbines in birds' main flight paths greatly reduced collisions with little loss of energy production. || Wind farms should not be built on ridges or hilltops. || Birds of prey avoid wind farms entirely. || All turbines at the wind farm caused equal numbers of collisions. >> Collisions were concentrated at a few turbines, and targeted shutdowns helped.
TS: Which choice best describes the overall structure of the text? || It explains a concern, reports a finding that clarifies the problem, and describes an effective solution. || It compares energy production at several wind farms. || It describes the migration routes of hawks in detail. || It argues that wind energy is too harmful to continue. >> Concern, concentrated collisions, targeted shutdowns.
IN: Based on the text, the solution was effective mainly because || the collisions occurred at only a small number of identifiable turbines. || the birds stopped migrating along the ridge. || every turbine was removed from the ridge. || the farm produced more energy during migration. >> Knowing where collisions occurred allowed a narrow, low-cost fix.

P: Some languages have many more words for colors than others. For years, researchers debated whether speakers of such languages actually perceive colors differently. In one experiment, speakers of a language with separate words for light blue and dark blue were slightly faster at telling those two shades apart than speakers of a language with only one word for blue. The difference was small, but it suggests that the words people use may subtly influence how quickly they notice distinctions.
CI:: || An experiment suggests that having separate words for two shades may make speakers slightly faster at distinguishing them. || Speakers of all languages perceive colors in exactly the same way. || Some languages have no words for colors at all. || People who speak two languages cannot tell shades of blue apart. >> Separate words for light and dark blue were linked to slightly faster discrimination.
TS: Which choice best describes the function of the phrase "The difference was small" in the text? || It qualifies the finding so that its conclusion is not overstated. || It indicates that the experiment failed. || It contradicts the claim in the first sentence. || It explains how the shades of blue were chosen. >> It limits the strength of the claim, which uses "may subtly influence."
IN: Based on the text, the researchers would most likely agree that || language may have a modest effect on color perception, but it does not determine what colors people can see. || speakers with one word for blue cannot see dark blue. || language has no connection to perception. || the experiment proved that language completely controls perception. >> The effect was "small" and "subtle."
"""
