"""Passage units, batch 8 (format documented in passage_data1.py). Original texts; people and studies are illustrative."""

UNITS = """
P: Some nutrition writers claim that eating fat makes people gain weight more than eating any other nutrient.
P2: Fat contains more calories per gram than protein or carbohydrates, but studies comparing low-fat and low-carbohydrate diets with equal calories have found similar weight loss on average. What matters most for weight appears to be total calories and whether people can stick with a diet over time.
CT:: || By arguing that when calories are equal, low-fat diets do not produce more weight loss, and that total calories and adherence matter most || By agreeing that fat causes more weight gain than any other nutrient regardless of calories || By claiming that fat contains fewer calories than protein || By arguing that diets should contain no carbohydrates >> Equal-calorie diets produced similar results.
CT: The author of Text 2 would most likely agree with Text 1 that fat || contains more calories per gram than protein or carbohydrates. || is the only cause of weight gain. || should be eliminated from diets. || has no calories. >> "Fat contains more calories per gram."
CT: Based on Text 2, an important factor for weight loss is || whether people can stick with a diet over time. || whether a diet is low in fat specifically. || the time of day meals are eaten. || the color of foods. >> "Whether people can stick with a diet over time."

P: When a city began offering free swimming lessons to children in neighborhoods without public pools, officials bused students to a recreation center across town. Participation was lower than expected. Surveys found that many families could not accommodate the long bus rides after school. The city then set up temporary pools at neighborhood schools during the summer, and enrollment tripled.
CI:: || A free swimming program attracted far more children once lessons were moved closer to their neighborhoods. || Families were uninterested in swimming lessons. || The city closed its recreation center. || Children preferred long bus rides to swimming lessons. >> Moving lessons to neighborhood schools tripled enrollment.
TS: Which choice best describes the overall structure of the text? || It describes a program, a problem with participation and its cause, and a change that addressed it. || It compares swimming with other sports. || It explains how temporary pools are built. || It argues that swimming lessons should cost money. >> Low participation, survey findings, and relocation.
IN: Based on the text, the main barrier to participation was most likely || the time and difficulty of traveling to the lessons. || the cost of the lessons. || a lack of interest in learning to swim. || poor teaching at the recreation center. >> Families "could not accommodate the long bus rides."

P: The following text is from a novel. The old clock in the hallway had stopped at 4:17 the day Grandfather died, and no one had wound it since. Years passed. Then, on the morning of her own wedding, Tessa found her father standing in front of it with the key in his hand. He wound it slowly, and as the pendulum began to swing, he said, without turning around, "It's time."
CI:: || On his daughter's wedding day, Tessa's father restarts a clock that had stopped when his own father died, marking a new beginning. || Tessa's father throws away the old clock. || The clock breaks on the day of Tessa's wedding. || Tessa winds the clock to remember her grandfather. >> Winding the clock marks moving forward.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It establishes the clock's connection to a loss, giving meaning to the father's later action. || It explains how clocks are wound. || It describes the wedding ceremony. || It reveals Tessa's age. >> The clock stopped when Grandfather died.
IN: Based on the text, the father's words "It's time" most likely have || both a literal meaning about the clock and a figurative meaning about moving on. || only a meaning about being late for the wedding. || no connection to the clock. || an angry tone toward Tessa. >> The restarted clock and the wedding suggest a new chapter.

P: Researchers studying how people navigate cities found that residents who relied heavily on GPS directions formed less accurate mental maps of their neighborhoods than residents who navigated without it. When asked to draw maps or estimate distances between landmarks, GPS users made more errors, though they reached destinations just as reliably.
CI:: || Relying on GPS was linked to less accurate mental maps, even though GPS users reached destinations reliably. || GPS users got lost more often than other residents. || Residents who navigated without GPS could not reach destinations. || GPS improves people's mental maps. >> GPS users made more mapping errors but arrived reliably.
TS: Which choice best describes the function of the final clause, beginning with "though," in the text? || It notes that GPS users' ability to reach destinations was not impaired. || It explains how the researchers drew maps. || It suggests that the study's findings were incorrect. || It describes which GPS devices were used. >> Their spatial knowledge differed, not their arrival.
IN: Based on the text, a GPS user whose phone battery died in an unfamiliar part of town might || have more difficulty finding the way than someone who usually navigates without GPS. || find the way more easily than other residents. || draw a perfect map of the area. || never have used GPS before. >> Weaker mental maps would make navigation harder without GPS.

P: For centuries, scholars assumed that a certain carved stone monument was a religious object. Recent analysis of the carvings revealed markings that align with the positions of the sun at the solstices and equinoxes. Some researchers now propose that the monument may also have served as a calendar, helping communities plan planting and festivals.
CI:: || New analysis suggests that a carved monument long thought to be religious may also have served as a calendar. || The monument has been proven to be only a religious object. || The carvings show the positions of stars at midnight. || Communities never used calendars for planting. >> Solar alignments suggest a calendar function.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It presents new evidence that leads to a revised interpretation. || It restates the traditional interpretation. || It describes how the monument was carved. || It explains why festivals were held. >> Solar markings prompt the calendar idea.
IN: Based on the text, the word "also" in the final sentence suggests that the researchers || do not necessarily reject the monument's religious significance. || believe the monument had no religious purpose. || think the monument was built recently. || doubt that the markings align with the sun. >> "Also served" adds a function.

P: When a hospital began having pharmacists review patients' medication lists at discharge, errors in prescriptions sent home with patients dropped sharply. Pharmacists often caught medications that duplicated one another or could interact harmfully, problems that busy doctors had missed. Readmissions related to medication problems also declined.
CI:: || Adding pharmacist review at discharge reduced medication errors and related readmissions. || Pharmacists caused more prescription errors. || Doctors never make medication errors. || Readmissions increased after the change. >> Pharmacists caught duplications and interactions.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It explains how pharmacists reduced errors. || It describes the hospital's history. || It presents a drawback of the program. || It explains why patients were readmitted before the hospital opened. >> They caught duplications and interactions.
IN: Based on the text, the decline in readmissions most likely resulted from || fewer patients going home with problematic medication combinations. || doctors prescribing more medications. || patients staying in the hospital longer. || the hospital refusing readmissions. >> Fewer errors meant fewer medication-related problems.

P: The following text is adapted from an essay. As a child I believed that adults knew exactly what they were doing. My parents paid bills, fixed leaks, and made decisions with what looked like total confidence. It was only when I became an adult myself that I realized how much of that confidence was performance, a steady face kept up so that children would feel safe while the grown-ups figured things out.
CI:: || The writer realizes as an adult that her parents' apparent confidence often masked uncertainty meant to reassure their children. || The writer's parents never paid bills. || The writer still believes adults always know what they are doing. || The writer's parents were unable to fix leaks. >> Confidence was partly "performance."
TS: Which choice best describes the overall structure of the text? || It describes a childhood belief and then the adult realization that revised it. || It lists household chores in order. || It compares two families. || It argues that children should pay bills. >> Belief, then realization.
IN: Based on the text, the writer suggests that her parents appeared confident mainly to || help their children feel secure. || impress their neighbors. || avoid doing household tasks. || hide their wealth. >> So that "children would feel safe."

P: Ecologists found that frogs in ponds near busy roads call at higher pitches than frogs of the same species in quiet ponds. Traffic noise is concentrated at low frequencies, and higher-pitched calls may be easier for other frogs to hear over that noise. However, females of the species generally prefer lower-pitched calls, which typically come from larger males.
CI:: || Frogs near roads call at higher pitches, which may help them be heard over traffic but could make their calls less attractive to females. || Frogs near roads call at lower pitches. || Traffic noise is concentrated at high frequencies. || Females prefer higher-pitched calls. >> Higher pitch aids audibility but conflicts with female preference.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It introduces a possible drawback of the change in calling behavior. || It explains why roads are noisy. || It supports the idea that higher calls attract more mates. || It describes how frogs lay eggs. >> Females prefer lower calls.
IN: Based on the text, male frogs near busy roads may face a trade-off between || being heard over traffic and sounding attractive to females. || finding food and avoiding predators. || calling at night and calling during the day. || living in ponds and living on land. >> Higher pitch helps audibility but lowers appeal.

P: A company that produces breakfast cereal tested whether placing a cartoon character on the box affected children's choices. In a taste test, children were given the same cereal in two boxes, one with a character and one without. Most children said the cereal from the character box tasted better, even though the cereal was identical.
CI:: || Children rated identical cereal as tastier when it came from a box featuring a cartoon character. || The cereals in the two boxes tasted different. || Children preferred boxes without characters. || Cartoon characters improve the nutrition of cereal. >> Packaging influenced perceived taste.
TS: Which choice best describes the function of the phrase "even though the cereal was identical" in the text? || It emphasizes that the difference in ratings came from the packaging, not the food. || It explains how the cereal was made. || It suggests the test was unfair. || It describes the children's ages. >> Identical food means packaging caused the difference.
IN: Based on the text, the test suggests that children's judgments of taste can be || influenced by factors unrelated to the food itself. || completely unaffected by packaging. || based only on nutritional information. || identical for all foods. >> Packaging changed taste ratings.

P: When scientists first proposed that the continents slowly move, many geologists objected because no one could explain what force could push such enormous masses. Decades later, maps of the ocean floor revealed long underwater mountain ranges where new crust forms and spreads outward. This discovery provided a mechanism, and the idea of moving continents gained broad acceptance.
CI:: || The discovery of seafloor spreading supplied a mechanism that led to acceptance of the idea that continents move. || Geologists immediately accepted the idea that continents move. || Ocean floor maps disproved continental movement. || No underwater mountain ranges exist. >> A mechanism was needed and later found.
TS: Which choice best describes the overall structure of the text? || It describes an idea, the main objection to it, and the evidence that eventually addressed the objection. || It describes how maps are made. || It compares mountains on land and underwater. || It argues that the continents never moved. >> Proposal, objection, and mechanism discovered.
IN: Based on the text, geologists initially rejected the idea mainly because || it lacked an explanation of how continents could move. || maps showed continents in fixed positions. || the idea was proposed by ocean explorers. || moving continents would be too fast to observe. >> "No one could explain what force could push" them.

P: A school district that shortened its summer break and added more short breaks throughout the year hoped to reduce learning loss. Teachers reported spending less time reviewing material in the fall. Some families, however, struggled to find child care during the new breaks, which did not align with the schedules of nearby districts.
CI:: || A revised school calendar reduced review time for teachers but created child care challenges for some families. || The new calendar increased summer learning loss. || All families found the new schedule convenient. || Teachers spent more time reviewing material. >> Benefits for teaching, drawbacks for child care.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It presents a drawback of the change. || It explains why the district adopted the change. || It supports the teachers' reports. || It describes the length of the new breaks. >> Child care problems.
IN: Based on the text, the child care difficulties were made worse by the fact that || other districts' breaks occurred at different times. || the summer break was longer. || teachers worked during the breaks. || the district had no schools. >> Breaks "did not align with the schedules of nearby districts."

P: The following text is from a short story. Kenji's father spoke little English and rarely came to school events. So when Kenji saw him standing at the back of the auditorium during the science fair, still in his work uniform, Kenji nearly dropped his poster. His father did not ask questions or read the display. He simply stood beside it for the entire evening, nodding at every visitor who stopped.
CI:: || Kenji's father shows his support by attending the science fair and staying beside Kenji's project all evening. || Kenji's father refuses to attend the science fair. || Kenji's father explains the project to every visitor. || Kenji is embarrassed that his father attends. >> His quiet presence expresses support.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It explains why the father's attendance is surprising. || It describes Kenji's science project. || It explains why the father wears a uniform. || It reveals the winner of the science fair. >> He rarely came to school events.
IN: Based on the text, the father's "still in his work uniform" suggests that he || came directly from work to be there. || planned to work at the science fair. || did not own other clothes. || was a judge at the fair. >> He arrived without changing, likely from work.

P: Biologists studying hibernating ground squirrels found that the animals periodically warm themselves up during hibernation, raising their body temperature for about a day before cooling down again. These arousals use a large share of the energy the squirrels spend over the winter. Researchers suspect the arousals may be necessary for functions such as sleep or immune activity that cannot occur at very low body temperatures.
CI:: || Hibernating ground squirrels periodically rewarm despite the energy cost, possibly to allow essential body functions. || Ground squirrels stay at the same low temperature throughout hibernation. || Arousals save energy for squirrels. || Squirrels stop hibernating after one arousal. >> Costly arousals may support vital functions.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It highlights the energy cost of the arousals, making their purpose puzzling. || It explains how squirrels find food. || It describes the squirrels' burrows. || It proves that arousals are unnecessary. >> A large energy share raises the question of why they occur.
IN: Based on the text, arousals would be unlikely to continue if they || provided no benefit to the squirrels. || used a large amount of energy but served essential functions. || occurred every few weeks. || happened during winter. >> Researchers assume arousals serve necessary functions.

P: A museum that offered free admission one evening a month found that the free nights attracted visitors who had never been to the museum before, including many families with young children. Membership sign-ups also rose after these evenings, suggesting that some first-time visitors returned as paying members.
CI:: || Free monthly evenings brought new visitors to a museum, some of whom later became members. || Free evenings discouraged people from becoming members. || Only longtime members attended free evenings. || The museum stopped offering free admission. >> New visitors and rising membership.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It describes a further effect that suggests free evenings had lasting benefits. || It describes the museum's exhibits. || It explains why families have young children. || It contradicts the first sentence. >> Membership sign-ups rose.
IN: Based on the text, the museum most likely viewed the free evenings as || a way to attract new audiences who might become long-term supporters. || a loss with no benefits. || an event only for existing members. || a reason to raise ticket prices for families. >> They attracted first-time visitors and new members.

P: Scientists examining ice cores from Greenland found layers of dust and chemicals that correspond to large volcanic eruptions. By counting annual layers of snow, much like tree rings, researchers could date the eruptions and compare them with historical records of cold summers and poor harvests. Several recorded famines coincided with volcanic layers in the ice.
CI:: || Ice cores allowed scientists to date volcanic eruptions and link some of them to historical cold summers and famines. || Volcanic eruptions never affect climate. || Ice cores contain no annual layers. || Tree rings are found in Greenland's ice. >> Dated layers matched historical famines.
TS: Which choice best describes the overall structure of the text? || It describes what ice cores contain, how they were dated, and what the comparison with historical records revealed. || It explains how volcanoes form. || It compares Greenland and Antarctica. || It argues that famines are caused only by wars. >> Contents, dating method, and findings.
IN: Based on the text, the link between volcanic layers and famines suggests that eruptions may || have cooled climates enough to harm harvests. || have caused warmer summers. || have no connection to weather. || have occurred only in Greenland. >> Famines coincided with volcanic layers and cold summers.

P: When a small town's only doctor retired, residents feared they would lose local medical care. The town partnered with a nearby hospital to set up video appointments at the library, staffed by a nurse who could take measurements during calls. Many residents were initially skeptical, but within a year most routine visits happened this way, and patients reported saving hours of travel.
CI:: || After losing its doctor, a town used library-based video appointments that became widely used and saved patients travel time. || Residents refused to use video appointments. || The town hired a new doctor immediately. || The library stopped hosting appointments. >> Video visits became common and convenient.
TS: Which choice best describes the function of the phrase "Many residents were initially skeptical" in the text? || It indicates early doubts that were later overcome. || It explains why the doctor retired. || It describes the nurse's training. || It shows that the program failed. >> Skepticism gave way to widespread use.
IN: Based on the text, the nurse's presence during calls was likely important because it || allowed measurements that a remote doctor could not take alone. || replaced the need for a doctor entirely. || kept the library quiet. || taught residents to use computers. >> The nurse "could take measurements during calls."

P: Researchers analyzing thousands of job postings found that ads using words such as "competitive" and "dominant" attracted fewer applications from women than ads describing the same jobs with words such as "collaborative" and "supportive." When a company revised its ads to use more neutral language, the share of women applying increased.
CI:: || The wording of job ads appeared to influence how many women applied, and neutral wording increased applications from women. || Women applied equally regardless of ad wording. || Revised ads reduced applications from women. || Job postings rarely use descriptive words. >> Wording affected who applied.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It describes an intervention that supports the pattern found in the analysis. || It explains why companies post jobs online. || It contradicts the first finding. || It describes the salary for the jobs. >> Revised ads increased women's applications.
IN: Based on the text, a company hoping to attract a wide range of applicants would most likely benefit from || reviewing the language used in its job ads. || using more words like "dominant." || removing all job descriptions. || posting fewer job ads. >> Wording influenced applicant pools.

P: The following text is from a poem. The river does not remember / the mountain it came from, / nor does it know the ocean / where it will someday run. / It only knows the stones it turns / and the reeds along its way, / and it sings to them the one song / it has: today, today.
CI:: || The poem depicts a river that is concerned only with its present surroundings, not its past or future. || The river longs to return to the mountain. || The river is afraid of reaching the ocean. || The river carries stones to the ocean. >> It knows only the stones and reeds of "today."
TS: Which choice best describes the overall structure of the poem? || It describes what the river does not know and then what it does know. || It narrates a journey from the ocean to the mountain. || It compares two rivers. || It describes a storm and its aftermath. >> Past and future unknown, present known.
IN: Based on the text, the river's "one song" most likely represents || attention to the present moment. || memories of the mountain. || fears about the future. || the sound of the ocean. >> "Today, today."

P: Engineers testing self-driving cars found that the vehicles handled highway driving well but struggled in situations requiring interpretation of human behavior, such as a pedestrian waving a driver forward or a cyclist making eye contact before turning. Human drivers rely on such informal signals, which are difficult to program.
CI:: || Self-driving cars performed well on highways but had difficulty interpreting informal human signals that drivers rely on. || Self-driving cars struggled most on highways. || Pedestrians never signal to drivers. || Informal human signals are easy to program. >> Highways were manageable, but human cues were hard.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It explains why the situations described earlier are challenging for self-driving cars. || It describes how highways are built. || It presents the results of highway tests. || It argues that cyclists should not make eye contact. >> Informal signals "are difficult to program."
IN: Based on the text, a self-driving car would most likely have the greatest difficulty || at a crowded crosswalk where pedestrians gesture to drivers. || on an empty highway in clear weather. || driving in a straight line. || following marked lanes. >> Human gestures are hard for the vehicles.

P: Some islands have species of birds that cannot fly, even though their ancestors could. Biologists suggest that on islands without ground predators, flying offered few advantages while requiring a great deal of energy. Over many generations, birds that spent less energy on flight muscles and more on other traits may have survived and reproduced more successfully.
CI:: || Flightless island birds may have evolved because flying offered little advantage where ground predators were absent. || Island birds lost flight because they were hunted by predators. || All birds on islands can fly. || Flying requires little energy. >> Without predators, flight's costs outweighed its benefits.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It offers an explanation for the loss of flight described in the first sentence. || It describes the diet of island birds. || It explains how islands form. || It contradicts the first sentence. >> Few advantages and high energy costs.
IN: Based on the text, if predators that hunt on the ground were introduced to such an island, the flightless birds would most likely || be at greater risk than birds that can fly. || quickly regain the ability to fly. || be unaffected. || begin hunting the predators. >> They evolved in the absence of ground predators.

P: When a library replaced its self-checkout machines with staffed desks for a trial period, checkout times increased slightly. Surveys, however, showed that patrons asked librarians many more questions, often about finding books, using databases, or getting help with job applications. Several patrons said they had not realized librarians could help with such tasks.
CI:: || Staffed checkout desks slowed checkout slightly but led patrons to ask librarians for many kinds of help. || Self-checkout machines led to more questions. || Patrons refused to use staffed desks. || Librarians could not help with job applications. >> More interaction revealed librarians' services.
TS: Which choice best describes the function of the word "however" in the text? || It signals a benefit that offsets the slight increase in checkout time. || It indicates that the trial failed. || It introduces the library's history. || It explains how machines work. >> Slower checkout, but more assistance.
IN: Based on the text, patrons who used self-checkout machines had probably || been less aware of the help librarians could offer. || asked librarians more questions. || checked out fewer books. || waited in longer lines. >> Some "had not realized librarians could help."
"""
