"""Passage units, batch 12 (format documented in passage_data1.py). Original texts; people and studies are illustrative."""

UNITS = """
P: When a city began lending air conditioners to elderly residents during heat waves, emergency room visits for heat-related illness among older adults dropped noticeably. Social workers delivering the units also checked on residents' health and connected several with other services, such as meal delivery, that they had not known about.
CI:: || A program lending air conditioners to older residents reduced heat-related emergency visits and connected residents with other services. || Heat-related emergency visits rose after the program began. || Social workers refused to deliver air conditioners. || Older residents already knew about every available service. >> Fewer ER visits plus additional connections.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It describes an additional benefit that came from the program's deliveries. || It explains how air conditioners cool rooms. || It presents a drawback of the program. || It describes the city's weather. >> Health checks and service referrals.
IN: Based on the text, delivering the air conditioners in person was valuable partly because it || allowed social workers to identify other needs residents had. || made the air conditioners work better. || replaced the need for meal delivery. || prevented heat waves. >> Social workers connected residents with services.

P: The following text is from a novel. Every morning, Omar's father left a folded note in his lunch bag, usually a joke so bad that Omar groaned aloud in the cafeteria. By high school, Omar pretended to be embarrassed and threw the notes away before his friends could see. Years later, packing to leave for college, he found a shoebox in his father's closet filled with copies of every note, each one dated in careful handwriting.
CI:: || Omar discovers that his father saved copies of the lunch notes Omar had pretended not to value. || Omar's father stopped writing notes when Omar entered high school. || Omar kept every note his father wrote. || Omar's father threw away the notes. >> The shoebox reveals the father's devotion.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It shows Omar's apparent dismissal of the notes, which contrasts with the later discovery. || It explains why the jokes were bad. || It describes Omar's friends. || It reveals where Omar went to college. >> He threw notes away, while his father kept copies.
IN: Based on the text, the careful dating of each note suggests that Omar's father || treasured the notes as a record of his son's childhood. || planned to publish the jokes. || needed the notes for work. || forgot which jokes he had written. >> Dated copies show care.

P: Researchers studying wild chimpanzees observed that groups in different regions use different tools and techniques, such as cracking nuts with stones in some areas but not in others where the same nuts and stones are available. Because these differences are not explained by the environment alone, some researchers describe them as cultural traditions passed down through learning.
CI:: || Differences in tool use among chimpanzee groups that cannot be explained by environment suggest learned cultural traditions. || All chimpanzee groups use identical tools. || Chimpanzees crack nuts only where stones are unavailable. || Tool use in chimpanzees is determined entirely by environment. >> Differences persist despite similar resources.
TS: Which choice best describes the function of the phrase "where the same nuts and stones are available" in the text? || It rules out a lack of resources as the explanation for the differences. || It describes the chimpanzees' diet. || It explains how stones crack nuts. || It suggests that chimpanzees cannot find stones. >> Same resources, different behavior.
IN: Based on the text, young chimpanzees most likely acquire their group's tool techniques by || learning from others in their group. || inheriting them without any learning. || inventing them independently each generation. || copying chimpanzees from distant regions. >> Traditions are "passed down through learning."

P: When a regional airline started posting its on-time performance for each route on its website, some routes with poor records improved within months. Managers reported that public comparison motivated staff to find solutions, such as adjusting schedules that had been unrealistic and positioning spare parts at busy airports.
CI:: || Publicly posting on-time performance motivated airline staff to fix problems on poorly performing routes. || On-time performance worsened after the data were posted. || The airline hid its performance data. || Spare parts were removed from busy airports. >> Transparency spurred improvements.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It explains how staff improved the routes' performance. || It describes the airline's history. || It shows that posting data had no effect. || It lists every route the airline flies. >> Adjusted schedules and positioned parts.
IN: Based on the text, some routes had poor on-time records partly because || their schedules had been unrealistic. || passengers boarded too early. || the airline had too many spare parts. || the website was difficult to use. >> Staff adjusted "schedules that had been unrealistic."

P: Some species of fireflies synchronize their flashing, so that thousands of insects in a forest blink at nearly the same moment. Researchers suggest that synchronized flashing may help females recognize males of their own species amid the visual clutter of many flashing insects. Experiments with artificial lights showed that females responded more often to synchronized flashes than to random ones.
CI:: || Synchronized flashing may help female fireflies recognize suitable males, and experiments support this idea. || Fireflies flash at random intervals only. || Females ignore synchronized flashes. || Synchronized flashing attracts predators to females. >> Synchrony may aid recognition, supported by experiments.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It presents evidence supporting the explanation offered in the second sentence. || It describes the forest where fireflies live. || It contradicts the researchers' suggestion. || It explains how artificial lights are made. >> Females responded more to synchronized flashes.
IN: Based on the text, in a forest with many species of flashing insects, synchronized flashing would most likely || make a species' signal easier for females to pick out. || make males harder for females to find. || prevent all insects from flashing. || cause females to flash randomly. >> It helps recognition "amid the visual clutter."

P: The following text is from a memoir. My grandmother spoke four languages but never learned to drive. So every Saturday, I drove her to the market across town, and every Saturday she used a different language: Portuguese with the fish seller, French with the baker, Italian with the woman who sold olives. In the car on the way home, she taught me one new word from each conversation.
CI:: || The narrator's weekly drives with her multilingual grandmother became occasions for learning words from the grandmother's many languages. || The grandmother drove the narrator to the market. || The grandmother spoke only one language at the market. || The narrator refused to learn new words. >> Market visits and shared language lessons.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It introduces details about the grandmother that set up the weekly routine. || It explains why the market was far away. || It lists the foods sold at the market. || It reveals the narrator's age. >> Four languages and no driving lead to Saturday trips.
IN: Based on the text, the grandmother's use of different languages at the market suggests that || the vendors came from varied linguistic backgrounds. || she wanted to confuse the narrator. || the market required visitors to speak French. || she had forgotten how to speak Portuguese. >> She matched each vendor's language.

P: A study tracking two groups of patients recovering from knee surgery found that those who began gentle physical therapy within a day of surgery regained mobility faster than those who waited a week. Patients who started early also reported less stiffness. The researchers cautioned that the early therapy must be carefully supervised to avoid injury.
CI:: || Starting supervised physical therapy soon after knee surgery helped patients regain mobility faster with less stiffness. || Waiting a week before therapy led to faster recovery. || Early therapy caused more stiffness. || Physical therapy should never be supervised. >> Early therapy helped, with supervision.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It adds a caution about how the findings should be applied. || It describes the surgery in detail. || It contradicts the finding about mobility. || It explains why patients had surgery. >> Therapy must be supervised.
IN: Based on the text, the researchers would most likely advise against || beginning intense, unsupervised exercise right after surgery. || starting therapy within a day under supervision. || tracking patients' mobility. || reducing stiffness. >> Supervision is needed "to avoid injury."

P: When archaeologists excavated an ancient harbor, they found remains of ships loaded with pottery made in regions hundreds of kilometers away. Some pottery contained traces of olive oil and wine. The discoveries suggest that the harbor was part of a trade network that connected distant communities long before historians had assumed such networks existed in the region.
CI:: || Ships and pottery found in an ancient harbor suggest a long-distance trade network older than historians assumed. || The harbor traded only with nearby villages. || Pottery found in the harbor was made locally. || Historians already knew the network's full age. >> Distant pottery indicates early trade.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It provides details about goods that were likely traded. || It describes how ships were built. || It contradicts the first sentence. || It explains why the harbor was abandoned. >> Olive oil and wine residues.
IN: Based on the text, historians before these discoveries most likely believed that || long-distance trade networks in the region developed later. || the harbor was the largest in the world. || pottery was never used to store liquids. || ships could not carry cargo. >> The network existed "long before historians had assumed."

P: When a town created a community tool library where residents could borrow ladders, drills, and garden equipment, organizers expected mainly homeowners to use it. Many borrowers turned out to be renters who lacked storage space and did not want to buy tools they would use only occasionally. The library also became a place where neighbors shared repair tips.
CI:: || A community tool library served renters as well as homeowners and became a place for sharing repair knowledge. || Only homeowners borrowed tools from the library. || Renters preferred buying their own tools. || The tool library closed because of low use. >> Unexpected borrowers and a social role.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It describes an additional role the library came to play. || It explains why renters lack storage space. || It contradicts the earlier sentences. || It describes the tools in detail. >> Sharing repair tips.
IN: Based on the text, renters found the tool library especially useful because they || had limited space and rarely needed tools. || owned more tools than homeowners. || were required to borrow tools. || wanted to sell their tools. >> They "lacked storage space" and used tools occasionally.

P: The following text is from a poem. The kite pulls at my hand / as if it knows the sky / belongs to it, and I / am only holding the string. / I could let go. / It would climb and climb, / and I would lose it, / and I think, some days, / that would be enough.
CI:: || The speaker imagines releasing a kite that seems to belong to the sky, finding a kind of contentment in letting go. || The speaker is afraid of flying kites. || The kite falls to the ground. || The speaker ties the kite to a tree. >> Letting go "would be enough."
TS: Which choice best describes the function of the line "I could let go" in the poem? || It marks a turn from describing the kite's pull to considering releasing it. || It describes the wind's direction. || It explains how kites are made. || It reveals that the string broke. >> The poem shifts to contemplating release.
IN: Based on the text, the speaker's thought that losing the kite "would be enough" most likely suggests || an acceptance that some things are meant to be free. || regret about buying the kite. || anger at the wind. || a plan to buy a larger kite. >> The kite "belongs" to the sky.

P: Many cities have begun converting parking spaces into small outdoor seating areas called parklets. In one city, businesses next to parklets reported increased foot traffic and sales, though some drivers complained about losing parking. A survey found that most customers of those businesses arrived on foot, by bike, or by transit rather than by car.
CI:: || Parklets were associated with more foot traffic for nearby businesses, and most customers did not arrive by car. || Businesses lost customers after parklets were installed. || All drivers supported removing parking spaces. || Most customers arrived by car. >> Benefits and survey context.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It provides information that helps explain why losing parking did not hurt businesses. || It describes how parklets are built. || It supports the drivers' complaints. || It explains why cities have parking spaces. >> Most customers didn't drive.
IN: Based on the text, business owners who initially worried that parklets would reduce sales most likely || overestimated how many of their customers depended on parking. || were correct that sales would fall. || had no customers who walked. || closed their businesses. >> Most customers arrived without cars.

P: Scientists studying a species of songbird found that birds living on islands with fewer predators had duller feathers than birds of the same species on the mainland. Bright colors can attract mates but also make birds easier for predators to spot. The researchers suggest that the balance between attracting mates and avoiding predators differs between the two environments.
CI:: || Differences in feather color between island and mainland birds may reflect different balances between attracting mates and avoiding predators. || Island birds have brighter feathers than mainland birds. || Bright colors protect birds from predators. || Predators are more common on the islands. >> Color reflects trade-offs in different settings.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It explains the competing effects of bright coloration. || It describes the islands' vegetation. || It contradicts the first sentence. || It explains how feathers grow. >> Attracts mates but increases visibility.
IN: Based on the text, which factor would researchers most likely investigate to explain why island birds became duller despite having fewer predators? || Whether bright colors provide less benefit for attracting mates on the islands || Whether predators prefer dull birds || Whether island birds eat different seeds only || Whether mainland birds live longer >> Fewer predators alone would favor brightness, so mate attraction may differ.

P: When a public library began offering free museum passes that patrons could reserve, the passes were booked months in advance. Surveys found that many families who used them had never visited those museums because of ticket costs. Several museums reported that some pass users later returned as paying visitors or members.
CI:: || Free museum passes from a library let families who could not afford tickets visit museums, and some later became paying visitors. || The museum passes were rarely used. || Families already visited museums frequently. || Museums lost members because of the passes. >> Access for new visitors and later returns.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It explains why the passes were so popular with some families. || It describes how passes were printed. || It presents a drawback of the program. || It explains the museums' opening hours. >> Cost had kept families away.
IN: Based on the text, the museums most likely benefited from the program by || gaining new visitors who might continue to visit. || selling fewer memberships. || closing on weekends. || charging families higher prices. >> Some pass users returned as paying visitors or members.

P: The following text is from a short story. On the last day of camp, Theo's counselor handed him the old compass they had used on every hike. Theo protested that it belonged to the camp. The counselor shook his head. "It belongs to whoever pays attention to where they're going," he said. Theo turned the compass over in his hands, noticing for the first time a list of initials scratched into the back.
CI:: || A counselor gives Theo a compass that has been passed down to attentive campers, marking Theo as its newest keeper. || Theo refuses to accept the compass. || The counselor sells the compass to Theo. || The compass belongs only to the counselor. >> The initials suggest a tradition Theo now joins.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It reveals that the compass has been passed to others before Theo. || It explains how compasses work. || It describes the camp's hiking trails. || It shows that Theo is disappointed. >> Initials indicate previous owners.
IN: Based on the text, the initials on the compass most likely belong to || earlier campers who received the compass. || the company that made the compass. || Theo's family members. || the camp's directors only. >> A list of initials suggests prior recipients.

P: When a regional water utility sent customers monthly reports comparing their water use with that of similar neighboring households, average water use fell by several percent. Households that had used more than their neighbors reduced their use the most. A few households using less than their neighbors, however, slightly increased their use after seeing the comparison.
CI:: || Comparing households' water use with neighbors' reduced overall use, though some low users slightly increased theirs. || Water use increased for all households. || High users did not change their behavior. || The reports had no effect on water use. >> Overall reduction with an unintended effect.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It describes an unexpected response among some households. || It explains how water is billed. || It restates the main finding. || It describes the utility's history. >> Low users increased use slightly.
IN: Based on the text, low-use households may have increased their water use because the reports || suggested they were using less than typical, making higher use seem acceptable. || required them to use more water. || raised their water prices. || contained errors. >> Comparison to neighbors may have normalized higher use.

P: Researchers studying ancient wheat found that farmers thousands of years ago gradually selected plants whose seed heads did not shatter and scatter seeds on the ground. Wild wheat drops its seeds when ripe, which helps it spread, but that trait made harvesting difficult. By saving seeds from plants that held onto their grain, early farmers changed the crop over generations.
CI:: || Early farmers gradually transformed wheat by saving seeds from plants that kept their grain instead of scattering it. || Wild wheat holds its seeds tightly when ripe. || Early farmers selected plants that scattered seeds. || Wheat has not changed since ancient times. >> Selection for non-shattering seed heads.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It explains why the trait farmers selected against was useful in the wild but a problem for harvesting. || It describes modern wheat farming. || It contradicts the first sentence. || It explains how bread is made. >> Scattering aids spread but hinders harvest.
IN: Based on the text, a wild wheat plant that did not scatter its seeds would most likely || spread less effectively on its own than typical wild wheat. || spread faster than other wild wheat. || produce no seeds. || be impossible to harvest. >> Scattering "helps it spread."

P: A study of children's playgrounds found that equipment with some element of manageable risk, such as higher climbing structures, kept children engaged longer than very low, simple equipment. Injury rates were similar between the two types of playgrounds. Researchers suggest that appropriate challenges help children build confidence and physical skills.
CI:: || Playground equipment with manageable challenges engaged children longer without increasing injuries and may build confidence and skills. || Challenging equipment caused many more injuries. || Children preferred very simple equipment. || Playgrounds should remove climbing structures. >> Engagement rose; injuries did not.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It addresses a likely concern about more challenging equipment. || It describes how playgrounds are designed. || It contradicts the finding about engagement. || It explains why children like simple equipment. >> Injury rates were similar.
IN: Based on the text, the researchers would most likely recommend that playgrounds || include some age-appropriate challenges. || remove all equipment above ground level. || ban climbing. || use only flat, simple equipment. >> Appropriate challenges build confidence and skills.
"""
