"""Passage units, batch 2 (same format as passage_data1; P2 adds a second text for cross-text units)."""

UNITS = """
P: Some researchers argue that allowing students to choose which books they read in school increases how much they read. When a group of middle schools replaced assigned novels with a large classroom library, students could pick any book as long as they wrote a short reflection afterward.
P2: A two-year study of middle schools found that students given free choice of books did read more pages overall. However, the same students were less likely to attempt books above their current reading level, and their scores on tests of challenging vocabulary grew more slowly than those of students who also read some assigned texts.
CT:: || By agreeing that choice may increase reading but cautioning that it can come with drawbacks for building advanced skills || By claiming that students given choice actually read less than students given assigned books || By arguing that reflections are more important than the books students read || By suggesting that assigned novels should be removed from all middle schools >> Text 2 confirms students read more pages but notes they avoided harder books and gained challenging vocabulary more slowly.
CT: Which choice best describes a difference in how the authors of Text 1 and Text 2 view student choice in reading? || Text 1 presents it as a benefit, while Text 2 suggests that its benefits may be accompanied by costs. || Text 1 argues that it lowers reading volume, while Text 2 argues that it raises reading volume. || Text 1 focuses on high school students, while Text 2 focuses on college students. || Text 1 relies on test scores, while Text 2 relies on students' reflections. >> Text 1 emphasizes increased reading; Text 2 adds evidence of drawbacks.

P: Many conservationists favor protecting large, continuous areas of habitat, arguing that big reserves support more species and allow animals to roam, find mates, and adapt to changing conditions.
P2: Large reserves have clear advantages, but a network of many smaller protected areas can sometimes preserve more total species. Because small reserves can be spread across different habitats, such as wetlands, grasslands, and forests, they may capture a wider range of plants and animals than a single large reserve located in one type of landscape.
CT:: || By acknowledging the advantages of large reserves while arguing that several smaller reserves may sometimes protect more species || By rejecting the idea that animals need to roam or find mates || By claiming that small reserves are always better than large reserves || By arguing that reserves should be located only in forests >> Text 2 grants "clear advantages" but proposes that networks of small reserves can capture more habitats and species.
CT: Based on the texts, both authors would most likely agree that || protected areas play an important role in conserving species. || small reserves are more expensive to manage than large reserves. || animals should not be allowed to move between reserves. || wetlands contain fewer species than forests do. >> Both discuss how reserves can best preserve species; they differ on size.

P: Traditionally, historians have credited a single inventor with creating the first practical telephone, pointing to the patent he filed and the famous first call he placed to his assistant.
P2: Patent records and laboratory notebooks show that several inventors in different countries were developing similar voice-transmitting devices during the same years, often building on one another's published work. Crediting one person, some historians now argue, obscures the collaborative and competitive process through which the telephone actually emerged.
CT:: || By arguing that crediting a single inventor overlooks the work of many people who developed similar devices at the same time || By claiming that the famous first call never took place || By agreeing that one inventor deserves all the credit for the telephone || By suggesting that the telephone was invented much later than historians believe >> Text 2 points to several inventors working at once and says single credit "obscures" that process.
CT: Which choice best describes the relationship between the two texts? || Text 2 challenges the traditional account described in Text 1. || Text 2 provides additional details that support the account in Text 1. || Text 2 describes the invention of a different device. || Text 2 summarizes Text 1 without offering a new perspective. >> Text 2 presents evidence against crediting one person, the view in Text 1.

P: Some nutrition writers claim that eating late at night inevitably leads to weight gain, because the body supposedly burns fewer calories while sleeping.
P2: Controlled studies that give participants the same total calories at different times of day have generally found little difference in weight change. Late-night eating may be linked to weight gain in surveys, but that link often reflects what people eat at night, such as high-calorie snacks, and how much they eat overall, not the timing itself.
CT:: || By arguing that the total amount and type of food people eat matter more than the time at which they eat it || By agreeing that the body burns no calories during sleep || By claiming that eating at night causes weight loss || By suggesting that surveys about eating habits are always accurate >> Text 2 cites studies showing timing has little effect when calories are equal and points to what and how much people eat.
CT: Based on Text 2, the surveys linking late-night eating to weight gain may be misleading because || the people who eat at night may also choose higher-calorie foods or eat more overall. || participants in the surveys ate only in the morning. || the surveys measured weight only once. || controlled studies found that nighttime eating increases metabolism. >> Text 2 says the link "often reflects what people eat at night ... and how much they eat overall."

P: Critics sometimes dismiss graphic novels as simplified versions of "real" literature, suitable mainly for readers who struggle with traditional books.
P2: Reading a graphic novel well requires skills that prose alone does not develop. Readers must interpret how images and words interact, notice details in the artwork that contradict or complicate the text, and infer what happens in the gaps between panels. Far from being a simplified form, the graphic novel asks readers to combine two ways of making meaning at once.
CT:: || By arguing that graphic novels demand complex interpretive skills rather than offering a simplified reading experience || By agreeing that graphic novels are mainly for struggling readers || By claiming that prose novels contain no images || By suggesting that graphic novels should replace traditional literature in schools >> Text 2 describes the skills graphic novels require and says they are "far from being a simplified form."
CT: The author of Text 2 mentions "the gaps between panels" primarily to || give an example of something readers must interpret on their own. || criticize artists who leave out important scenes. || explain why graphic novels are shorter than prose novels. || describe a printing error common in graphic novels. >> Inferring what happens in the gaps is one of the skills the author lists.

P: Advocates of four-day school weeks argue that the schedule saves districts money on transportation and utilities and gives teachers more time to plan.
P2: In several rural districts that adopted four-day weeks, savings turned out to be smaller than expected, typically a few percent of the budget. Some families also reported difficulty finding child care on the fifth day. Although teachers generally liked the schedule, results for student achievement were mixed across districts.
CT:: || By noting that the savings may be modest and that the schedule can create other challenges || By claiming that four-day weeks increase transportation costs || By arguing that teachers dislike four-day weeks || By agreeing that four-day weeks clearly improve student achievement >> Text 2 reports small savings, child-care problems, and mixed achievement results.
CT: Based on the texts, the authors would most likely agree that four-day school weeks || are generally appealing to teachers. || cost districts more than five-day weeks. || have been adopted mainly in large cities. || lead to higher test scores in every district. >> Text 1 says they give teachers planning time; Text 2 says teachers generally liked the schedule.

P: Many birdwatchers believe that feeding wild birds in winter helps them survive the cold months by providing extra energy when natural food is scarce.
P2: Winter feeding can help some birds survive, but it can also have unintended effects. In one region, feeders encouraged certain species to stay farther north instead of migrating, and crowds at feeders helped spread diseases among birds. Researchers suggest keeping feeders clean and spacing them apart to reduce these risks.
CT:: || By agreeing that feeding can help birds survive while warning that it can also cause problems that should be managed || By claiming that feeding birds always causes them to die || By arguing that birds never need extra food in winter || By suggesting that feeders should be placed close together >> Text 2 grants that feeding "can help" but notes changed migration and disease, and recommends precautions.
CT: Which choice best describes how Text 2 relates to Text 1? || It qualifies the view in Text 1 by describing possible drawbacks of the practice. || It provides evidence that the view in Text 1 is entirely mistaken. || It describes a different practice unrelated to Text 1. || It restates the view in Text 1 in more technical language. >> Text 2 accepts the benefit but adds risks and precautions.

P: When a coastal city considered building a seawall to protect against rising seas, many residents supported the plan, arguing that a solid wall was the most reliable defense against flooding.
P2: Seawalls can protect the land directly behind them, but they often increase erosion on nearby beaches by reflecting wave energy. Some coastal engineers recommend combining smaller structures with restored dunes and marshes, which absorb wave energy and can adjust as sea levels change.
CT:: || By pointing out that seawalls can cause problems nearby and that natural features may offer a more adaptable form of protection || By claiming that seawalls provide no protection at all || By agreeing that a solid wall is the only reliable defense || By arguing that the city faces no risk from rising seas >> Text 2 notes erosion caused by seawalls and recommends dunes and marshes that "can adjust."
CT: Based on Text 2, a restored marsh would most likely be preferred over a seawall because it || can absorb wave energy and adapt to changing sea levels. || is cheaper to build than any other structure. || reflects wave energy toward nearby beaches. || prevents all flooding in the city. >> Marshes "absorb wave energy and can adjust as sea levels change."

P: The following text is from a short story. Every summer, the carnival arrived in town on the same Tuesday and left on the same Sunday. Nadia had watched it come and go for eleven years without ever riding the Ferris wheel. This year, standing in line with a ticket that had cost her two weeks of saved allowance, she felt her heart pounding. When the attendant waved her forward, she stepped into the swaying seat before she could change her mind.
CI:: || Nadia overcomes her hesitation and rides the Ferris wheel for the first time. || Nadia decides not to ride the Ferris wheel after all. || Nadia works at the carnival every summer. || Nadia is disappointed that the carnival arrives late this year. >> After eleven years of not riding, she steps into the seat "before she could change her mind."
TS: Which choice best describes the function of the second sentence in the text as a whole? || It establishes a long history of avoiding the ride, which makes her decision this year significant. || It explains how the carnival's schedule has changed over time. || It suggests that Nadia has never been to the carnival before. || It describes the Ferris wheel's size and design. >> Eleven years without riding gives weight to this year's choice.
IN: Based on the text, Nadia most likely stepped into the seat quickly because she || worried that she might lose her nerve if she hesitated. || was late for another ride. || had ridden the Ferris wheel many times before. || wanted to get a better view of the attendant. >> She acted "before she could change her mind," showing she feared losing her nerve.

P: For centuries, people in some mountain villages have built terraces, flat steps carved into steep hillsides, to grow crops. Terraces slow the flow of rainwater so that it soaks into the soil instead of rushing downhill and carrying the soil away. In several regions where terraces were abandoned as families moved to cities, landslides and erosion increased within a few decades.
CI:: || Terraces protect hillside soil by slowing rainwater, and abandoning them can lead to erosion and landslides. || Mountain villages have stopped growing crops entirely. || Terraces are a recent invention used mainly in cities. || Rainwater erodes flat land more quickly than steep land. >> The text explains how terraces slow water and what happened when they were abandoned.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It provides evidence of the terraces' protective role by describing what happened without them. || It explains why families moved from the villages to cities. || It describes how terraces are built. || It contradicts the claim made in the second sentence. >> Increased erosion after abandonment supports the terraces' protective function.
IN: Based on the text, a village that maintains its terraces would most likely experience || less soil erosion than a similar village whose terraces were abandoned. || more landslides than a village without terraces. || less rainfall than neighboring villages. || a decline in its crops. >> Terraces keep water from carrying soil downhill.

P: A composer who writes music for video games explained that her work differs from writing for film in one important way: in a film, every scene lasts exactly as long as the director decides, but in a game, the player controls how long each moment lasts. A player might spend thirty seconds or thirty minutes exploring a single room. As a result, she writes pieces that can loop smoothly or shift gradually to match what the player is doing.
CI:: || Because players control the pace of a game, a game composer writes music that can loop or adapt to the player's actions. || Video game music is more difficult to perform than film music. || Film directors often ask game composers to write their music. || Players prefer games with no background music. >> The difference in who controls timing leads her to write looping or adaptive music.
TS: Which choice best describes the overall structure of the text? || It identifies a difference between two kinds of composing and explains how that difference shapes the composer's work. || It describes the composer's childhood and then her career. || It compares the budgets of films and video games. || It argues that film music is superior to game music. >> Film timing versus player-controlled timing, then the resulting approach.
IN: Based on the text, a piece of game music that ended abruptly after one minute would most likely be a problem because || the player might remain in that part of the game for much longer. || players rarely spend more than a minute in any room. || film directors require music to end quickly. || games do not allow music to be repeated. >> A player "might spend thirty seconds or thirty minutes" in one room.

P: Scientists once assumed that honeybees navigate mainly by remembering landmarks. Experiments have shown that bees also rely on the position of the sun, and they can compensate for the sun's movement across the sky over the course of a day. Even when clouds hide the sun, bees can detect patterns of polarized light in patches of blue sky, allowing them to keep their bearings.
CI:: || Honeybees navigate using the sun's position and polarized light, not only landmarks. || Honeybees cannot find their way when the sky is cloudy. || Honeybees navigate only by remembering landmarks. || Honeybees fly only during the middle of the day. >> The text adds the sun and polarized light to the earlier assumption about landmarks.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It presents an earlier view that the following sentences show to be incomplete. || It states the main conclusion of the experiments. || It explains why bees need to navigate. || It describes a method for studying bees. >> Later sentences show bees use more than landmarks.
IN: Based on the text, if a bee were flying on a partly cloudy day with the sun hidden, it would most likely || still be able to orient itself using polarized light in visible patches of blue sky. || be unable to return to its hive. || rely only on the scent of flowers. || wait until the clouds cleared to begin flying. >> Bees "can detect patterns of polarized light in patches of blue sky."

P: In the 1800s, many cities drew drinking water directly from rivers that also carried sewage. Outbreaks of cholera were common. When one city began filtering its water through layers of sand and gravel, cholera cases there dropped sharply, while a neighboring city that continued using unfiltered river water saw no such decline. The comparison helped persuade officials elsewhere to adopt filtration.
CI:: || A comparison between two cities showed that water filtration reduced cholera, encouraging other cities to filter their water. || Cholera outbreaks were rare in the 1800s. || Sand and gravel make water taste better. || All cities stopped using river water in the 1800s. >> The city that filtered saw cholera drop; the neighbor did not; others followed.
TS: Which choice best describes the function of the third sentence in the text as a whole? || It presents a contrast that provides evidence for the effectiveness of filtration. || It explains how sand filters are built. || It introduces a disease different from cholera. || It argues that filtration was too expensive for most cities. >> The two-city comparison is the evidence that persuaded officials.
IN: Based on the text, the neighboring city was useful to the comparison mainly because it || showed what happened when the water was not filtered. || had better water than the city that filtered. || invented the sand filtration method. || had no cases of cholera. >> It continued using unfiltered water, serving as a point of comparison.

P: The following text is adapted from a nineteenth-century letter. My dear sister, the voyage has been long, and the sea has not been kind. For nine days the waves rose higher than the mast, and I confess I did not expect to write to you again. Yet this morning the sky cleared, a flock of gulls circled the ship, and the captain says we shall see land within two days. I have never been so glad to hear the cry of a bird.
CI:: || After a frightening voyage, the writer feels relief as signs indicate that land is near. || The writer regrets leaving home and plans to return immediately. || The writer describes a peaceful and uneventful trip. || The writer is annoyed by the noise of the gulls. >> The storm made the writer fear the worst; the clear sky, gulls, and news of land bring relief.
TS: Which choice best describes the overall structure of the text? || It describes a period of danger and then a moment of hope. || It lists the ship's supplies and then describes the crew. || It compares two voyages the writer has taken. || It describes the writer's plans after arriving on land. >> Nine days of storms, then "yet this morning the sky cleared."
IN: Based on the text, the writer was most likely glad to hear the gulls because || birds near the ship suggested that land was not far away. || the writer had never seen gulls before. || the gulls' cries meant another storm was coming. || the captain had asked everyone to watch for birds. >> Gulls appear just as the captain says land is two days away.

P: Many cities have begun replacing streetlights with LED bulbs, which use far less electricity than older lamps. Some astronomers and ecologists have raised a concern: early LED streetlights emitted a large amount of blue light, which scatters widely in the atmosphere and can disrupt the behavior of nocturnal animals. Newer LED designs produce warmer light with less blue, offering energy savings with fewer side effects.
CI:: || LED streetlights save energy, and newer designs reduce the drawbacks of the blue light emitted by early models. || LED streetlights use more electricity than older lamps. || Nocturnal animals prefer blue light to warm light. || Astronomers want cities to remove all streetlights. >> The text presents the benefit, the concern about blue light, and newer designs that address it.
TS: Which choice best describes the overall structure of the text? || It describes a change, raises a concern about it, and then explains how the concern has been addressed. || It explains how streetlights are manufactured. || It argues that cities should return to older lamps. || It compares the costs of several kinds of lighting. >> LED adoption, blue-light concern, warmer newer designs.
IN: Based on the text, a city choosing new LED streetlights to minimize effects on nocturnal animals would most likely select lights that || emit warm light with relatively little blue. || emit as much blue light as possible. || use more electricity than older lamps. || are brighter than any previous streetlights. >> Newer designs with less blue have "fewer side effects."

P: When a regional airline began weighing passengers' carry-on bags at the gate, travelers complained about the delays. The airline explained that its small planes have strict weight limits, and knowing the total weight of luggage helps pilots calculate how much fuel to carry. Within a few months, passengers adjusted by packing lighter, and boarding times returned to normal.
CI:: || An airline's policy of weighing carry-on bags was unpopular at first but served a safety purpose, and passengers soon adapted. || The airline stopped weighing bags after passengers complained. || Large planes have stricter weight limits than small planes. || Boarding times became permanently longer because of the policy. >> The complaint, the explanation, and passengers' adjustment.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It gives the reason behind the policy that caused the complaints. || It describes how passengers reacted to the policy. || It explains how pilots are trained. || It suggests that the policy was unnecessary. >> The weight limits and fuel calculations explain why bags were weighed.
IN: Based on the text, boarding times most likely returned to normal because || lighter bags made the weighing process quicker and caused fewer problems at the gate. || the airline switched to larger planes. || the airline hired more gate agents. || pilots stopped calculating fuel needs. >> Passengers "adjusted by packing lighter," and then boarding times returned to normal.

P: A marine biologist studying cleaner wrasses, small fish that eat parasites off larger fish, noticed that the wrasses behaved differently when other fish were watching. When observed by potential clients, the wrasses were more careful to eat only parasites rather than nipping at the healthy mucus on their clients' skin, which they prefer. The biologist suggests that the wrasses may be managing their reputations.
CI:: || Cleaner wrasses appear to behave more cooperatively when other fish can see them, suggesting a concern with reputation. || Cleaner wrasses eat only mucus and never parasites. || Larger fish avoid cleaner wrasses whenever possible. || Cleaner wrasses live alone and rarely interact with other fish. >> Their behavior changes when observed, which the biologist links to reputation.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It offers an interpretation of the behavior described earlier in the text. || It describes the method the biologist used. || It presents a finding that contradicts the earlier observations. || It explains what cleaner wrasses eat. >> The reputation idea explains why behavior changes when others watch.
IN: Based on the text, a cleaner wrasse that is not being watched by other fish would most likely || be more likely to nip at a client's healthy mucus. || refuse to eat any parasites. || leave the reef entirely. || clean more carefully than when it is watched. >> Wrasses prefer mucus and were more careful only when observed.

P: The following text is from a novel. For three generations the Okonkwo family had run the hardware store on Main Street, and for three generations the bell above its door had rung the same flat note. When Adaeze took over the shop, she replaced the dusty shelves, repainted the walls a pale green, and installed bright new lights. But when a customer suggested she replace the bell, she shook her head. Some things, she said, should sound exactly the way they always have.
CI:: || While modernizing the family store, Adaeze chooses to preserve the old bell because of its connection to the past. || Adaeze plans to sell the hardware store. || Adaeze refuses to make any changes to the store. || Customers dislike the changes Adaeze has made. >> She renovates the store but keeps the bell, which has rung the same note for three generations.
TS: Which choice best describes the overall structure of the text? || It describes several changes a character makes and then one thing she decides not to change. || It describes a store's history and then its closing. || It compares two family members' approaches to business. || It presents a customer's complaint and the store's response. >> New shelves, paint, and lights contrast with the kept bell.
IN: Based on the text, Adaeze most likely keeps the bell because she || values its link to her family's long history with the store. || cannot afford a new bell. || does not notice the sound it makes. || believes customers want a louder bell. >> "Some things ... should sound exactly the way they always have" connects the bell to three generations.
"""
