"""Passage units, batch 11 (format documented in passage_data1.py). Original texts; people and studies are illustrative."""

UNITS = """
P: When a regional railway added quiet cars, where phone calls and loud conversations were not allowed, officials expected them to appeal mainly to business travelers. Surveys found that the cars were popular with a wide range of passengers, including students studying for exams and parents with sleeping infants. The railway later added a second quiet car to its busiest routes.
CI:: || Quiet cars on a railway proved popular with many kinds of passengers, leading the railway to add more. || Only business travelers used the quiet cars. || Passengers complained about the quiet cars. || The railway removed quiet cars from busy routes. >> Broad popularity led to expansion.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It presents an expectation that the survey results broadened. || It explains why trains are noisy. || It describes the railway's ticket prices. || It summarizes the railway's decision. >> Officials expected business travelers only.
IN: Based on the text, the railway added a second quiet car most likely because || demand for quiet space exceeded what one car could provide. || passengers disliked the first quiet car. || business travelers stopped riding. || phone calls became illegal. >> Popularity on busy routes led to expansion.

P: The following text is from a novel. The piano had been out of tune for years, and no one in the house played it anymore. When Aiko's grandmother moved in, she said nothing about it for a week. Then one evening, after everyone had gone to bed, the family heard music drifting up the stairs: an old, slightly sour-sounding waltz, played slowly, as if the player were remembering it one note at a time.
CI:: || Aiko's grandmother quietly brings music back into the house by playing the long-neglected piano. || Aiko's grandmother complains that the piano is out of tune. || The family sells the old piano. || Aiko learns to play a waltz perfectly. >> The grandmother plays the piano at night.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It establishes the piano's neglect, which makes the later music meaningful. || It explains how pianos are tuned. || It describes Aiko's musical training. || It reveals that the grandmother dislikes music. >> No one had played it in years.
IN: Based on the text, the phrase "as if the player were remembering it one note at a time" suggests that the grandmother || had not played the piece in a long time. || was reading unfamiliar sheet music. || was an expert concert pianist. || wanted to wake the family. >> She recalls the waltz slowly.

P: Researchers studying why some people are "morning people" and others "night owls" found that genetic differences affect the body's internal clock. However, when volunteers spent a week camping without artificial light, their sleep schedules shifted earlier and became more similar to one another, suggesting that modern lighting widens the natural differences between people.
CI:: || Genes influence whether people are early or late risers, but artificial light appears to widen these differences. || Genes have no effect on sleep schedules. || Camping made volunteers' sleep schedules more different. || Artificial light makes everyone wake earlier. >> Both genetics and light play roles.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It presents a finding showing that environment also affects sleep timing. || It restates the genetic finding. || It describes how volunteers set up tents. || It contradicts the idea that genes matter. >> Without artificial light, schedules converged.
IN: Based on the text, a night owl who spent a week without artificial light would most likely || begin going to sleep earlier than usual. || stay awake even later. || stop sleeping altogether. || become a morning person permanently. >> Schedules "shifted earlier."

P: When a town replaced a busy four-way stop with a small roundabout, some residents worried that drivers would be confused. For the first few weeks, traffic moved hesitantly. Within months, however, waiting times at the intersection dropped, and the number of collisions fell, as drivers adjusted to yielding while moving slowly through the circle.
CI:: || A roundabout initially confused drivers but soon reduced waiting times and collisions. || The roundabout caused more collisions over time. || Residents requested the four-way stop be restored. || Traffic moved faster in the first weeks. >> Early hesitation, later improvements.
TS: Which choice best describes the overall structure of the text? || It describes a change, an early concern and difficulty, and the eventual benefits. || It compares two towns' roads. || It explains the history of roundabouts. || It argues that four-way stops are safer. >> Concern and hesitation, then improvement.
IN: Based on the text, the early hesitation most likely resulted from || drivers being unfamiliar with how to use the roundabout. || the roundabout being closed. || an increase in pedestrians. || broken traffic lights. >> Drivers later "adjusted."

P: Some desert beetles collect drinking water from fog. The beetles stand on sand dunes with their backs tilted into the wind, and tiny droplets of fog collect on bumps on their shells, eventually rolling down into their mouths. Engineers have studied the beetles' shells to design surfaces that harvest water from fog in dry regions.
CI:: || Desert beetles gather water from fog with their shells, inspiring designs for fog-harvesting surfaces. || Desert beetles drink only from underground springs. || Engineers designed beetles to collect fog. || Fog never reaches desert dunes. >> Beetles' water collection inspires technology.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It describes a human application inspired by the beetles' behavior. || It explains why fog forms. || It describes beetles' predators. || It questions whether beetles drink fog. >> Engineers imitate the shell design.
IN: Based on the text, the beetles tilt their backs into the wind most likely to || catch more fog droplets on their shells. || avoid being seen by predators. || dig into the sand. || stay warm at night. >> Droplets collect on bumps facing the fog.

P: The following text is from a memoir. I spent the summer I was fourteen working at my aunt's flower shop, convinced it would be the dullest job imaginable. By August I knew the names of forty flowers, could tie a bow with my eyes closed, and had watched a nervous young man spend twenty minutes choosing roses for a proposal. I had expected to count the days. Instead, I counted the stories.
CI:: || A summer job the narrator expected to be dull turned out to be full of interesting experiences. || The narrator found working at the flower shop boring. || The narrator quit the job after a week. || The narrator's aunt sold only roses. >> She "counted the stories" instead of the days.
TS: Which choice best describes the function of the final two sentences in the text as a whole? || They contrast the narrator's expectation with her actual experience. || They describe how to tie a bow. || They explain why the young man chose roses. || They list the flowers sold in the shop. >> Counting days versus counting stories.
IN: Based on the text, the anecdote about the young man choosing roses mainly illustrates || the kinds of moments that made the job meaningful to the narrator. || how difficult customers can be. || the high price of roses. || the narrator's plans to become a florist. >> It is one of the "stories."

P: A study of online classes found that students who were required to post short weekly reflections about what they had learned were more likely to finish the course than students in sections without the requirement. Researchers suggest that the reflections kept students engaged and helped instructors notice early when students were struggling.
CI:: || Weekly reflection posts were associated with higher course completion, possibly by increasing engagement and early support. || Reflection posts reduced course completion. || Students disliked all online classes. || Instructors ignored the reflections. >> Reflections linked to finishing.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It offers possible explanations for the finding. || It describes how the course was graded. || It contradicts the finding. || It explains why online classes exist. >> Engagement and early detection.
IN: Based on the text, instructors reading reflections could most likely || identify students who needed help before they fell too far behind. || grade exams automatically. || stop teaching the course. || replace the course content. >> Reflections helped instructors "notice early."

P: For centuries, farmers in some mountain regions have raised a breed of sheep with unusually thick wool that allows the animals to survive harsh winters. As many farmers switched to faster-growing breeds, the traditional sheep became rare. Recently, some weavers have begun paying premium prices for its wool, prized for its warmth and durability, giving farmers a reason to keep raising the breed.
CI:: || Demand from weavers for its distinctive wool is helping preserve a rare traditional sheep breed. || The traditional sheep breed has disappeared completely. || Weavers prefer wool from faster-growing breeds. || Farmers stopped raising sheep altogether. >> Premium prices encourage farmers to keep the breed.
TS: Which choice best describes the overall structure of the text? || It describes a traditional breed, its decline, and a development that may help it survive. || It explains how wool is spun into yarn. || It compares sheep with goats. || It argues that farmers should stop raising sheep. >> Tradition, decline, and renewed demand.
IN: Based on the text, farmers had switched to faster-growing breeds most likely because || those breeds could be raised more profitably. || the traditional sheep could not survive winters. || weavers refused to buy traditional wool. || faster-growing breeds produced warmer wool. >> Faster growth offers economic advantage.

P: When a city began tracking which streetlights were broken using reports from residents' smartphones, repair times dropped from weeks to days. Previously, broken lights were often discovered only during periodic inspections. The reports also revealed that some neighborhoods had many more broken lights than others, prompting the city to investigate the cause.
CI:: || Resident smartphone reports sped up streetlight repairs and revealed uneven problems across neighborhoods. || Periodic inspections repaired lights faster than reports. || Residents refused to report broken lights. || All neighborhoods had the same number of broken lights. >> Faster repairs and new insight into patterns.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It describes an additional insight gained from the reporting system. || It explains how smartphones work. || It shows that repair times increased. || It describes the cost of streetlights. >> Uneven distribution prompted investigation.
IN: Based on the text, before resident reports, broken lights most likely || stayed broken for longer because they were found only during inspections. || were repaired within hours. || were reported by the lights themselves. || did not exist. >> They were "discovered only during periodic inspections."

P: Many octopus species live only a year or two and die soon after reproducing. Female octopuses guard their eggs without eating, sometimes for months, until the eggs hatch. Researchers have found that a gland near the octopus's eyes triggers changes that lead to this fasting and decline; when the gland was removed in experiments, mothers abandoned their eggs, resumed eating, and lived longer.
CI:: || A gland in female octopuses triggers the fasting and decline that follow egg-laying. || Octopuses live for many decades. || Female octopuses eat constantly while guarding eggs. || Removing the gland caused mothers to guard eggs longer. >> The gland drives brooding behavior and decline.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It presents experimental evidence identifying a cause of the behavior described earlier. || It describes where octopuses lay eggs. || It explains why octopuses change color. || It contradicts the claim that octopuses guard eggs. >> Removing the gland changed behavior.
IN: Based on the text, the gland most likely plays a role in || ensuring that mothers stay with their eggs until they hatch. || helping octopuses see in the dark. || causing octopuses to hunt more. || making eggs hatch faster. >> Without it, mothers abandoned eggs.

P: When a high school changed its start time from 7:30 to 8:30 a.m., students reported sleeping about forty minutes more on school nights. Attendance in first-period classes improved, and the number of students falling asleep in class decreased. Some parents, however, noted that later dismissal times made it harder to schedule after-school activities and jobs.
CI:: || A later school start time led to more sleep and better attendance, though it complicated some after-school schedules. || Students slept less after the change. || Attendance fell after the change. || Parents unanimously supported the new schedule. >> Benefits plus a scheduling drawback.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It presents a drawback of the change. || It explains why the change was made. || It describes students' sleep habits in detail. || It summarizes the attendance data. >> Later dismissal complicated activities.
IN: Based on the text, fewer students fell asleep in class most likely because || they were getting more sleep at night. || classes became shorter. || teachers stopped giving lectures. || students drank more coffee. >> They slept about forty minutes more.

P: Some art restorers once used strong chemicals to remove old varnish from paintings, occasionally damaging the original paint beneath. Newer methods use gels that release cleaning agents slowly and can be applied to tiny areas under a microscope. These techniques allow restorers to remove grime while preserving delicate brushwork.
CI:: || Newer restoration methods allow grime to be removed more precisely without damaging original paint. || Strong chemicals are the safest way to restore paintings. || Restorers no longer clean paintings. || Gels damage paintings more than older methods. >> Gels offer precise, gentle cleaning.
TS: Which choice best describes the overall structure of the text? || It contrasts an older, risky method with a newer, more precise one. || It describes the history of a single painting. || It explains how varnish is made. || It argues that paintings should never be restored. >> Old harsh chemicals, new controlled gels.
IN: Based on the text, applying cleaning gels under a microscope is most useful because it || lets restorers control exactly where the cleaning agent acts. || makes the painting brighter than it originally was. || removes the original paint. || speeds up drying time. >> They can be applied "to tiny areas."

P: The following text is from a short story. For the whole bus ride, the new girl sat alone, staring out the window. Rosa had planned to sit with her friends, as always. But when the bus stopped at the school, Rosa noticed the girl clutching a map of the building, her hands trembling slightly. Rosa slid into the seat beside her and asked, "Want me to show you where the gym is?"
CI:: || Noticing a new student's nervousness, Rosa sets aside her usual plans to help her. || Rosa ignores the new girl for the entire day. || The new girl shows Rosa around the school. || Rosa's friends ask the new girl to join them. >> Rosa offers help after seeing her anxiety.
TS: Which choice best describes the function of the sentence "Rosa had planned to sit with her friends, as always" in the text? || It shows that Rosa's decision to help involves changing her routine. || It explains why the new girl sat alone. || It describes the bus route. || It reveals that Rosa has no friends. >> Helping means breaking from habit.
IN: Based on the text, the detail about the girl's trembling hands suggests that she || felt anxious about her first day. || was cold on the bus. || was angry at Rosa. || had been to the school many times. >> Trembling while clutching a map shows nervousness.

P: When a coastal town prohibited single-use plastic bags, many shoppers switched to reusable bags. Litter surveys found far fewer plastic bags on beaches afterward. Sales of small plastic trash bags, however, increased, as some residents had previously reused shopping bags to line household wastebaskets.
CI:: || A plastic bag ban reduced bag litter on beaches but led some residents to buy other plastic bags instead. || The ban increased plastic bag litter on beaches. || Shoppers refused to use reusable bags. || Sales of trash bags decreased after the ban. >> Less litter, but some substitution.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It describes an unintended effect of the ban. || It explains why reusable bags are popular. || It supports the claim that litter decreased. || It describes how beaches are cleaned. >> Trash bag sales rose.
IN: Based on the text, before the ban, some residents' shopping bags most likely || served a second use as trash can liners. || were always thrown directly on beaches. || were made of cloth. || were never reused. >> They "reused shopping bags to line household wastebaskets."

P: Scientists studying why some leaves change color in autumn found that as days shorten, trees stop producing green chlorophyll, revealing yellow and orange pigments already present in the leaves. Red colors, however, come from pigments that some trees actively produce in autumn, possibly to protect leaves from sun damage while the trees reabsorb nutrients before the leaves fall.
CI:: || Autumn leaf colors come partly from existing pigments revealed as chlorophyll fades and partly from red pigments trees produce. || All autumn colors are newly produced pigments. || Trees produce more chlorophyll in autumn. || Red pigments are present in leaves all summer. >> Yellow and orange revealed; red produced.
TS: Which choice best describes the function of the word "however" in the text? || It signals that red colors have a different origin than yellow and orange. || It indicates that leaves stay green. || It introduces a contradiction about chlorophyll. || It shows that the study failed. >> Red comes from actively produced pigments.
IN: Based on the text, the red pigments may benefit trees by || helping protect leaves while nutrients are recovered. || making leaves fall sooner. || producing chlorophyll. || attracting insects to eat the leaves. >> Possibly "to protect leaves from sun damage."

P: When a grocery chain began placing water bottles next to soda in refrigerated cases at checkout, sales of bottled water increased while soda sales dipped slightly. Previously, water had been stocked only in a distant aisle. The chain's analysts concluded that convenient placement influenced which drink shoppers grabbed at the last moment.
CI:: || Placing water next to soda at checkout increased water sales, suggesting that convenient placement affects last-minute choices. || Moving water to checkout reduced water sales. || Shoppers always walk to distant aisles for water. || Soda sales rose sharply. >> Convenience changed choices.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It describes the earlier placement for comparison. || It explains how soda is made. || It presents the analysts' conclusion. || It describes prices at the store. >> Water was previously in a distant aisle.
IN: Based on the text, a store hoping to increase sales of fruit might || place fruit near the checkout lines. || move fruit to the back of the store. || stop selling soda entirely. || hide fruit behind other products. >> Convenient placement influences quick choices.

P: The following text is from a poem. My father's workshop still smells of pine, / though he has not lifted a plane in years. / His tools hang in their outlines on the wall, / each shape drawn in pencil, / so that anything taken / would leave a ghost behind / until it came back home.
CI:: || The speaker describes a father's workshop, where outlines of tools preserve the memory of the work done there. || The father still works in the workshop every day. || The tools have been sold. || The speaker dislikes the smell of pine. >> Outlines remain though he no longer works.
TS: Which choice best describes the function of the final three lines of the poem? || They explain the purpose of the outlines while suggesting absence and return. || They describe a ghost that lives in the workshop. || They list the tools on the wall. || They describe the father's new hobby. >> A missing tool "would leave a ghost."
IN: Based on the text, the outlines on the wall most likely suggest that the father was || careful and organized in his work. || careless with his tools. || a professional painter. || unfamiliar with woodworking. >> Each tool has a drawn place.

P: Researchers analyzing thousands of hours of basketball games found that teams attempting more three-point shots scored more points per possession on average, even though three-pointers are made less often than shorter shots. Because each successful three-pointer earns an extra point, the higher reward can outweigh the lower success rate. The finding helped explain why many teams increased their three-point attempts.
CI:: || Three-point shots can produce more points per possession despite lower accuracy, which helps explain their growing use. || Three-pointers are made more often than shorter shots. || Teams scored fewer points when attempting more three-pointers. || Teams stopped attempting three-point shots. >> Higher reward offsets lower success.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It explains how three-pointers can be more valuable despite being missed more often. || It describes the history of the three-point line. || It contradicts the first sentence. || It describes the size of basketball courts. >> The extra point outweighs the lower success rate.
IN: Based on the text, if three-pointers were worth the same as shorter shots, teams would most likely || attempt fewer three-pointers. || attempt even more three-pointers. || score more points per possession. || stop taking any shots. >> The extra point is what makes them worthwhile.

P: When a museum began offering sensory-friendly hours, with dimmed lights, quieter galleries, and limited crowds, officials expected to serve mainly visitors with autism. Attendance data showed that many older adults and parents with young children also chose these hours, preferring the calmer atmosphere.
CI:: || Sensory-friendly museum hours attracted a wider range of visitors than expected, including older adults and families. || Only visitors with autism attended sensory-friendly hours. || The museum canceled sensory-friendly hours. || Visitors preferred crowded galleries. >> Broader appeal than expected.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It shows that the program's appeal extended beyond its intended audience. || It explains how lights were dimmed. || It describes the museum's exhibits. || It contradicts the purpose of the program. >> Older adults and parents also attended.
IN: Based on the text, older adults and parents with young children most likely valued || a calmer, less crowded environment. || louder, busier galleries. || the chance to see new exhibits only. || free admission. >> They preferred "the calmer atmosphere."

P: Geologists studying a river canyon noticed that some of the rock layers exposed in its walls contain fossils of marine animals, even though the canyon lies far inland and high above sea level. The fossils indicate that the region was once covered by a shallow sea before geological forces lifted the land.
CI:: || Marine fossils in an inland canyon show that the region was once under a sea before being uplifted. || The canyon was carved by ocean waves recently. || Marine animals once lived in mountain rivers. || The fossils were carried there by people. >> Fossils indicate a former sea and uplift.
TS: Which choice best describes the function of the phrase "even though the canyon lies far inland and high above sea level" in the text? || It highlights why the fossils' presence is surprising. || It explains how rivers form canyons. || It describes the canyon's width. || It suggests the fossils are fake. >> Marine fossils inland need explanation.
IN: Based on the text, which statement about the region is best supported? || Its land surface has risen substantially over geological time. || It has always been above sea level. || It is currently covered by ocean. || No animals ever lived there. >> The land was "lifted."

P: When a public radio station invited listeners to submit short audio stories about their neighborhoods, producers expected a few dozen entries. They received more than a thousand. Many stories came from people who had never spoken on the radio before, and several became among the station's most shared segments online.
CI:: || A call for listener-submitted stories drew far more entries than expected, and many became popular. || Few listeners submitted stories. || Only professional reporters submitted stories. || The segments were rarely shared online. >> Unexpected volume and popularity.
TS: Which choice best describes the function of the sentence "They received more than a thousand" in the text? || It emphasizes how greatly the response exceeded expectations. || It explains how stories were recorded. || It describes the neighborhoods. || It shows that the project failed. >> A few dozen expected versus more than a thousand.
IN: Based on the text, the popularity of the segments most likely stemmed partly from || the fresh, personal perspectives of everyday residents. || the stories being read by famous actors. || the station's decision to shorten news broadcasts. || the stories being fictional. >> Many came from first-time voices.

P: Some cities have painted crosswalks with bright, artistic designs. In one city, researchers compared intersections before and after the paintings were added and found that drivers yielded to pedestrians more often at painted crosswalks. The researchers suggest that the eye-catching designs made crosswalks more noticeable.
CI:: || Artistic crosswalk designs were associated with drivers yielding to pedestrians more often, likely because they were more noticeable. || Drivers yielded less at painted crosswalks. || Painted crosswalks confused pedestrians. || The designs had no effect on drivers. >> More yielding after paintings.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It offers an explanation for the change in driver behavior. || It describes how the crosswalks were painted. || It lists the cities involved. || It argues against painting crosswalks. >> The designs were more noticeable.
IN: Based on the text, a crosswalk that drivers often fail to notice might be improved by || making it more visually striking. || removing its markings. || painting it the same color as the road. || making it narrower. >> Visibility led to more yielding.

P: The following text is from a novel. Every year on the first snowfall, Grandmother Ana made hot chocolate and told the same story about the winter she met Grandfather. The grandchildren could recite it word for word and pretended to groan. But the year Grandmother was too ill to tell it, the youngest, Pilar, stood up in front of the fire, took a deep breath, and began: "It was the coldest winter anyone could remember..."
CI:: || When their grandmother is too ill to tell her traditional story, the youngest grandchild continues the tradition. || The grandchildren refuse to hear the story again. || Grandmother Ana tells a new story. || Pilar forgets how the story begins. >> Pilar takes up the story.
TS: Which choice best describes the function of the sentence "The grandchildren could recite it word for word and pretended to groan" in the text? || It shows that the tradition was familiar and more beloved than the children let on. || It explains why the grandmother became ill. || It describes the hot chocolate recipe. || It shows that the children disliked their grandmother. >> Their "pretended" groans hide affection.
IN: Based on the text, Pilar's decision to tell the story most likely reflects || the family's attachment to the tradition. || her wish to change the story's ending. || her dislike of snow. || an assignment from school. >> She keeps the tradition alive.
"""
