"""Passage units, batch 9 (format documented in passage_data1.py). Original texts; people and studies are illustrative."""

UNITS = """
P: When a coastal city's fishing industry declined, many old wooden boats were left to rot in the harbor. A group of retired shipwrights began restoring a few of them and offering free sailing lessons to local teenagers. The project grew into a program that now teaches boatbuilding skills, and several graduates have found jobs at repair yards along the coast.
CI:: || A volunteer effort to restore old boats grew into a program that teaches teenagers skills leading to jobs. || The city's fishing industry recovered after boats were restored. || Teenagers refused to learn sailing. || Retired shipwrights sold the old boats. >> Restoration became training and employment.
TS: Which choice best describes the overall structure of the text? || It describes a situation of decline, a response to it, and how that response developed. || It compares fishing and sailing. || It explains how wooden boats are built step by step. || It argues that harbors should be closed. >> Decline, restoration and lessons, and growth into job training.
IN: Based on the text, the program most likely benefits the community by || preserving traditional skills and creating job opportunities for young people. || increasing the number of fishing boats that rot. || replacing the city's harbor. || ending sailing lessons. >> Graduates work at repair yards.

P: The following text is from a novel. The letter from her brother arrived on the first day of spring, three years after their last argument. Mira read the single line twice—"I planted the tomatoes the way you always said"—and then sat down on the porch step and laughed until she cried. Their fight had been about something far larger than tomatoes, but she understood exactly what he meant.
CI:: || A brief, seemingly ordinary message from her brother signals reconciliation to Mira after a long estrangement. || Mira's brother writes to explain how to plant tomatoes. || Mira refuses to read her brother's letter. || Mira and her brother argue about gardening. >> The line about tomatoes is a gesture of peace.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It clarifies that the letter's meaning goes beyond its literal words. || It explains how to plant tomatoes. || It reveals that the argument was about gardening. || It describes Mira's porch. >> The fight was larger than tomatoes, yet she understands the message.
IN: Based on the text, the brother's line most likely suggests that he || is acknowledging Mira and wants to repair their relationship. || is still angry about the argument. || needs help with his garden. || is planning to visit the next day. >> Doing it "the way you always said" concedes to her.

P: Researchers who installed underwater microphones near a restored oyster reef found that the reef grew noisier over several years, filled with the clicks and grunts of fish and shrimp. The noise levels closely tracked increases in the numbers of animals divers counted. The researchers suggest that recording sound could offer a cheaper way to monitor reef recovery than frequent diving surveys.
CI:: || Sounds recorded on a restored reef tracked increases in animal life, suggesting that sound monitoring could cheaply measure reef recovery. || Oyster reefs became quieter as they recovered. || Divers counted fewer animals over time. || Underwater microphones harmed the reef. >> Noise matched animal counts.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It shows that the recorded sound corresponded to actual changes in animal numbers. || It explains how microphones are waterproofed. || It describes the types of oysters on the reef. || It argues that divers are unnecessary. >> Noise "closely tracked" counts.
IN: Based on the text, a restored reef whose recordings stayed quiet for several years would most likely || not be attracting many animals. || be recovering faster than other reefs. || have too many fish for divers to count. || need fewer microphones. >> Sound tracked animal abundance.

P: In the early twentieth century, many cities replaced horse-drawn carriages with automobiles, partly to solve a pollution problem: horse manure filled streets, attracting flies and spreading disease. Cars eliminated that problem but introduced new ones, including exhaust fumes and traffic accidents, that later generations would struggle to address.
CI:: || Automobiles solved the problem of horse manure in cities but created new problems of their own. || Horse-drawn carriages caused no pollution. || Cars had no negative effects on cities. || Cities returned to using horses. >> One solution produced new problems.
TS: Which choice best describes the function of the word "but" in the second sentence? || It introduces the drawbacks that followed the solution. || It explains why horses were used. || It describes the benefits of horses. || It shows that cars failed to reduce manure. >> "Eliminated that problem but introduced new ones."
IN: Based on the text, the author would most likely agree that || solutions to problems can create unexpected new challenges. || horses were better than cars in every way. || traffic accidents were common with horses. || exhaust fumes were a problem before cars. >> Cars solved one problem while creating others.

P: A psychologist studying how people judge the passage of time asked participants to estimate how long they had spent on various tasks. People consistently felt that time passed faster when they were absorbed in engaging activities and slower when they were bored or waiting, even when the actual durations were identical.
CI:: || People's sense of how much time has passed depends on how engaged they are, even when the actual time is the same. || People accurately estimate time regardless of their activity. || Boring tasks seem to pass faster than engaging ones. || Time actually moves faster during engaging tasks. >> Perception differs from real duration.
TS: Which choice best describes the function of the phrase "even when the actual durations were identical" in the text? || It emphasizes that the difference lay in perception rather than in actual time. || It shows that the tasks lasted different amounts of time. || It explains how participants chose tasks. || It suggests that the study was flawed. >> Identical durations isolate perception.
IN: Based on the text, someone waiting for a delayed train with nothing to do would most likely || feel that the wait lasted longer than it did. || feel that the wait was very short. || estimate the wait perfectly. || enjoy the wait more than an engaging activity. >> Waiting makes time feel slower.

P: When scientists studied honey found in ancient tombs, they discovered that some of it was still edible after thousands of years. Honey's low water content and high acidity make it inhospitable to bacteria, and bees add an enzyme that produces small amounts of hydrogen peroxide, which further prevents spoilage.
CI:: || Honey resists spoiling for very long periods because of its low moisture, acidity, and natural antibacterial compounds. || Honey spoils quickly without refrigeration. || Ancient honey was unsafe to eat. || Bees add water to honey to preserve it. >> Its chemistry prevents bacterial growth.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It explains the properties that account for the discovery described in the first sentence. || It describes how tombs were built. || It questions whether the honey was really edible. || It explains how bees collect nectar. >> Low water, acidity, and hydrogen peroxide.
IN: Based on the text, honey that absorbed a large amount of water would most likely || become more vulnerable to spoilage. || last even longer. || become more acidic. || turn into hydrogen peroxide. >> Low water content helps prevent bacteria.

P: A city that offered residents free compost bins found that participation varied widely by neighborhood. In areas where volunteers went door to door explaining how composting works, many more households used the bins than in areas where bins were simply delivered with printed instructions.
CI:: || Personal explanations from volunteers led to much higher use of free compost bins than printed instructions alone. || Printed instructions were more effective than volunteers. || Residents in all neighborhoods used compost bins equally. || The city stopped offering compost bins. >> Door-to-door outreach increased participation.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It identifies a factor associated with the differences in participation. || It describes the size of the compost bins. || It explains why the city offered free bins. || It argues that composting is difficult. >> Volunteer visits versus printed instructions.
IN: Based on the text, a city launching a new recycling program would most likely benefit from || having people explain the program directly to residents. || delivering bins without any instructions. || relying only on printed flyers. || limiting the program to one neighborhood. >> Personal outreach increased use.

P: The following text is from a memoir. My first apartment had a window that looked directly at a brick wall. For a year I resented it. Then one spring a pair of sparrows built a nest in a gap between the bricks, and I found myself waking early to watch them carry grass and string. By the time the chicks fledged, I had stopped thinking of it as a bad view.
CI:: || A pair of nesting sparrows changes the narrator's feelings about a view she had resented. || The narrator moves to a new apartment with a better view. || The narrator removes the sparrows' nest. || The narrator's window faces a park. >> Watching the birds transforms her view.
TS: Which choice best describes the overall structure of the text? || It describes an initial frustration, an event that changed it, and the narrator's new attitude. || It describes how sparrows build nests. || It compares two apartments. || It argues that brick walls are beautiful. >> Resentment, sparrows, and changed perspective.
IN: Based on the text, the narrator's waking early suggests that she || became interested in and attached to the sparrows. || had trouble sleeping because of noise. || needed to leave for work earlier. || wanted to chase the birds away. >> She watched them carry nesting material.

P: Astronomers studying a distant star noticed that its brightness dipped irregularly and by unusually large amounts, unlike the small, regular dips caused by orbiting planets. Some proposed that swarms of comets or clouds of dust were passing in front of it. Later observations showing that the dimming was stronger in blue light than red light supported the dust explanation, since fine dust blocks blue light more.
CI:: || Observations of how a star's dimming varied by color supported the idea that dust caused its irregular dimming. || The star dimmed because of a single orbiting planet. || The star's brightness never changed. || Dust blocks red light more than blue light. >> Color-dependent dimming pointed to dust.
TS: Which choice best describes the overall structure of the text? || It describes an unusual observation, possible explanations, and evidence favoring one of them. || It describes how telescopes measure color. || It compares two stars. || It argues that planets cause all dimming. >> Observation, proposals, and supporting evidence.
IN: Based on the text, if the star's dimming had been equal in blue and red light, the dust explanation would most likely have been || less strongly supported. || proven correct. || replaced by the planet explanation automatically. || unaffected. >> Dust predicts stronger blue dimming.

P: When an airline began allowing passengers to board from both the front and back doors of the plane, the average boarding time dropped by several minutes. Crowding in the aisle decreased because passengers seated near the rear no longer had to squeeze past those stowing bags in front rows.
CI:: || Boarding through both front and rear doors reduced aisle crowding and shortened boarding times. || Boarding from both doors made boarding slower. || Passengers preferred boarding only from the front. || Aisles became more crowded with two doors. >> Two doors reduced congestion.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It explains why boarding time decreased. || It describes the airline's routes. || It presents a drawback of the change. || It explains how bags are stowed. >> Less aisle crowding.
IN: Based on the text, passengers seated in the rear were most likely delayed before the change because they || had to wait while people in front rows put away their bags. || boarded before everyone else. || had no overhead bins. || used a different airplane. >> They had to "squeeze past those stowing bags."

P: Some trees in dense forests grow tall and thin, while trees of the same species growing in open fields spread wide branches and remain shorter. In a crowded forest, sunlight is limited at lower levels, so growing upward quickly helps a tree reach light. In an open field, sunlight is available all around, and wide branches can capture it efficiently.
CI:: || Trees of the same species grow differently depending on how much light is available in their surroundings. || Trees in forests are a different species from trees in fields. || Trees in open fields grow taller than forest trees. || Sunlight is abundant at low levels in dense forests. >> Shape reflects light availability.
TS: Which choice best describes the function of the second and third sentences in the text as a whole? || They explain the difference in tree shape described in the first sentence. || They describe how forests are planted. || They contradict the first sentence. || They compare trees with shrubs. >> Light conditions explain the shapes.
IN: Based on the text, a young tree growing in a gap where a large tree has fallen in the forest would most likely || have more light available at lower levels than trees in dense forest. || receive less light than before the tree fell. || stop growing entirely. || grow only underground. >> A gap opens the canopy.

P: When a school replaced traditional detention with a program in which students discussed what led to their behavior and how to make amends, repeat offenses declined. Teachers noted that students were more likely to apologize and less likely to see discipline as unfair. Some teachers, however, felt the conversations took too much time during busy school days.
CI:: || A discussion-based alternative to detention reduced repeat offenses and improved attitudes, though some teachers found it time-consuming. || Traditional detention reduced repeat offenses more. || Students refused to participate in the discussions. || All teachers preferred the new program. >> Benefits and a time concern.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It presents a concern about the program. || It describes the program's benefits. || It explains how detention used to work. || It argues that the program should expand. >> "However," some teachers found it time-consuming.
IN: Based on the text, students in the program were more likely to view discipline as fair most likely because || they had a chance to discuss their behavior and its effects. || they received no consequences. || detention lasted longer. || teachers stopped enforcing rules. >> Discussion made discipline feel more reasonable.

P: The following text is from a short story. Every summer, Grandpa Luis entered the county fair's pie contest, and every summer he lost to Mrs. Delgado. This year, when the judges announced that he had finally won, he did not cheer. He walked straight to Mrs. Delgado's table, cut a slice of her peach pie, and said, loudly enough for everyone to hear, "Still the best in the county."
CI:: || Upon finally winning the contest, Grandpa Luis graciously praises his longtime rival's pie. || Grandpa Luis celebrates loudly after beating Mrs. Delgado. || Mrs. Delgado wins the contest again. || Grandpa Luis refuses to enter the contest. >> He honors his rival instead of celebrating.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It establishes a long rivalry that gives meaning to Grandpa Luis's reaction. || It explains how pies are judged. || It describes Mrs. Delgado's recipe. || It reveals the contest's prize. >> Years of losing set up the gracious response.
IN: Based on the text, Grandpa Luis most likely speaks "loudly enough for everyone to hear" in order to || publicly honor Mrs. Delgado's skill. || embarrass Mrs. Delgado. || complain about the judges. || get a second prize. >> A public compliment shows respect.

P: When a company introduced a policy allowing employees to work any hours they chose as long as they completed their tasks, managers worried that collaboration would suffer. Communication did become harder at first. Teams responded by agreeing on a few core hours when everyone would be available, and surveys later showed high satisfaction with the flexible schedule.
CI:: || A flexible schedule initially made communication harder, but teams adapted by setting shared core hours, and employees were satisfied. || Flexible schedules ended all collaboration permanently. || Employees disliked the flexible schedule. || The company returned to fixed hours immediately. >> Early challenges were solved with core hours.
TS: Which choice best describes the overall structure of the text? || It describes a policy, an initial problem, the solution teams developed, and the outcome. || It compares two companies. || It explains how to write surveys. || It argues against flexible schedules. >> Policy, difficulty, core hours, and satisfaction.
IN: Based on the text, core hours were most likely intended to || make sure employees could communicate with one another at predictable times. || require everyone to work longer days. || replace the flexible schedule entirely. || reduce employee satisfaction. >> "When everyone would be available."

P: Biologists noticed that some species of butterfly that are harmless to birds closely resemble species that taste bitter or are toxic. Birds that have learned to avoid the toxic butterflies also tend to avoid the harmless look-alikes. The resemblance, researchers suggest, protects the harmless species even though it has no defenses of its own.
CI:: || Harmless butterflies that resemble toxic species are protected because birds avoid them too. || Harmless butterflies taste bitter to birds. || Birds prefer to eat toxic butterflies. || Toxic butterflies imitate harmless ones. >> Resemblance to toxic species deters birds.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It explains how the resemblance benefits the harmless butterflies. || It describes the butterflies' migration. || It contradicts the first sentence. || It explains how butterflies become toxic. >> Birds avoid look-alikes.
IN: Based on the text, if toxic butterflies disappeared from a region, the harmless look-alikes would most likely || lose some of the protection their appearance provides. || become toxic themselves. || be avoided even more strongly. || change color immediately. >> Birds would no longer learn to avoid the pattern.

P: Historians studying diaries from an eighteenth-century city found that residents frequently mentioned the price of bread. Entries describing price increases often appeared shortly before records of public protests. Some historians argue that the cost of basic food played a larger role in the city's unrest than political speeches, which receive more attention in traditional accounts.
CI:: || Diaries suggest that rising bread prices may have been a major cause of unrest in an eighteenth-century city. || Residents rarely mentioned food in their diaries. || Political speeches were the only cause of protests. || Bread prices fell before protests. >> Price increases preceded protests.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It presents an argument based on the diary evidence that challenges traditional emphasis. || It describes the city's government. || It explains how diaries were preserved. || It summarizes political speeches. >> Food costs versus political speeches.
IN: Based on the text, traditional accounts of the city's unrest most likely || focused more on political speeches than on food prices. || relied mainly on residents' diaries. || ignored political speeches entirely. || described bread prices in detail. >> Speeches "receive more attention in traditional accounts."

P: When a bakery began selling day-old bread at half price, the owner expected sales of fresh bread to fall. Instead, fresh bread sales held steady, and the discounted bread attracted new customers, some of whom later bought fresh items. Food waste at the bakery also dropped.
CI:: || Selling day-old bread at a discount attracted new customers and reduced waste without hurting fresh bread sales. || Fresh bread sales fell sharply after the discount. || The bakery stopped baking fresh bread. || Customers refused to buy day-old bread. >> Steady sales, new customers, and less waste.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It states an expectation that the results did not support. || It describes how bread is baked. || It explains why bread becomes stale. || It lists the bakery's products. >> The owner expected lower fresh sales.
IN: Based on the text, some new customers who bought discounted bread most likely || returned to buy fresh items as well. || stopped visiting the bakery. || complained about the prices. || bought only fresh bread from the start. >> "Some of whom later bought fresh items."

P: The following text is from a poem. I kept my grandmother's thimble / in a drawer for twenty years, / a silver cap too small / for any finger but her own. / Tonight I sewed a button / on my daughter's winter coat, / and without thinking, / I slipped the thimble on.
CI:: || The speaker unconsciously uses her grandmother's thimble while sewing, linking three generations. || The speaker throws away her grandmother's thimble. || The thimble fits the daughter perfectly. || The speaker's grandmother sews a coat. >> The thimble connects grandmother, speaker, and daughter.
TS: Which choice best describes the overall structure of the poem? || It describes a long-kept object and then a moment when the speaker uses it. || It lists items in a drawer. || It describes a winter storm. || It compares two coats. >> Kept for twenty years, then used.
IN: Based on the text, the phrase "without thinking" suggests that the speaker's action was || instinctive and connected to her grandmother's influence. || a deliberate decision made after long reflection. || a mistake she regretted. || required by her daughter. >> It happens naturally, echoing the grandmother.

P: A city testing electric buses found that they cost more to buy than diesel buses but less to fuel and maintain. Over a bus's expected lifetime, the total costs were roughly equal. The electric buses also reduced noise and exhaust along routes through dense neighborhoods, which residents reported appreciating.
CI:: || Electric buses cost more upfront but had similar lifetime costs to diesel buses and reduced noise and exhaust. || Electric buses cost less than diesel buses in every respect. || Residents complained about electric buses. || Diesel buses were cheaper to maintain. >> Lifetime costs were similar, with extra benefits.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It describes benefits beyond cost considerations. || It explains how electric buses are charged. || It shows that electric buses were more expensive overall. || It describes the bus routes. >> Reduced noise and exhaust.
IN: Based on the text, the city would most likely consider electric buses worthwhile because || their total cost was similar while offering environmental and quality-of-life benefits. || they were much cheaper to purchase. || residents preferred louder buses. || they required more fuel. >> Equal costs plus less noise and exhaust.
"""
