"""Passage units, batch 5 (format documented in passage_data1.py). Original texts; people and studies are illustrative."""

UNITS = """
P: When a remote island installed solar panels and batteries to replace its diesel generators, officials worried that cloudy weeks would leave residents without power. The system's designers addressed the concern by oversizing the battery bank and keeping one small generator for emergencies. In the first three years, the generator ran for a total of only eleven days, and the island's fuel costs fell by more than ninety percent.
CI:: || An island's switch to solar power with large batteries proved reliable and dramatically reduced fuel costs. || The island's solar system failed during cloudy weeks. || The island removed all of its generators. || Fuel costs on the island rose after the switch to solar power. >> The backup generator was rarely needed, and fuel costs fell sharply.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It explains how the designers responded to the concern raised in the first sentence. || It describes the island's geography. || It presents evidence that the concern was justified. || It explains why diesel generators were installed originally. >> Oversized batteries and a backup generator address cloudy weeks.
IN: Based on the text, the generator ran for only eleven days most likely because || the batteries usually stored enough solar energy to cover cloudy periods. || the island had no cloudy weather for three years. || residents stopped using electricity. || the generator was broken. >> The oversized battery bank reduced the need for backup power.

P: The following text is from a novel. Aunt Rosa's kitchen radio had been broken for years, stuck forever on a station that played old dance music. Everyone offered to buy her a new one. She refused. When I asked her why, she turned up the volume, took my hands, and spun me across the linoleum floor, laughing, until the song ended. "Now," she said, slightly out of breath, "you tell me what's broken."
CI:: || Aunt Rosa shows the narrator that the "broken" radio still brings her joy. || Aunt Rosa asks the narrator to fix her old radio. || Aunt Rosa dislikes dance music. || The narrator buys Aunt Rosa a new radio. >> By dancing to the music, she shows that nothing important is broken.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It suggests that Aunt Rosa sees the radio's limitation as unimportant compared with the pleasure it gives. || It reveals that Aunt Rosa has finally agreed to replace the radio. || It explains how the radio became stuck on one station. || It introduces a disagreement between Aunt Rosa and the narrator. >> Her question invites the narrator to rethink what "broken" means.
IN: Based on the text, Aunt Rosa refused a new radio most likely because || she enjoyed the music the old radio played. || new radios were too expensive. || she wanted to learn to repair it herself. || she rarely spent time in the kitchen. >> She dances happily to the station it is stuck on.

P: Ecologists studying a river noticed that trout populations were healthiest in stretches shaded by trees. Shade keeps water cooler, and cooler water holds more dissolved oxygen, which trout need. Where trees along the banks had been cleared for pasture, water temperatures rose in summer and trout numbers fell. Several landowners have since planted trees along the river to restore shade.
CI:: || Trees along a river help trout by shading the water, keeping it cool and rich in oxygen. || Trout prefer warm, sunny stretches of river. || Clearing trees along rivers increases the oxygen in the water. || Landowners removed trees to help trout populations. >> Shade leads to cooler, more oxygenated water and healthier trout.
TS: Which choice best describes the overall structure of the text? || It describes an observation, explains the reason behind it, gives supporting evidence, and notes a response. || It compares trout with other freshwater fish. || It describes how to plant trees along a riverbank. || It argues that pastures should be eliminated. >> Observation, cause, evidence from cleared areas, and replanting.
IN: Based on the text, a stretch of river where trees are planted would most likely || eventually become more suitable for trout. || become too cold for trout to survive. || lose dissolved oxygen. || require more pasture. >> Shade restores cooler, oxygen-rich water.

P: In the 1800s, many doctors did not wash their hands between examining patients. One physician noticed that women giving birth in a hospital ward staffed by doctors died of fever far more often than women in a ward staffed by midwives, who did not perform autopsies. He suspected that doctors were carrying something harmful from autopsies to patients and required them to wash their hands with a chlorine solution. Death rates in the doctors' ward fell dramatically.
CI:: || A physician's observation led him to require handwashing, which sharply reduced deaths in a hospital ward. || Midwives in the 1800s performed more autopsies than doctors. || Handwashing had no effect on death rates. || Doctors in the 1800s always washed their hands between patients. >> Comparing wards led to handwashing and fewer deaths.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It describes a comparison that led the physician to suspect a cause. || It explains how chlorine solutions were made. || It shows that the physician's idea was wrong. || It describes the physician's early life. >> The difference between wards pointed to autopsies.
IN: Based on the text, the fact that midwives did not perform autopsies was significant because it || helped explain why their patients were less likely to develop fever. || meant midwives worked fewer hours than doctors. || proved that midwives were better trained. || caused the physician to ban midwives. >> The key difference between the wards was autopsy work.

P: Some sea turtles nest on beaches lined with hotels and streetlights. Hatchlings typically find the ocean by crawling toward the brightest horizon, which on a natural beach is the moonlit sea. Artificial lights can lure them inland instead, where many die. Towns that require beachfront buildings to dim or shield their lights during nesting season have seen far more hatchlings reach the water.
CI:: || Artificial lighting can lead sea turtle hatchlings away from the ocean, and dimming lights helps more of them reach the water. || Sea turtle hatchlings find the ocean by following sounds. || Hotels near beaches help hatchlings reach the sea. || Hatchlings prefer to crawl toward dark areas inland. >> Hatchlings follow light; dimming lights helps them.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It explains the natural behavior that artificial lights interfere with. || It describes how towns regulate hotel lighting. || It presents the results of dimming lights. || It explains why turtles nest near hotels. >> Hatchlings crawl toward the brightest horizon.
IN: Based on the text, hatchlings on a beach with bright lights behind it would most likely || crawl toward the lights instead of the sea. || reach the ocean more quickly. || wait until morning to move. || stay buried in the sand. >> Artificial lights "can lure them inland."

P: The following text is from a memoir. I learned to swim in a cold lake at the age of nine, taught by my older brother, who was eleven and far more confident than he had any right to be. His method was simple: he stood waist-deep and told me to swim to him. Each time I got close, he took one step back. I was furious. By the end of the summer, I could swim across the entire cove.
CI:: || The narrator's brother used a simple trick to push her to swim farther, which frustrated her but made her a strong swimmer. || The narrator refused to learn to swim from her brother. || The narrator's brother was a professional swimming instructor. || The narrator learned to swim in a heated pool. >> By stepping back, he extended each swim, and she could soon cross the cove.
TS: Which choice best describes the function of the sentence "I was furious" in the text? || It conveys the narrator's childhood reaction to a method that later proved effective. || It explains why the narrator stopped swimming. || It shows that the brother was angry with the narrator. || It describes the temperature of the lake. >> Her anger contrasts with her eventual success.
IN: Based on the text, the brother stepped back each time the narrator got close most likely to || make her swim a little farther each time. || tease her until she gave up. || keep himself from getting cold. || avoid being splashed. >> Stepping back extended her swim, building her ability.

P: Many people believe that bulls are enraged by the color red. In fact, cattle cannot distinguish red from green. Experiments have shown that bulls charge at a moving cape regardless of its color, suggesting that the motion, not the color, provokes them. The red cape's use in bullfighting likely has more to do with tradition and showmanship than with any effect on the animal.
CI:: || Bulls respond to a cape's motion, not its color, so the red cape is more a matter of tradition than effect. || Bulls are enraged by the color red. || Cattle see colors exactly as humans do. || Bullfighters use red capes because bulls cannot see them. >> Experiments show motion, not color, triggers charging.
TS: Which choice best describes the overall structure of the text? || It presents a common belief, provides evidence against it, and offers another explanation for a related practice. || It describes the history of bullfighting in detail. || It compares the eyesight of several animals. || It argues that bulls should be trained differently. >> Belief about red, evidence of color blindness and motion, and tradition as the explanation.
IN: Based on the text, a bull facing a still red cape and a moving blue cape would most likely || charge at the moving blue cape. || charge at the still red cape. || ignore both capes. || charge only at a green cape. >> Motion provokes them regardless of color.

P: A company that designs video games tested two versions of a tutorial. In one, players read written instructions before starting. In the other, players learned controls gradually through short challenges during the first level. Players in the second group were more likely to finish the first level and to keep playing afterward. The company's designers concluded that people learn a game better by doing than by reading about it.
CI:: || Players who learned a game's controls through gradual challenges were more engaged than players who read instructions first. || Written instructions were more effective than in-game challenges. || Players preferred reading instructions before playing. || The company stopped including tutorials in its games. >> The challenge-based tutorial led to more completion and continued play.
TS: Which choice best describes the function of the second and third sentences in the text as a whole? || They describe the two versions being compared in the test. || They present the results of the test. || They explain why the company makes video games. || They argue against the designers' conclusion. >> One version uses reading, the other uses challenges.
IN: Based on the text, the designers would most likely recommend that a new game || introduce its controls through hands-on challenges during play. || begin with a long page of written rules. || remove its first level. || require players to read a manual before starting. >> They concluded that people learn "by doing."

P: Scientists once assumed that plants grow toward light simply because light speeds up growth. Later experiments revealed a more precise mechanism. A plant hormone gathers on the shaded side of a stem, causing cells there to lengthen faster than cells on the sunny side. Because the shaded side grows more, the stem bends toward the light.
CI:: || Plants bend toward light because a hormone makes cells on the shaded side of the stem grow faster. || Light makes all cells in a stem grow at the same rate. || Plants grow away from light to avoid damage. || Plant hormones gather on the sunny side of stems. >> Faster growth on the shaded side bends the stem toward light.
TS: Which choice best describes the overall structure of the text? || It describes an earlier assumption and then explains the mechanism that later experiments revealed. || It describes how to grow plants indoors. || It compares plants with animals. || It presents two theories and declares both incorrect. >> Assumption, then hormone mechanism.
IN: Based on the text, if a plant's hormone gathered evenly on all sides of its stem, the stem would most likely || grow straight rather than bending toward the light. || bend away from the light. || stop growing entirely. || bend toward the light more sharply. >> Bending results from uneven growth caused by the hormone's position.

P: The following text is from a short story. The chess club had lost every match that season. At the final tournament, twelve-year-old Imani faced the league's top player, a high school senior who had not lost a game in two years. Forty minutes in, the senior frowned, studied the board for a long time, and then extended his hand across the table. The room went silent. Imani stared at his hand before she understood.
CI:: || Imani, a young player from a struggling club, wins a game against the league's top player. || Imani loses her match to the league's top player. || The high school senior refuses to shake Imani's hand. || The chess club wins every match of the season. >> The undefeated senior extends his hand, conceding the game.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It establishes the club's poor record, making Imani's result more surprising. || It explains how Imani learned to play chess. || It describes the rules of the tournament. || It reveals the outcome of the final match. >> A losing season heightens the surprise of the win.
IN: Based on the text, Imani "stared at his hand before she understood" most likely because she || did not immediately realize that he was conceding the game. || did not want to shake hands with him. || thought he was asking for a pencil. || was unsure whether the tournament had begun. >> An offered handshake signals resignation, which she had not expected.

P: When a river city experienced repeated floods, planners considered building taller levees. Instead, they converted a strip of low-lying land along the river into a park designed to flood safely, with grassy fields and paths that could be submerged without serious damage. During heavy rains, the park absorbs overflow that would otherwise reach nearby streets. In dry months, residents use it for sports and picnics.
CI:: || A city reduced flooding by turning riverside land into a park that can safely hold floodwater and serve residents in dry months. || The city built taller levees along the river. || The park is closed to residents throughout the year. || Heavy rains no longer occur in the city. >> The floodable park absorbs overflow and serves as recreation space.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It describes an additional benefit of the park beyond flood control. || It explains why the city chose not to build levees. || It describes damage caused by recent floods. || It questions whether the park was effective. >> Sports and picnics add value in dry months.
IN: Based on the text, the park's grassy fields and paths were most likely chosen because they || can be flooded without being seriously damaged. || prevent all water from reaching the park. || cost more than other materials. || are rarely used by residents. >> The park was designed to be submerged safely.

P: Some cities have experimented with replacing traffic signals at busy intersections with roundabouts. At signals, cars sometimes speed through yellow lights, and the most dangerous crashes happen when vehicles collide at right angles. In roundabouts, all traffic moves in the same direction at lower speeds, so collisions that do occur tend to be glancing blows rather than direct hits. Studies of converted intersections have found large drops in serious injuries.
CI:: || Roundabouts can reduce serious injuries because traffic moves slowly in one direction, making severe collisions less likely. || Roundabouts cause more serious crashes than traffic signals. || Drivers speed up when entering roundabouts. || Cities have removed all roundabouts. >> Lower speeds and same-direction traffic reduce severe crashes.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It describes dangers at signaled intersections that roundabouts help avoid. || It explains how roundabouts are designed. || It presents the results of studies on roundabouts. || It argues that yellow lights should be longer. >> Speeding through yellow lights and right-angle crashes.
IN: Based on the text, a crash in a roundabout is likely to be less severe than one at a signal because || vehicles are moving more slowly and in the same direction. || roundabouts have no cars. || drivers in roundabouts never collide. || traffic signals make cars move more slowly. >> Collisions tend to be "glancing blows rather than direct hits."

P: Honeybee colonies are sometimes described as "superorganisms" because individual bees function somewhat like cells in a body. Worker bees specialize in tasks such as foraging, nursing larvae, and guarding the entrance, and the colony as a whole regulates its own temperature. No single bee directs these activities; instead, they emerge from countless interactions among individuals responding to simple cues.
CI:: || A honeybee colony behaves like a single organism, with coordinated activity emerging from interactions among bees rather than central control. || The queen bee directs every task in the colony. || Worker bees each perform every task in the colony. || Bee colonies cannot regulate their temperature. >> Specialization and self-regulation arise without a leader.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It explains how the colony's coordination occurs without a central leader. || It describes the physical appearance of worker bees. || It contradicts the comparison made in the first sentence. || It lists the tasks performed by worker bees. >> Activities "emerge from countless interactions."
IN: Based on the text, the comparison to "cells in a body" suggests that individual bees || contribute to the colony's survival through specialized roles. || can survive independently for long periods. || compete with one another for control. || all perform identical jobs. >> Like cells, bees specialize for the whole.

P: A study of college students found that those who wrote down three things they were grateful for each week reported higher life satisfaction after ten weeks than students who wrote about daily hassles or neutral events. The effect was modest, and the researchers cautioned that the study relied on students' own reports of how they felt.
CI:: || Writing about gratitude was linked to modestly higher reported life satisfaction, though the findings relied on self-reports. || Writing about daily hassles increased life satisfaction the most. || Gratitude journaling had a dramatic effect on students' health. || Students who wrote nothing were the happiest. >> The gratitude group reported slightly higher satisfaction, with a caution about self-report data.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It qualifies the study's finding by noting its limitations. || It describes how students were chosen for the study. || It presents a second finding that contradicts the first. || It explains why gratitude improves health. >> It notes a modest effect and reliance on self-reports.
IN: Based on the text, the researchers would most likely agree that || further research using measures other than self-reports would be useful. || the study proves that gratitude journaling cures unhappiness. || students' self-reports are always inaccurate. || writing about hassles is harmful. >> Their caution suggests a need for other kinds of evidence.

P: The following text is from a novel. Wen had moved to the city expecting noise, crowds, and strangers who never looked at one another. What surprised her was the bakery on the corner. The owner learned her name on her second visit, set aside a sesame roll for her each morning, and asked about her new job as though they had known each other for years. By winter, the corner no longer felt like part of a strange city. It felt like her street.
CI:: || A friendly bakery owner helps Wen feel at home in an unfamiliar city. || Wen finds the city exactly as unfriendly as she expected. || Wen opens a bakery after moving to the city. || Wen decides to return to her hometown by winter. >> The owner's warmth makes the corner feel like "her street."
TS: Which choice best describes the function of the first sentence in the text as a whole? || It presents Wen's expectations, which her experience at the bakery challenges. || It describes the bakery's location. || It explains why Wen chose her new job. || It reveals the ending of the story. >> She expected indifference but found personal attention.
IN: Based on the text, the owner setting aside a sesame roll each morning most likely shows that the owner || paid attention to Wen and made her feel welcome. || wanted Wen to buy more bread. || did not have enough rolls for other customers. || thought Wen was a new employee. >> It is one of several personal gestures that make Wen feel known.

P: In the early years of aviation, many engineers tried to build flying machines that flapped their wings like birds. These designs rarely worked. Later inventors achieved sustained flight by separating two functions that birds' wings combine: fixed wings provided lift, while propellers provided forward thrust. Studying birds was useful, but copying them too literally had led engineers astray.
CI:: || Successful early aircraft separated lift and thrust instead of directly imitating birds' flapping wings. || Early engineers built successful aircraft with flapping wings. || Birds do not use their wings for lift. || Propellers provide lift, while wings provide thrust. >> Fixed wings and propellers replaced flapping designs.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It states a general lesson drawn from the history described earlier. || It describes the first successful flight. || It explains how propellers work. || It suggests that engineers should stop studying birds. >> Studying birds helped, but literal copying misled engineers.
IN: Based on the text, the phrase "copying them too literally" most likely refers to || attempting to recreate birds' flapping motion in machines. || painting airplanes to look like birds. || using feathers as building materials. || studying how birds build nests. >> Flapping designs "rarely worked."

P: Researchers tracking city foxes with GPS collars found that the animals adjusted their routines to avoid people. Foxes that lived near busy parks were active mainly after midnight, while foxes in quieter suburbs often moved about in the early evening. The researchers noted that the foxes' diets also differed, with park foxes eating more discarded human food.
CI:: || City foxes adjusted when they were active depending on how busy their surroundings were, and their diets varied as well. || Foxes in all parts of the city followed identical schedules. || Foxes near busy parks were active mainly in the early evening. || City foxes avoid eating human food. >> Activity timing and diet differed by location.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It adds another difference between the two groups of foxes. || It explains how the GPS collars worked. || It contradicts the finding about activity times. || It describes why foxes live in cities. >> Diet is a second difference.
IN: Based on the text, foxes living near busy parks were most likely active after midnight because || fewer people were around at that time. || they preferred cold temperatures. || their GPS collars worked best at night. || suburban foxes chased them away in the evening. >> Foxes "adjusted their routines to avoid people."

P: A newspaper columnist argued that handwriting instruction wastes class time now that most writing is done on keyboards. A literacy researcher responded with evidence from studies of young children. Children who practiced forming letters by hand recognized letters more quickly and remembered spellings better than children who practiced only by typing. Handwriting, the researcher concluded, may support reading and spelling even if adults later write mostly by keyboard.
CI:: || A researcher cited evidence that practicing handwriting may help young children learn letters and spelling, countering a claim that it wastes time. || Children who typed learned letters faster than those who wrote by hand. || The columnist and the researcher agreed that handwriting should be eliminated. || Adults write mainly by hand. >> Evidence about letter recognition and spelling supports handwriting practice.
TS: Which choice best describes the overall structure of the text? || It presents an argument, introduces a response, and describes the evidence and conclusion supporting that response. || It describes the history of keyboards. || It compares two methods of teaching adults. || It explains how newspapers choose columnists. >> Columnist's claim, researcher's evidence and conclusion.
IN: Based on the text, the researcher would most likely respond to the columnist by noting that || the benefits of handwriting practice may extend beyond the ability to write by hand. || children should never use keyboards. || typing is unnecessary for adults. || handwriting instruction should begin in high school. >> Handwriting "may support reading and spelling."

P: The following text is from a poem. The oak does not hurry. / It adds a ring a year, / a thin brown line of patience / no one sees. / Storms come, and summers, / and the children who climbed it / grow tall and move away, / and still it adds its ring.
CI:: || The poem describes the oak's slow, steady growth, which continues regardless of what happens around it. || The poem describes an oak tree destroyed by a storm. || The speaker regrets climbing the oak as a child. || The oak grows quickly compared with other trees. >> "It adds its ring" despite storms and passing years.
TS: Which choice best describes the function of the final line of the poem? || It emphasizes the tree's persistence by repeating the image of adding a ring. || It introduces a new character. || It reveals that the tree has died. || It describes the children's return. >> "And still it adds its ring" echoes the second line.
IN: Based on the text, the phrase "no one sees" suggests that the oak's growth is || gradual and easy to overlook. || hidden underground. || visible only to children. || too fast to observe. >> A thin ring each year is not noticed.

P: Many people think of deserts as places with no water, but some desert animals obtain nearly all the moisture they need from food. Kangaroo rats, for example, rarely drink. They get water from seeds, and their kidneys produce extremely concentrated urine, conserving what little water they take in. They also spend the hottest hours in cool burrows, reducing moisture lost through breathing.
CI:: || Kangaroo rats survive in deserts by getting water from food and conserving it in several ways. || Kangaroo rats drink large amounts of water each day. || Desert animals cannot survive without drinking water. || Kangaroo rats spend the hottest hours above ground. >> Seeds, kidneys, and burrows help them manage water.
TS: Which choice best describes the function of the second, third, and fourth sentences in the text as a whole? || They provide an example that supports the claim in the first sentence. || They present evidence against the claim in the first sentence. || They explain how deserts form. || They compare kangaroo rats with camels. >> Kangaroo rats illustrate animals that get water from food.
IN: Based on the text, a kangaroo rat kept in a very hot enclosure with no burrow would most likely || lose more moisture than it would in the wild. || stop needing water entirely. || begin drinking seawater. || produce less concentrated urine. >> Burrows reduce moisture loss during the hottest hours.

P: When a public radio station began publishing transcripts of its programs online, some staff feared that people would read instead of listen, reducing the audience. Traffic data showed the opposite. Many readers who found transcripts through internet searches clicked to listen to the original broadcasts, and the station's online listening hours increased.
CI:: || Publishing program transcripts online attracted new listeners rather than reducing the radio station's audience. || Transcripts caused listeners to stop listening to the radio. || The station stopped publishing transcripts because of low traffic. || Staff unanimously supported publishing transcripts. >> Search readers clicked to listen, raising listening hours.
TS: Which choice best describes the function of the sentence "Traffic data showed the opposite" in the text? || It signals that the evidence contradicted the staff's fear. || It describes how the station collected data. || It explains why transcripts were published. || It indicates that the audience declined. >> Staff feared a decline; the data showed growth.
IN: Based on the text, the transcripts most likely helped the station by || making its programs easier for new audiences to discover. || replacing the need for broadcasts. || reducing the number of programs it produced. || preventing people from reading about the programs. >> Readers found transcripts through searches and then listened.

P: Paleontologists once imagined large dinosaurs as slow, cold-blooded animals that dragged their tails. Evidence from fossil trackways, which show tails held off the ground, and from bone growth rings, which suggest rapid growth, has changed that view. Many scientists now picture dinosaurs as active animals, some possibly warm-blooded, with tails held out for balance.
CI:: || Fossil evidence has led scientists to see many dinosaurs as active animals rather than slow, tail-dragging ones. || Dinosaurs dragged their tails along the ground. || Scientists agree that all dinosaurs were cold-blooded. || Fossil trackways show that dinosaurs could not walk. >> Trackways and growth rings changed the older view.
TS: Which choice best describes the overall structure of the text? || It describes an older view, presents evidence that changed it, and states the newer view. || It describes how fossils form. || It compares dinosaurs with modern reptiles. || It explains why dinosaurs became extinct. >> Old view, evidence, and new view.
IN: Based on the text, fossil trackways without tail marks are significant because they suggest that dinosaurs || held their tails off the ground. || had no tails. || walked only in water. || dragged their tails constantly. >> Trackways "show tails held off the ground."

P: A city parks department noticed that its public benches were rarely used. Designers observed that most benches faced empty lawns or walls. They moved several benches to face walkways, playgrounds, and a fountain, where people could watch activity. Within weeks, the relocated benches were among the most used in the park, while those left in place remained mostly empty.
CI:: || Moving park benches to face activity greatly increased how often people used them. || People prefer benches facing empty lawns. || The parks department removed all of its benches. || Benches were used equally regardless of their position. >> Relocated benches facing activity became popular.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It compares relocated benches with unmoved ones to show the change's effect. || It explains why the benches were originally placed facing walls. || It describes how the benches were built. || It suggests that the relocation failed. >> Moved benches were used; unmoved benches stayed empty.
IN: Based on the text, the designers would most likely conclude that people choose where to sit partly based on || whether there is something interesting to watch. || how new the benches are. || how far the benches are from the parking lot. || whether the benches are made of wood. >> Benches facing activity became the most used.

P: The following text is adapted from a nineteenth-century novel. Mr. Ashworth prided himself on never changing his mind. He had decided at twenty that the new railway would ruin the countryside, and at seventy he still refused to ride it. When his granddaughter fell ill in the city, however, he was seen at the station before dawn, buying a ticket with shaking hands.
CI:: || Mr. Ashworth abandons a lifelong stance when his granddaughter needs him. || Mr. Ashworth has always enjoyed riding the railway. || Mr. Ashworth refuses to visit his granddaughter. || Mr. Ashworth's granddaughter builds a railway. >> He buys a ticket to reach her despite decades of refusal.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It establishes a character trait that makes his final action significant. || It describes the railway's route. || It explains why the granddaughter moved to the city. || It reveals that Mr. Ashworth is ill. >> His pride in never changing his mind makes buying the ticket striking.
IN: Based on the text, Mr. Ashworth's "shaking hands" most likely reflect || his worry about his granddaughter and the difficulty of breaking a long-held vow. || the cold weather in the countryside. || his excitement about riding a train for fun. || his anger at the ticket seller. >> He is anxious about her illness and acting against his principles.

P: Beekeepers in one region reported that their honey tasted different from year to year. Chemists analyzing samples found that the flavor compounds in the honey closely matched the flowers that had bloomed most heavily each season. In years when wild thyme was abundant, for example, the honey contained compounds associated with thyme's distinctive flavor.
CI:: || Variations in honey flavor reflect which flowers bloomed most heavily in a given season. || Honey tastes the same regardless of which flowers bees visit. || Beekeepers add thyme to honey to change its flavor. || Chemists could not identify any flavor compounds in the honey. >> Flavor compounds matched each season's dominant flowers.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It provides a specific example of the pattern the chemists found. || It explains how honey is harvested. || It contradicts the beekeepers' observation. || It describes why thyme grows in the region. >> Thyme years illustrate the flower-flavor link.
IN: Based on the text, honey produced in a year when lavender bloomed heavily would most likely || contain flavor compounds associated with lavender. || taste exactly like the previous year's honey. || have no flavor at all. || contain compounds associated with thyme only. >> Honey flavor reflects the most abundant flowers.

P: Some schools have replaced traditional letter grades with detailed written feedback. Supporters argue that grades encourage students to focus on scores rather than learning. In one study, students who received only comments on their essays improved more on later assignments than students who received grades alone. Students who received both grades and comments, however, improved about as little as those who received grades alone, apparently paying attention mainly to the grade.
CI:: || A study found that essay comments helped students improve most when they were not accompanied by grades. || Students improved most when they received both grades and comments. || Grades alone produced the largest improvement. || Written comments had no effect on student writing. >> Comments alone led to the most improvement; grades seemed to draw attention away.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It presents a finding that suggests grades can reduce the benefit of comments. || It explains why schools use letter grades. || It describes how the essays were scored. || It restates the finding in the third sentence. >> Grades plus comments performed like grades alone.
IN: Based on the text, students who received both grades and comments improved little most likely because || they focused on their grades and paid less attention to the comments. || their comments were less detailed. || they wrote fewer essays. || they did not receive any feedback. >> They were "apparently paying attention mainly to the grade."

P: Coastal fog is an important water source for some redwood forests. Scientists measuring moisture found that during dry summers, redwoods absorb water from fog through their leaves, and fog dripping from branches can supply a substantial share of the water reaching the forest floor. Researchers are concerned that warming ocean temperatures could reduce fog along the coast.
CI:: || Redwood forests rely partly on fog for water, so reductions in coastal fog could threaten them. || Redwoods receive all of their water from rainfall. || Warming oceans will increase fog along the coast. || Fog harms redwood leaves. >> Fog supplies summer moisture; less fog is a concern.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It raises a concern that follows from the importance of fog described earlier. || It explains how scientists measured moisture. || It describes redwoods' height. || It contradicts the scientists' findings. >> Less fog would matter because redwoods depend on it.
IN: Based on the text, a summer with much less coastal fog would most likely || leave redwood forests with less water during the dry season. || make redwood forests wetter than usual. || have no effect on redwood forests. || cause redwoods to absorb more water through their roots from fog. >> Fog provides water "during dry summers."

P: The following text is from a short story. The science fair judges had moved on, and Dario's volcano had not erupted. He had checked the vinegar and the baking soda twice. His friends drifted away to watch a robot that played music. Alone at his table, Dario lifted the lid of the volcano and saw it: a folded note from his little sister, taped inside, blocking the tube. It read, "Good luck!!!"
CI:: || Dario discovers that his volcano failed because his sister's well-meaning note was blocking it. || Dario's volcano erupts in front of the judges. || Dario's friends sabotage his project. || Dario's sister builds a robot for the science fair. >> The "Good luck" note blocked the tube.
TS: Which choice best describes the overall structure of the text? || It describes a disappointing failure and then reveals its unexpected cause. || It describes how to build a volcano model step by step. || It compares Dario's project with his friends' projects. || It explains why the judges chose the winners. >> The failure, then the note's discovery.
IN: Based on the text, the note in the volcano is best described as || a kind gesture that accidentally caused a problem. || a deliberate attempt to ruin the project. || a message from the judges. || instructions for fixing the volcano. >> It says "Good luck!!!" yet blocked the tube.
"""
