"""Passage units, batch 10 (format documented in passage_data1.py). Original texts; people and studies are illustrative."""

UNITS = """
P: Many hikers assume that a trail's difficulty depends mainly on its length. A park service that surveyed visitors found that elevation gain and uneven footing predicted how tiring people found a trail far better than distance did. Several short, steep, rocky trails were rated harder than much longer trails over gentle ground. The park revised its trail signs to list elevation gain alongside distance.
CI:: || A survey showed that elevation gain and footing affect a trail's difficulty more than length, leading a park to revise its signs. || Longer trails are always harder than shorter trails. || Visitors found rocky trails easier than smooth trails. || The park removed distance information from its signs. >> Steepness and terrain mattered more.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It presents a common assumption that the survey results challenge. || It describes the park's most popular trail. || It explains how trail signs are made. || It summarizes the park's response. >> Hikers assume length matters most.
IN: Based on the text, the revised signs were most likely intended to || help visitors judge a trail's difficulty more accurately. || discourage visitors from hiking. || shorten the trails. || replace maps entirely. >> Elevation gain predicted tiredness better.

P: The following text is from a novel. For years, Ines had walked past the abandoned greenhouse on her way to work, noting its broken panes and the vines pressing against the glass. One morning she stopped, pushed open the rusted door, and stepped inside. Among the weeds, a single orange tree still stood, heavy with small, bright fruit, as if it had been waiting all this time for someone to notice.
CI:: || Ines discovers that a neglected greenhouse still holds a thriving orange tree. || Ines decides to tear down the greenhouse. || The greenhouse is filled with healthy plants that someone tends daily. || Ines works in the greenhouse every morning. >> A surprising sign of life in a neglected place.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It establishes the greenhouse's neglect, which makes the discovery inside surprising. || It explains why Ines changed jobs. || It describes the orange tree in detail. || It reveals who owns the greenhouse. >> Broken panes and vines suggest abandonment.
IN: Based on the text, the phrase "as if it had been waiting all this time for someone to notice" suggests that Ines || feels a sense of wonder at finding the tree. || is disappointed by what she finds. || planted the tree years ago. || expected the tree to be there. >> The image conveys surprise and wonder.

P: Researchers studying rats found that animals given access to running wheels learned their way through mazes faster than rats without wheels. The exercising rats also showed more new neuron growth in a brain region associated with memory. The researchers caution that rats differ from humans but suggest that exercise may support learning in other animals as well.
CI:: || Rats that exercised learned mazes faster and grew more new neurons, suggesting exercise may aid learning. || Exercise slowed rats' learning. || Rats without wheels grew more neurons. || The study proved that exercise improves human memory. >> Faster learning and more neuron growth.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It acknowledges a limitation while suggesting a broader implication. || It describes how the mazes were built. || It contradicts the findings about neurons. || It explains why rats like running wheels. >> Caution about rats versus humans.
IN: Based on the text, the researchers would most likely want to test next whether || similar effects of exercise occur in other species. || rats can run faster than mice. || mazes are harder without walls. || rats prefer wheels to food. >> They suggest exercise "may support learning in other animals."

P: When a city first installed bike lanes painted on the road, many cyclists still felt unsafe riding next to fast traffic. The city later tested lanes separated from cars by concrete barriers. On streets with protected lanes, the number of cyclists rose sharply, especially among people who described themselves as cautious riders.
CI:: || Physically protected bike lanes attracted many more cyclists, particularly cautious riders, than painted lanes did. || Painted bike lanes attracted more cyclists than protected lanes. || Cautious riders avoided protected bike lanes. || The city removed all bike lanes. >> Barriers made riders feel safer.
TS: Which choice best describes the overall structure of the text? || It describes a limitation of one approach and the improved results of another. || It explains how concrete barriers are made. || It compares cycling in two cities. || It argues that bicycles should be banned. >> Painted lanes fell short; protected lanes succeeded.
IN: Based on the text, protected lanes most likely attracted cautious riders because they || made cyclists feel safer from nearby traffic. || were painted brighter colors. || were located only in parks. || allowed cars to drive in them. >> Riders "felt unsafe riding next to fast traffic" otherwise.

P: Some caves contain formations called stalactites, which hang from ceilings like icicles. They form over thousands of years as water dripping from the ceiling leaves behind tiny amounts of dissolved minerals. Because they grow so slowly, scientists can analyze their layers to learn about past rainfall and climate in the region.
CI:: || Stalactites form slowly from mineral deposits, and their layers can reveal information about past climate. || Stalactites form in a few days. || Stalactites grow upward from cave floors. || Scientists cannot learn anything from stalactites. >> Slow growth preserves climate records.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It explains a scientific use that follows from how stalactites form. || It describes the appearance of stalactites. || It explains why caves are dark. || It questions how stalactites form. >> Slow growth allows climate analysis.
IN: Based on the text, a period of very little rainfall would most likely be reflected in a stalactite as || a change in its layers, since less water would drip from the ceiling. || a sudden increase in its length. || the stalactite falling from the ceiling. || no change at all. >> Layers record water and mineral deposition.

P: The following text is from a memoir. My grandfather taught me to fish on a lake so quiet that you could hear a dragonfly land. He never seemed to care whether we caught anything. When I asked him why we kept coming back on days when the fish would not bite, he pointed his rod at the mist rising off the water and said, "We're not really here for the fish."
CI:: || The narrator's grandfather values the peaceful experience of fishing more than catching fish. || The grandfather is frustrated when they catch nothing. || The narrator dislikes going fishing. || The lake is too noisy for fishing. >> "We're not really here for the fish."
TS: Which choice best describes the function of the first sentence in the text as a whole? || It establishes the peaceful setting that the grandfather values. || It describes how to catch fish. || It explains why the fish did not bite. || It introduces a conflict between the narrator and grandfather. >> The quiet lake sets up his point.
IN: Based on the text, the grandfather's gesture toward the mist suggests that he || appreciated the beauty of the lake. || wanted to fish in another spot. || thought the mist scared the fish. || was ready to leave. >> He points to the scenery while explaining why they come.

P: When an online retailer began showing delivery dates rather than shipping speeds, such as "arrives Thursday" instead of "ships in three to five days," customers were more likely to complete purchases. Researchers suggest that a specific date is easier for shoppers to understand and plan around than a range of days.
CI:: || Showing specific delivery dates instead of shipping ranges increased completed purchases, likely because dates are easier to understand. || Shoppers preferred vague shipping estimates. || Displaying delivery dates reduced sales. || Customers ignored delivery information. >> Specific dates helped shoppers plan.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It offers an explanation for the change in customer behavior. || It describes how packages are shipped. || It contradicts the first sentence. || It explains how prices were set. >> Dates are easier to plan around.
IN: Based on the text, a shopper needing a gift by a certain day would most likely find which information most useful? || A specific expected arrival date || A general shipping speed range || The weight of the package || The location of the warehouse >> Specific dates help planning.

P: Scientists studying a mountain lake found that its water had become clearer over several decades. At first they suspected reduced pollution. Further investigation showed that an invasive species of mussel, which filters tiny particles from the water, had spread throughout the lake. The mussels made the water clearer but also removed plankton that native fish depend on for food.
CI:: || An invasive mussel made a lake's water clearer while depleting plankton that native fish need. || Reduced pollution was the only reason the lake became clearer. || Native fish benefited from the invasive mussels. || The lake's water became cloudier over time. >> Clearer water came with harm to the food web.
TS: Which choice best describes the overall structure of the text? || It describes a change, an initial explanation, the actual cause, and that cause's negative effect. || It compares two lakes. || It explains how mussels reproduce. || It argues that lakes should be drained. >> Clearer water, suspected cause, mussels, and harm to fish.
IN: Based on the text, native fish populations in the lake would most likely || decline because of reduced food. || increase because of clearer water. || remain unaffected by the mussels. || begin eating the mussels exclusively. >> Mussels removed plankton the fish depend on.

P: Some schools have introduced "reading buddies" programs in which older students read with younger ones. Teachers in one school reported that younger children's reading improved, as expected. They were surprised to find that many older students who struggled with reading also showed gains, perhaps because reading aloud to younger children gave them low-pressure practice.
CI:: || A reading buddies program helped younger children and also struggling older students who read to them. || Only younger children benefited from the program. || Older students' reading declined. || Teachers ended the program because of poor results. >> Unexpected gains for older struggling readers.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It presents an unexpected benefit and a possible reason for it. || It describes how buddies were paired. || It restates the expected result. || It explains why younger children struggle. >> Surprising gains with an explanation.
IN: Based on the text, reading aloud to younger children most likely helped struggling older students because it || let them practice in a comfortable, low-pressure setting. || required them to read difficult novels. || replaced their regular classes. || involved competitive tests. >> "Low-pressure practice."

P: The following text is from a poem. The lamp in the window of the corner store / has burned each night for forty years. / Travelers who have never met the owner / measure their journeys by its light, / and though it saves no lives, / it tells them, turning the last corner, / that someone, somewhere on this street, / is still awake.
CI:: || A long-burning store lamp comforts travelers by signaling that someone is awake nearby. || The store lamp guides ships safely to shore. || The store owner turns off the lamp each night. || Travelers dislike the lamp's light. >> The lamp offers reassurance.
TS: Which choice best describes the function of the phrase "though it saves no lives" in the poem? || It acknowledges the lamp's modest practical importance before emphasizing its emotional value. || It suggests that the lamp is dangerous. || It explains how the lamp is powered. || It describes the owner's job. >> Modest role, but meaningful comfort.
IN: Based on the text, travelers "measure their journeys by its light" most likely because the lamp || serves as a familiar landmark signaling they are near their destination. || shows the exact distance they have traveled. || is the only light in the city. || belongs to their family. >> It marks "turning the last corner."

P: Engineers testing a new type of road surface made of porous pavement found that rainwater drained through it rather than running off. During storms, streets with the new surface had less standing water, and nearby storm drains overflowed less often. In cold regions, however, water trapped in the pavement could freeze and damage it, requiring more maintenance.
CI:: || Porous pavement reduced runoff and flooding but can require more maintenance in cold climates. || Porous pavement increases standing water. || The new surface works best in freezing climates. || Storm drains overflowed more with porous pavement. >> Drainage benefits and a cold-weather drawback.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It presents a limitation of the pavement in certain conditions. || It describes how the pavement is manufactured. || It explains the benefits of the pavement. || It describes storm drains. >> Freezing water can damage it.
IN: Based on the text, porous pavement would most likely be most practical in || regions with frequent rain and mild winters. || regions with long, freezing winters. || areas with no rainfall. || underground tunnels. >> It helps with storms but struggles with freezing.

P: A study of restaurant tipping found that servers who wrote "thank you" on customers' bills received slightly higher tips on average than servers who did not. The effect was small but consistent across many meals. The researchers suggest that small gestures of friendliness can influence how people respond, even in routine transactions.
CI:: || Writing "thank you" on bills was linked to slightly higher tips, suggesting small friendly gestures affect responses. || Customers tipped less when servers wrote messages. || The message had a large effect on tips. || Tipping is unaffected by servers' behavior. >> Small but consistent effect.
TS: Which choice best describes the function of the phrase "The effect was small but consistent" in the text? || It qualifies the finding while indicating that it was reliable. || It shows that the study failed. || It describes how bills were printed. || It explains why customers tip. >> Small size, reliable pattern.
IN: Based on the text, the researchers would most likely agree that || minor friendly gestures can make a measurable difference in people's behavior. || tips are determined entirely by food quality. || customers dislike messages on bills. || servers should stop thanking customers. >> Small gestures "can influence how people respond."

P: For many years, cities built public housing as large, isolated high-rise complexes. Critics later argued that concentrating many low-income families in one place limited access to jobs and services. More recent programs have favored mixed-income developments spread throughout neighborhoods, which some studies suggest can improve residents' access to opportunities.
CI:: || Approaches to public housing have shifted from isolated high-rises toward mixed-income developments intended to improve residents' opportunities. || Cities continue to build only isolated high-rises. || Concentrated housing improved access to jobs. || Mixed-income developments have been proven harmful. >> Changing approach and reasons.
TS: Which choice best describes the overall structure of the text? || It describes an earlier approach, criticism of it, and a newer approach. || It describes the architecture of one building. || It compares housing prices in two cities. || It argues that public housing should end. >> Old model, critique, new model.
IN: Based on the text, supporters of mixed-income developments most likely believe that || spreading housing throughout neighborhoods gives residents better access to jobs and services. || families should be concentrated in one area. || high-rise buildings are always unsafe. || housing has no effect on opportunity. >> They respond to criticism about limited access.

P: The following text is from a short story. The night before the move, Sara walked through the empty house one last time. Without furniture, every room sounded different, her footsteps echoing where the couch and bookshelves had once absorbed them. In her old bedroom, she pressed her hand against the wall where she had marked her height each birthday, the pencil lines still faintly visible, then turned off the light.
CI:: || On her last night in her childhood home, Sara quietly revisits reminders of growing up there. || Sara is excited to leave the house immediately. || Sara paints over the height marks on the wall. || Sara's family decides not to move. >> The empty rooms and height marks evoke memories.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It emphasizes how different the house feels now that it is empty. || It describes the new house Sara will move to. || It explains why the family is moving. || It lists the furniture that was sold. >> Echoing footsteps show the change.
IN: Based on the text, Sara's pressing her hand against the wall most likely shows || her attachment to memories of growing up in the house. || her anger about moving. || her plan to measure her height again. || that she is checking for damage. >> The height marks represent her childhood.

P: Botanists studying seeds stored in a frozen seed bank found that most seeds remained capable of sprouting after decades, but the rate varied widely by species. Some seeds lost viability quickly even when frozen, suggesting that seed banks may need different storage methods, or more frequent replanting and collection, for certain plants.
CI:: || Frozen seed storage works for many species but not all, suggesting some plants need different methods. || All seeds lose viability quickly when frozen. || Seed banks are unnecessary. || Every species' seeds stay viable forever when frozen. >> Viability varied by species.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It describes an exception and its implication for seed bank practices. || It explains how seed banks are built. || It restates that most seeds survive. || It describes the history of seed banks. >> Some seeds lose viability quickly.
IN: Based on the text, a seed bank storing seeds of a species that loses viability quickly would most likely need to || replace its stored seeds more often or find another storage method. || stop collecting that species. || freeze the seeds at warmer temperatures. || plant all its other seeds immediately. >> Different methods or more frequent replanting.
"""
