"""Passage units, batch 1. Each unit: P: passage, then question lines.
Question line: KIND: prompt || correct || wrong || wrong || wrong >> short reason
KIND is CI (central ideas), TS (text structure/purpose), IN (inferences). Use CI:: / TS:: to use the default prompt.
Passages are original; studies and people are illustrative."""

UNITS = """
P: For decades, farmers in one river valley burned the stubble left in their rice fields after each harvest. Burning was fast and cheap, but it filled the air with smoke for weeks. When a local cooperative offered to buy the stubble instead, many farmers were skeptical that anyone would want it. Within three years, however, the cooperative was turning the straw into packaging material and selling it to companies across the region, and the autumn smoke had largely disappeared.
CI:: || A cooperative's decision to buy rice stubble gave farmers an alternative to burning it and reduced smoke in the valley. || Farmers in the valley have stopped growing rice because burning stubble became too expensive. || Packaging made from straw is stronger than packaging made from other materials. || Most farmers in the valley still prefer to burn their rice stubble after each harvest. >> The text moves from the old practice (burning) to the cooperative's offer and its results: straw became packaging and the smoke largely disappeared.
TS: Which choice best describes the overall structure of the text? || It describes a long-standing practice and its drawback, then explains how a new option changed that practice. || It compares two methods of growing rice and argues that one is more profitable. || It presents a debate among farmers and then explains why the debate remains unresolved. || It traces the history of rice farming in the valley from its beginnings to the present. >> Old practice and its problem (smoke), then the cooperative's offer and its effects.
IN: Based on the text, why were many farmers initially skeptical of the cooperative's offer? || They doubted that there was any demand for rice stubble. || They believed that burning stubble improved the soil. || They thought the cooperative would pay too little. || They worried that selling stubble was illegal. >> The text says they were skeptical "that anyone would want it."

P: The following text is from a novel. Mrs. Achebe had taught piano in the same small room for forty years. The upright piano had a cracked key and a pedal that squeaked, and every student eventually asked why she did not replace it. She always gave the same answer: a perfect instrument forgives too much. On this one, she said, you have to listen.
CI:: || Mrs. Achebe believes that playing an imperfect piano teaches students to listen more carefully. || Mrs. Achebe cannot afford to replace her old piano. || Mrs. Achebe's students prefer practicing on newer instruments. || Mrs. Achebe plans to retire after forty years of teaching. >> Her answer, "a perfect instrument forgives too much ... you have to listen," explains why she keeps it.
TS: Which choice best states the main purpose of the text? || To reveal a character's view about the value of an imperfect instrument || To describe the process of repairing an old piano || To contrast the teaching methods of two piano teachers || To explain why a character decided to stop teaching >> The details about the flawed piano set up her explanation of why she keeps it.
IN: Based on the text, what can most reasonably be inferred about Mrs. Achebe's students? || They tend to notice the piano's flaws. || They rarely practice outside of lessons. || They are mostly adults. || They think the piano has an unusually beautiful sound. >> "Every student eventually asked why she did not replace it," so they notice the cracked key and squeaky pedal.

P: Many people assume that desert plants survive by storing large amounts of water. Some do, but a surprising number take a different approach. Certain desert shrubs drop nearly all of their leaves during dry months, reducing the surface through which water can escape. When rain returns, they grow a new set of leaves within days and resume making food. For these plants, survival depends less on saving water than on knowing when to stop using it.
CI:: || Some desert plants survive dry periods by temporarily shedding their leaves rather than by storing water. || All desert plants store large amounts of water in their stems. || Desert shrubs grow new leaves only once every several years. || Desert plants lose more water through their roots than through their leaves. >> The text contrasts the common assumption (storing water) with shrubs that drop leaves and regrow them after rain.
TS: Which choice best describes the function of the first sentence in the text as a whole? || It introduces a common belief that the rest of the text qualifies. || It provides evidence for the claim made in the final sentence. || It describes a finding that researchers later confirmed. || It defines a term that the text uses throughout. >> The text says "some do, but" and then describes a different strategy.
IN: Based on the text, what would most likely happen to one of these shrubs if it kept all its leaves throughout the dry months? || It would lose more water than it does when it drops its leaves. || It would stop producing new leaves after the next rain. || It would store more water in its stems. || It would grow faster during the dry months. >> Dropping leaves reduces "the surface through which water can escape," so keeping them would mean losing more water.

P: When the city opened its first public library branch in a converted bus station, officials expected it to be used mostly for borrowing books. Instead, the busiest part of the building turned out to be a row of tables with electrical outlets. Students came to charge laptops and do homework, job seekers used the free internet to fill out applications, and retirees gathered to read newspapers. Within a year, the library had added twice as many tables and cut back its shelf space.
CI:: || A new library branch became valued more as a place to work and gather than as a place to borrow books. || The city's first library branch failed to attract many visitors. || Students prefer libraries that are located in former bus stations. || Borrowing books has become more popular than using the internet at libraries. >> The unexpected popularity of tables and outlets led the library to add tables and cut shelf space.
TS: Which choice best describes the overall structure of the text? || It presents an expectation, describes what actually happened, and explains how the library responded. || It describes the history of a bus station and then explains why it was converted. || It lists the services libraries provide and ranks them by popularity. || It argues that libraries should stop lending books. >> Officials expected borrowing; people used the tables; the library adjusted.
IN: Based on the text, the library most likely cut back its shelf space in order to || make room for more work and gathering areas. || reduce the cost of buying new books. || store laptops for students. || return the building to its original use. >> It "added twice as many tables and cut back its shelf space."

P: Researchers studying a population of lizards on a small island noticed that the lizards' toe pads, which help them grip surfaces, were larger than those of the same species on the mainland. The island's vegetation is dominated by smooth-barked trees, while the mainland population lives mostly among rough rocks. The researchers suggest that larger toe pads may give the island lizards a better grip on the slick bark they must climb.
CI:: || Island lizards may have developed larger toe pads because they need to grip smooth tree bark. || Lizards on the mainland are larger than lizards on the island. || Smooth-barked trees are spreading from the island to the mainland. || The island lizards belong to a different species from the mainland lizards. >> The text links larger toe pads to the smooth bark the island lizards climb.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It describes a difference in habitat that helps explain the difference in toe-pad size. || It questions whether the island lizards really have larger toe pads. || It introduces a second species of lizard for comparison. || It explains how the researchers measured the lizards' toe pads. >> Smooth bark versus rough rocks sets up the explanation in the final sentence.
IN: Based on the text, which situation would the researchers most likely expect? || A population of the same species living on smooth-barked trees elsewhere would also have relatively large toe pads. || Lizards moved from the island to rough rocks would immediately lose their toe pads. || Mainland lizards would climb smooth bark more easily than island lizards. || The island lizards would avoid climbing trees altogether. >> If smooth bark favors larger pads, other smooth-bark populations should show the same trait.

P: The following text is from a short story. The storm had taken the power at dusk, and by nine the house was silent except for the wind. Jalen's little sister had stopped crying an hour ago, mostly because he had turned the flashlight into a stage light and was performing every animal voice he knew. He ran out of animals around eleven. By then she was asleep, and he sat in the dark holding the flashlight, listening to the windows rattle and wishing someone would do the same for him.
CI:: || Jalen comforts his sister during a frightening storm, even though he is also frightened. || Jalen is annoyed that his sister will not stop crying during the storm. || Jalen enjoys storms because they give him a chance to perform. || Jalen's sister entertains him with animal voices until he falls asleep. >> He entertains her until she sleeps, then sits "wishing someone would do the same for him."
TS: Which choice best describes the function of the final sentence in the text as a whole? || It reveals that the character who has been reassuring someone else is also in need of reassurance. || It explains why the power went out during the storm. || It suggests that Jalen's sister is only pretending to be asleep. || It shows that the storm has finally ended. >> The last detail reveals Jalen's own fear.
IN: Based on the text, why did Jalen's sister most likely stop crying? || She was distracted and amused by Jalen's performance. || The storm had ended. || The power had come back on. || She had gone to sleep before the storm began. >> The text says she stopped "mostly because" of his flashlight performance.

P: For most of the twentieth century, many linguists regarded the "uptalk" pattern, in which statements end with a rising pitch, as a sign of uncertainty. More recent studies complicate this view. In recorded conversations, speakers who used rising pitch often did so while holding the floor, signaling that they had more to say, or while checking that listeners were following along. Rather than expressing doubt, the rise frequently seemed to invite engagement.
CI:: || Recent research suggests that rising pitch at the end of statements often serves purposes other than expressing uncertainty. || Speakers who use rising pitch are usually unsure of what they are saying. || Linguists have stopped studying the way people speak in conversations. || Rising pitch is used more often in writing than in speech. >> The text contrasts the older view (uncertainty) with newer findings (holding the floor, checking understanding).
TS: Which choice best describes the overall structure of the text? || It presents a traditional interpretation and then describes findings that challenge it. || It defines a speech pattern and then traces its geographic spread. || It describes an experiment and then explains why its results were rejected. || It argues that rising pitch should be avoided in formal speech. >> Older view, then "more recent studies complicate this view."
IN: Based on the text, a speaker who uses rising pitch in the middle of a long story is most likely || signaling that the story is not finished. || admitting that parts of the story may be untrue. || asking a listener to tell a different story. || trying to end the conversation. >> Speakers used rising pitch "while holding the floor, signaling that they had more to say."

P: In 1928, the town of Eastbridge replaced its wooden footbridge with a concrete one. The new bridge was stronger, but residents soon noticed that the swallows that had nested beneath the old bridge for generations were gone. The birds' mud nests could not cling to the smooth concrete. In 2019, volunteers attached rough wooden panels to the underside of the bridge. The following spring, the swallows returned.
CI:: || Swallows left a bridge when its surface became too smooth for their nests and returned after rough panels were added. || Wooden bridges are generally stronger than concrete bridges. || Swallows prefer to nest near rivers rather than near towns. || The town of Eastbridge rebuilt its bridge in 2019 using wood. >> The text links the smooth concrete to the swallows' departure and the rough panels to their return.
TS: Which choice best states the main purpose of the text? || To explain how a change in a bridge's material affected nesting birds and how that effect was reversed || To argue that towns should build bridges from wood rather than concrete || To describe how swallows build nests from mud || To trace the complete history of bridge construction in Eastbridge >> Cause (smooth concrete), effect (swallows left), and fix (rough panels).
IN: Based on the text, the volunteers most likely chose rough wooden panels because || the swallows' mud nests could cling to a rough surface. || wood is less expensive than concrete. || rough panels made the bridge stronger. || the town wanted to restore the original wooden bridge. >> The nests "could not cling to the smooth concrete," so a rough surface would help.

P: Economists sometimes describe a "cobra effect," in which a policy produces the opposite of its intended result. The term comes from a story, possibly exaggerated, about a reward once offered for dead cobras to reduce their numbers. Some residents reportedly began breeding cobras to collect the reward. When officials canceled the program, the breeders released their now-worthless snakes, leaving more cobras than before. Whether or not every detail is accurate, economists use the story to show how incentives can backfire.
CI:: || The "cobra effect" illustrates how a policy's incentives can lead to results opposite to those intended. || Governments should never offer rewards to reduce animal populations. || Economists have proven that the cobra story is entirely true. || Breeding snakes is a common way to earn money in many countries. >> The story shows a reward meant to reduce cobras ending up increasing them.
TS: Which choice best describes the function of the phrase "possibly exaggerated" in the text? || It acknowledges that the story may not be completely accurate. || It suggests that the policy was more successful than reported. || It indicates that economists invented the story. || It emphasizes how dangerous cobras are. >> The phrase signals doubt about the story's details, echoed in "whether or not every detail is accurate."
IN: Based on the text, which situation would an economist most likely describe as an example of the cobra effect? || A city pays people for each rat tail they turn in, and some people begin raising rats. || A city lowers bus fares, and more people ride the bus. || A town plants trees, and summer temperatures fall. || A school adds tutoring, and test scores rise. >> Only this example shows an incentive producing more of the problem it was meant to reduce.

P: The following text is adapted from a travel essay. The market opens before the sun does. By five, vendors have unfolded their tables and arranged pyramids of oranges and bundles of herbs still wet with dew. By seven, the aisles are so crowded that shoppers move sideways. By noon it is over: the tables fold, the tarps come down, and a street cleaner sweeps away the last crushed petals. An hour later, no one walking by would guess that a thousand people had passed through that morning.
CI:: || A busy morning market appears and disappears so completely that little evidence of it remains by early afternoon. || The market is too crowded for shoppers to enjoy. || Vendors at the market sell mainly oranges and herbs. || The market stays open from early morning until late at night. >> The essay follows the market from setup to cleanup and ends with how completely it vanishes.
TS: Which choice best describes the overall structure of the text? || It follows a market through a single morning in chronological order. || It compares two markets in different cities. || It describes a market and then argues that it should be moved. || It explains how vendors at the market set their prices. >> The time markers "by five," "by seven," "by noon," and "an hour later" show chronological order.
IN: Based on the text, which statement about the market is most reasonable? || It is popular despite operating for only a few hours. || It attracts very few customers on most days. || Its vendors leave their tables set up overnight. || It sells mostly items that were imported from far away. >> A thousand people pass through, yet it runs only from before dawn to noon.

P: Octopuses have a remarkable ability to taste with their arms. Each arm is lined with suckers containing thousands of chemical receptors, allowing an octopus to detect prey hidden in crevices simply by touching the surrounding rock. Researchers have also found that an arm can begin reacting to a promising scent before the octopus's central brain appears to direct it, suggesting that each arm processes some information on its own.
CI:: || Octopus arms contain chemical receptors that let them sense prey and may process some information independently. || Octopuses rely mainly on eyesight to locate prey. || Octopuses taste food only after bringing it to their mouths. || An octopus's central brain controls every movement of its arms. >> The text describes receptors in the suckers and arms that react before the central brain seems to direct them.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It presents a finding that extends the text's description of the octopus's arms. || It contradicts the claim made in the first sentence. || It explains why octopuses hide in crevices. || It introduces a different animal for comparison. >> The last sentence adds that arms may process information on their own.
IN: Based on the text, an octopus exploring a rocky reef could most likely || detect a crab hidden inside a crack without seeing it. || taste only the prey that it can see. || locate prey only when its arms are still. || avoid touching rocks while hunting. >> It can "detect prey hidden in crevices simply by touching the surrounding rock."

P: When a small publisher decided to print its novels on paper made from recycled cotton clothing, some booksellers worried that readers would dislike the paper's slightly rough texture. The publisher included a short note at the back of each book explaining where the paper came from. Sales of the new editions matched those of the old ones, and many readers wrote to say that the note had made them notice and appreciate the feel of the pages.
CI:: || A publisher's switch to recycled-clothing paper did not hurt sales, and many readers came to appreciate the paper. || Readers strongly disliked the rough texture of books printed on recycled paper. || Booksellers convinced the publisher to stop using recycled paper. || Paper made from cotton clothing is less expensive than ordinary paper. >> Sales held steady, and readers wrote that they appreciated the pages.
TS: Which choice best describes the overall structure of the text? || It describes a change, a concern about that change, and the outcome that followed. || It explains how recycled paper is manufactured, step by step. || It compares the prices of two kinds of paper. || It argues that all publishers should use recycled paper. >> The switch, booksellers' worry, then sales and reader responses.
IN: Based on the text, the note at the back of each book most likely || shaped how readers perceived the paper's texture. || caused sales of the new editions to fall. || listed other books printed on recycled paper. || replaced the need for a table of contents. >> Readers said the note "had made them notice and appreciate the feel of the pages."

P: Glass frogs, found in Central and South American rain forests, have translucent skin on their undersides. For years, scientists assumed this transparency simply helped the frogs blend in with the leaves they rest on. A recent study found something more surprising: while sleeping, a glass frog moves most of its red blood cells into its liver, making its body far more transparent. When the frog wakes and becomes active, the blood cells return to circulation.
CI:: || Glass frogs become more transparent while sleeping by storing most of their red blood cells in their liver. || Glass frogs are completely invisible during the day. || Glass frogs live mostly on the forest floor rather than on leaves. || Glass frogs lose their red blood cells permanently as they age. >> The study found that the frogs hide blood cells in the liver while sleeping, increasing transparency.
TS: Which choice best describes the function of the second sentence in the text as a whole? || It presents an earlier understanding that the study's finding goes beyond. || It describes the method the researchers used in their study. || It explains why glass frogs are found only in rain forests. || It offers a conclusion that the rest of the text supports. >> "For years, scientists assumed" sets up "a recent study found something more surprising."
IN: Based on the text, a glass frog would most likely be least transparent when it is || hopping between leaves in search of food. || sleeping on a leaf during the day. || resting motionless on the underside of a leaf. || hiding with most of its blood stored in its liver. >> When the frog is active, "the blood cells return to circulation," reducing transparency.

P: In the early years of the sport, marathon courses varied widely in length, from about 40 to 42 kilometers. Records set on one course could not be fairly compared with those set on another. In 1921, athletics officials adopted a standard distance of 42.195 kilometers, the length of a well-known course from a previous international competition. Only after that decision did marathon records become meaningful across different races.
CI:: || Standardizing the marathon's distance made it possible to compare records set in different races. || The first marathons were longer than modern marathons. || Athletics officials chose the marathon distance at random. || Marathon records were more impressive before the distance was standardized. >> Varied lengths made comparisons unfair until a standard distance was adopted.
TS: Which choice best describes the overall structure of the text? || It identifies a problem with early marathons and then describes the decision that solved it. || It describes a famous marathon runner's career from beginning to end. || It compares marathon training methods across several decades. || It argues that marathons should be shorter. >> Varied course lengths (problem), then the 1921 standard (solution).
IN: Based on the text, before 1921 a runner who set a record on a 40-kilometer course would most likely || not be fairly compared with a runner who set a record on a 42-kilometer course. || be disqualified from future races. || hold the official world record for the marathon. || be required to run the course again. >> "Records set on one course could not be fairly compared with those set on another."

P: A team of volunteers in a coastal town spent a summer recording every species of bird they saw along a single kilometer of shoreline. They expected to count perhaps thirty species. They counted seventy-two. Several were migrants resting for only a day or two, which the volunteers would have missed if they had visited less often. The team concluded that frequent, repeated observation reveals far more about a place than occasional surveys do.
CI:: || Frequent observation revealed many more bird species along a shoreline than volunteers had expected, including brief visitors. || The shoreline is home to fewer bird species than most volunteers believed. || Migrant birds never stop along coastal shorelines. || Occasional surveys are more accurate than frequent observation. >> Seventy-two species, including one- or two-day migrants, led the team to value frequent observation.
TS: Which choice best describes the function of the sentence "They counted seventy-two" in the text as a whole? || It reveals that the result far exceeded the volunteers' expectations. || It explains the method the volunteers used to count birds. || It lists the most common species along the shoreline. || It questions the accuracy of the volunteers' count. >> It follows "They expected to count perhaps thirty species."
IN: Based on the text, a researcher who surveyed the same shoreline only once a month would most likely || record fewer species than the volunteers did. || record more migrant species than the volunteers did. || record exactly seventy-two species. || find that no migrants visit the shoreline. >> Several migrants stayed only a day or two and would be missed by less frequent visits.

P: The following text is from a novel. Grandfather's garden was a map of his life. The fig tree by the gate came from a cutting he had carried across an ocean wrapped in a damp shirt. The roses along the fence had been a gift on the day my mother was born. And the stubborn patch of mint, which he pulled up every spring and which grew back every summer, he said reminded him of himself.
CI:: || The narrator's grandfather sees the plants in his garden as connected to important parts of his life. || The narrator's grandfather dislikes the mint that grows in his garden. || The narrator's mother planted most of the garden. || The garden contains only plants brought from another country. >> Each plant is linked to a memory or trait, making the garden "a map of his life."
TS: Which choice best describes the function of the first sentence in the text as a whole? || It states a central idea that the following details illustrate. || It describes a problem that the rest of the text resolves. || It introduces a character who appears only once in the text. || It contrasts the garden with another place in the novel. >> The fig tree, roses, and mint each show how the garden maps his life.
IN: Based on the text, the grandfather most likely compares himself to the mint because he sees himself as || persistent in the face of repeated setbacks. || difficult for others to understand. || unable to grow in a new place. || gentle and easily discouraged. >> The mint is "stubborn" and grows back every summer after being pulled up.

P: Some city parks departments have begun replacing lawns with patches of native wildflowers and grasses. Lawns must be mowed, watered, and fertilized regularly, which is costly. Native plants, once established, need little water and almost no mowing. They also provide food for bees and butterflies. Critics argue that the plantings look untidy, but supporters point out that many residents have come to enjoy the changing colors through the seasons.
CI:: || Some parks are replacing lawns with native plants, which cost less to maintain and support pollinators, though not everyone likes their appearance. || Native plants require more water than traditional lawns. || Residents have unanimously opposed replacing lawns with wildflowers. || City parks departments plan to remove all grass from public parks. >> The text gives the reasons for the change and notes both criticism and support.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It presents an objection to the plantings along with a response to that objection. || It summarizes the costs of maintaining lawns. || It explains how native plants are established. || It concludes that the plantings should be removed. >> Critics call them untidy; supporters note residents enjoy them.
IN: Based on the text, a parks department that switches from lawns to native plantings would most likely || spend less on mowing and watering once the plants are established. || need to fertilize its parks more often. || attract fewer bees and butterflies. || receive no complaints about the parks' appearance. >> Native plants "need little water and almost no mowing" once established.

P: Early mapmakers often filled the unexplored edges of their maps with drawings of sea monsters. Historians once treated these images as simple decoration or evidence of superstition. One historian has proposed a different reading: many of the creatures closely resemble descriptions from sailors' reports of whales, walruses, and giant squid. On this view, the drawings were mapmakers' attempts, however imperfect, to record real animals that travelers had described.
CI:: || One historian argues that sea monsters on early maps may represent attempts to depict real animals described by sailors. || Early mapmakers invented sea monsters to frighten sailors away from certain waters. || Historians agree that sea monsters on maps were purely decorative. || Early sailors never encountered whales or giant squid. >> The text presents the historian's reading that the drawings recorded real animals.
TS: Which choice best describes the overall structure of the text? || It describes a feature of early maps, gives a traditional interpretation of it, and then presents an alternative interpretation. || It explains how early maps were made and then lists their errors. || It describes a sailor's voyage and then analyzes the map he used. || It argues that modern maps are less accurate than early maps. >> Feature (sea monsters), old view (decoration/superstition), new view (records of real animals).
IN: Based on the text, which finding would be most consistent with the historian's view? || A map's sea monster closely matches a sailor's written description of a walrus from the same period. || A map's sea monster appears in an area where no sailor had traveled. || Mapmakers of the period described their drawings as purely imaginary. || Sea monsters appear on maps only after whales had been scientifically described. >> A close match between a drawing and a sailor's description supports the idea that the drawings recorded real animals.

P: When engineers designed a new high-speed train, they faced an unexpected problem: each time the train exited a tunnel at full speed, it produced a loud boom that disturbed nearby residents. The cause was air compressed in front of the train's blunt nose. An engineer who was also a birdwatcher noticed that kingfishers dive from air into water, a much denser medium, with barely a splash. The team redesigned the train's nose to resemble a kingfisher's long, narrow beak, and the booms largely stopped.
CI:: || Engineers reduced noise from a high-speed train by redesigning its nose to resemble a kingfisher's beak. || Kingfishers are affected by noise from high-speed trains. || High-speed trains cannot travel through tunnels. || The train's original nose was designed to resemble a bird's beak. >> The problem (booms), cause (compressed air), inspiration (kingfisher), and solution (new nose).
TS: Which choice best describes the function of the third sentence in the text as a whole? || It describes an observation that inspired a solution to the problem. || It explains why residents complained about the train. || It presents a second problem the engineers faced. || It suggests that kingfishers are disturbed by trains. >> The kingfisher observation led to the redesigned nose.
IN: Based on the text, the kingfisher's beak was a useful model most likely because it || allows the bird to move from one medium into a denser one with little disturbance. || is brightly colored and easy to see. || helps the bird catch fish more quickly than other birds. || produces a loud sound when the bird dives. >> Kingfishers dive into denser water "with barely a splash," similar to a train entering the dense air of a tunnel.

P: Scientists studying tree rings from a forest in a dry region found that rings formed during years of heavy rainfall were noticeably wider than rings from drought years. By measuring rings in trees that were hundreds of years old, the team reconstructed a record of rainfall stretching back far earlier than any written weather records from the area. The reconstruction revealed several long droughts that had not previously been documented.
CI:: || Tree rings allowed scientists to reconstruct a long rainfall record and identify previously unknown droughts. || Trees in dry regions grow faster during droughts than during wet years. || Written weather records from the area go back hundreds of years. || Scientists planted new trees to measure future rainfall. >> Ring widths reflected rainfall, allowing a reconstruction that revealed undocumented droughts.
TS: Which choice best describes the overall structure of the text? || It describes a relationship between tree rings and rainfall and then explains what scientists learned by using it. || It compares two forests and explains why one grew faster. || It questions whether tree rings can reveal information about the past. || It describes a drought and its effects on local farmers. >> The ring-rainfall link, then the reconstruction and its findings.
IN: Based on the text, a series of unusually narrow rings in a tree most likely indicates || a period of low rainfall. || a period of heavy rainfall. || a year when the tree was planted. || a mistake in the scientists' measurements. >> Rings from drought years were narrower than rings from wet years.

P: The following text is from a memoir. My father never told me he was proud of me. He was not a man who said such things. But every newspaper clipping that mentioned my name, even a single line about a spelling bee, ended up in a folder in his desk drawer. I found the folder after he died. It was two inches thick.
CI:: || The narrator discovers after her father's death evidence of the pride he never expressed aloud. || The narrator's father disapproved of her achievements. || The narrator kept newspaper clippings about her father. || The narrator won many spelling bees as a child. >> The folder of clippings shows the pride her father "never told" her about.
TS: Which choice best describes the function of the final sentence in the text as a whole? || It emphasizes how carefully and extensively the father had followed the narrator's accomplishments. || It explains why the father never spoke about his feelings. || It suggests that the folder contained mostly unrelated articles. || It reveals that the narrator was disappointed by what she found. >> The folder's thickness underscores how much he collected.
IN: Based on the text, which statement about the narrator's father is most reasonable? || He valued her achievements even though he did not say so. || He rarely read the newspaper. || He wanted the narrator to become a journalist. || He kept the folder hidden because he was ashamed of it. >> He saved every clipping, "even a single line," despite never saying he was proud.
"""
